### ISSUE TITLE
Radarr downloading the same movie NZB multiple times

### ISSUE THREAD

**Issue by gold007eye** [Radarr/Radarr#1108]
**Description:**

I have 2 movies now in the past 2 days that found releases and downloaded the requested quality of the movie.  For some reason though radarr keeps sending that same exact NZB request to SABnzbd.  I can't seem to figure out why this keeps happening.  The downloads complete successfully and and Radarr is even showing the movie as "Downloaded", but yet doesn't seem to know internally that it has been downloaded successfully.

Is there something I am doing wrong?  I have this setup basically the same as Sonarr and never have this problem with TV shows.   Seems to be something with the Automatic search or the fact that it isn't "Un-monitoring" the movie once the requested quality has been grabbed successfully or at a minimum I would think that it should recognize that the NZB has already been grabbed and not to grab it again.

![image](https://cloud.githubusercontent.com/assets/4365462/23802335/9bc03382-0578-11e7-98ed-57be35996167.png)

![image](https://cloud.githubusercontent.com/assets/4365462/23802298/798c25e6-0578-11e7-9290-36579eea6a54.png)

![image](https://cloud.githubusercontent.com/assets/4365462/23802400/d1a3cae0-0578-11e7-9e19-fb3d836b5258.png)

![image](https://cloud.githubusercontent.com/assets/4365462/23802371/bc8fb43e-0578-11e7-9565-3cb753e46e1a.png)

**Radarr Version:**
0.2.0.453

**Logs:**
`17-3-10 05:53:23.8|Info|Sabnzbd|Adding report [Assassins.Creed.2016.720p.WEB-DL.X264.AC3-EVO] to the queue.
17-3-10 05:53:24.2|Info|DownloadService|Report sent to SABnzbd. Assassins.Creed.2016.720p.WEB-DL.X264.AC3-EVO
17-3-10 05:53:25.1|Info|RssSyncService|RSS Sync Completed. Reports found: 100, Reports grabbed: 1
17-3-10 06:06:10.4|Info|NetImportSearchService|No lists are enabled for auto-import.
17-3-10 06:38:54.3|Info|RssSyncService|Starting RSS Sync
17-3-10 06:38:56.2|Info|DownloadDecisionMaker|Processing 100 releases
17-3-10 06:38:58.2|Info|Sabnzbd|Adding report [Assassins.Creed.2016.720p.WEB-DL.X264.AC3-EVO] to the queue.
17-3-10 06:38:58.6|Info|DownloadService|Report sent to SABnzbd. Assassins.Creed.2016.720p.WEB-DL.X264.AC3-EVO
17-3-10 06:38:59.4|Info|RssSyncService|RSS Sync Completed. Reports found: 100, Reports grabbed: 1
17-3-10 06:42:41.0|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. T:\Movies\Assassin's Creed (2016)\Assassin's Creed (2016).mkv
17-3-10 07:06:23.0|Info|NetImportSearchService|No lists are enabled for auto-import.
17-3-10 07:24:01.1|Info|RssSyncService|Starting RSS Sync
17-3-10 07:24:02.8|Info|DownloadDecisionMaker|Processing 100 releases
17-3-10 07:24:04.9|Info|Sabnzbd|Adding report [Assassins.Creed.2016.720p.WEB-DL.X264.AC3-EVO] to the queue.
17-3-10 07:24:05.2|Info|DownloadService|Report sent to SABnzbd. Assassins.Creed.2016.720p.WEB-DL.X264.AC3-EVO
17-3-10 07:24:06.0|Info|RssSyncService|RSS Sync Completed. Reports found: 100, Reports grabbed: 1
17-3-10 07:27:44.7|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. T:\Movies\Assassin's Creed (2016)\Assassin's Creed (2016).mkv
17-3-10 08:06:29.9|Info|NetImportSearchService|No lists are enabled for auto-import.
17-3-10 08:09:31.3|Info|RssSyncService|Starting RSS Sync
17-3-10 08:09:33.0|Info|DownloadDecisionMaker|Processing 100 releases
17-3-10 08:09:34.9|Info|Sabnzbd|Adding report [Assassins.Creed.2016.720p.WEB-DL.X264.AC3-EVO] to the queue.
17-3-10 08:09:35.3|Info|DownloadService|Report sent to SABnzbd. Assassins.Creed.2016.720p.WEB-DL.X264.AC3-EVO
17-3-10 08:09:36.2|Info|RssSyncService|RSS Sync Completed. Reports found: 100, Reports grabbed: 1
17-3-10 08:13:15.0|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. T:\Movies\Assassin's Creed (2016)\Assassin's Creed (2016).mkv
17-3-10 08:55:04.8|Info|RssSyncService|Starting RSS Sync
17-3-10 08:55:06.4|Info|DownloadDecisionMaker|Processing 100 releases
17-3-10 08:55:08.4|Info|Sabnzbd|Adding report [Assassins.Creed.2016.720p.WEB-DL.X264.AC3-EVO] to the queue.
17-3-10 08:55:08.8|Info|DownloadService|Report sent to SABnzbd. Assassins.Creed.2016.720p.WEB-DL.X264.AC3-EVO
17-3-10 08:55:09.5|Info|RssSyncService|RSS Sync Completed. Reports found: 100, Reports grabbed: 1
17-3-10 08:58:46.9|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. T:\Movies\Assassin's Creed (2016)\Assassin's Creed (2016).mkv
17-3-10 09:06:48.7|Info|NetImportSearchService|No lists are enabled for auto-import.
17-3-10 09:40:34.8|Info|RssSyncService|Starting RSS Sync
17-3-10 09:40:36.4|Info|DownloadDecisionMaker|Processing 100 releases
17-3-10 09:40:38.4|Info|Sabnzbd|Adding report [Assassins.Creed.2016.720p.WEB-DL.X264.AC3-EVO] to the queue.
17-3-10 09:40:38.8|Info|DownloadService|Report sent to SABnzbd. Assassins.Creed.2016.720p.WEB-DL.X264.AC3-EVO
17-3-10 09:40:39.5|Info|RssSyncService|RSS Sync Completed. Reports found: 100, Reports grabbed: 1`

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by onedr0p** [comment]
Can you switch to the nightlies and see if this still happens? I made changes I think will fix this issue.

**Comment by onedr0p** [comment]
Also please post your profile settings for that profile.

**Comment by gold007eye** [comment]
I have switched to nightlies.  I will have to see the next thing that comes out if it still does this.  Or could I just mark these as "Watch" again to see if it re-triggers the issue?

Here are the profile settings:
![image](https://cloud.githubusercontent.com/assets/4365462/23804034/26db3d2c-057e-11e7-9ab1-b9f4e8732ade.png)

**Comment by onedr0p** [comment]
Please post screenshot of profile settings for hd-720p.

You can remove the files, refresh the movie, and remove from your radarr / sab history. Then perform a manual search, let it download, then when it completes, try manual search again.

**Comment by gold007eye** [comment]
Here is the screenshot requested.
![image](https://cloud.githubusercontent.com/assets/4365462/23808792/c73a0b2e-0590-11e7-8444-7b1cfc282d4b.png)

**Comment by gold007eye** [comment]
Is there away to have a setting to delete any of the Qualities that we would never want to search for / need so those aren't included in search results only the qualities that we would ever want would show in results instead.

**Comment by ghallford** [comment]
I am having the same issue. Multiple downloads. I am on nightlies and have been for a couple of weeks

**Comment by gold007eye** [comment]
@onedr0p I have tried what you said with Assassin's Creed as my test and it has the same thing again.  Even switching to nightlies.

For some reason Radarr keeps deleting the movie and then re-downloading the same thing,

![image](https://cloud.githubusercontent.com/assets/4365462/23824377/46a5ffb2-063b-11e7-987b-6cb6d5d848df.png)

![image](https://cloud.githubusercontent.com/assets/4365462/23824370/0e7aae12-063b-11e7-9876-7f8d54181ff7.png)

**Comment by onedr0p** [comment]
@galli-leo do you have any idea why this is happening? I cannot reproduce this. Maybe it's a problem with sab.

**Comment by ghallford** [comment]
I am using nzbget, same issue though. Radarr sends multiple downloads at the same time.

⁣
--
Geoff Hallford​

**Comment by onedr0p** [comment]
How were these movies added to radarr, lists, search, bulk import, ombi?

**Comment by onedr0p** [comment]
If it's not happening for all movies we need to pinpoint a common issue.

**Comment by ghallford** [comment]
Mine were Trakt List. 

⁣
--
Geoff Hallford​

**Comment by gold007eye** [comment]
Mine were manually added.

**Comment by galli-leo** [comment]
@onedr0p No idea what could be happening here. @gold007eye & @ghallford Do you guys see anything in the logs?

**Comment by ghallford** [comment]
I don't know why but mine is no longer adding multiple copies of the same
movie for download

**Comment by onedr0p** [comment]
Must have been related to the search on list sync bug. I disabled last night until we get it working.

**Comment by gold007eye** [comment]
Just as a followup I experienced this same issue on "Resident Evil - The Final Chapter" last night into this morning.  Again  manually added (not from a list).

I think this time it is because the file is showing as "Missing" yet the Files tab clearly has it listed. 1st image shows movie page (missing status), 2nd images is showing "Downloaded" AFTER manually refreshing the movie page, image 3 is the history showing same thing as before with the movie getting deleted and then re-downloaded again and showing that it was bouncing between grabbing "720p and 1080p"

![image](https://cloud.githubusercontent.com/assets/4365462/23948143/b1b78bf6-094f-11e7-8b43-fca8f9958632.png)

![image](https://cloud.githubusercontent.com/assets/4365462/23948214/02e521fa-0950-11e7-95fd-137106749d3e.png)

![image](https://cloud.githubusercontent.com/assets/4365462/23948283/5c3782ac-0950-11e7-9417-5f7d9e95584e.png)

**Comment by gold007eye** [comment]
Also not sure to go with the above if this makes a difference, but it looks like it's not marking things as downloaded or failed when looking under the search.  

![image](https://cloud.githubusercontent.com/assets/4365462/23948403/dea8bac6-0950-11e7-8a29-1545cbd79425.png)

Sab Log
![image](https://cloud.githubusercontent.com/assets/4365462/23948458/0d75b552-0951-11e7-9c15-a05ccbf273cb.png)

**Comment by darknessgp** [comment]
I'm not sure if this is related... but it looks like it may be. I've gotten multiple items sent to my torrent client before finally one works and marks the movie as downloaded. Though this may not be related because the first one wasn't labelled by radarr correctly, so I'm thinking it didn't ever really see that it was added.

![multiple1](https://cloud.githubusercontent.com/assets/1521243/23964516/c422e938-0982-11e7-82ae-0ed3f870d97f.JPG)
![multiple2](https://cloud.githubusercontent.com/assets/1521243/23964515/c41fb9ac-0982-11e7-9a7f-c04132e59a01.JPG)
![multiple3](https://cloud.githubusercontent.com/assets/1521243/23964640/1c50db1a-0983-11e7-97e7-d790436dc4e6.JPG)

**Comment by onedr0p** [comment]
I think I have a fix for this in the nightly soon.

**Comment by SuperPotatoMen** [comment]
@onedr0p is there also a fix to prevent snatching a movie if it already in the library?

**Comment by onedr0p** [comment]
That is another issue, related to the lists?

**Comment by bonyboy** [comment]
Having the same problem.  Created a custom list in Trakt and added a few movies.  Radarr has each movie (same release) queued up twice.  Running 0.2.0.535 on Ubuntu Server.

**Comment by Stibbons** [comment]
Appears also with custom trakt.tv list.

**Comment by galli-leo** [comment]
@Stibbons Are you on .535?

**Comment by Stibbons** [comment]
yes

**Comment by gold007eye** [comment]
Just an update.. I think I know what might be causing the downloading to start, finish, delete and restart the same download.  I just noticed with the next movie. it is grabbing as "Blue-Ray 720", but Radarr is tagging the completed download as "**HDTV**-720p"  So then it regrabs the movie again, because "technically" that doesn't meet the cut-off quality.  

That looks like remnants of Sonarr coding maybe fixing that will fix this issue?  If you look at the previous images of mine above showing the history you see the same thing happened.. Radarr setting finished downloaded quality as HDTV-720.

![image](https://cloud.githubusercontent.com/assets/4365462/24717086/d9bae884-19f6-11e7-8a5f-8784b78dc394.png)

**Comment by Stibbons** [comment]
Not sure it is the same bug. Your case is 1 successful download then Radarr tries to redownload it because it thinks the cut off is not met.

Here we see that at the same moment the very same nzb is sent twice at sabnzbd.

**Comment by gold007eye** [comment]
The reason there is only 1 time is because I turned the monitoring off as soon as I saw it starting this process.. just like my original post.  So I knew it was just gonna keep downloading infinitely until I unmonitored it :)  It's definitely the same bug as my original post.  I was just giving more incite as to another possible avenue as to why it is happening.

**Comment by galli-leo** [comment]
@gold007eye Can you make a new issue and copy over your comment? They are not related by the way.

**Comment by galli-leo** [comment]
@Stibbons we know what causes this and reverted the change for the nightlies. This should be fixed for the next pre-release.

**Comment by gold007eye** [comment]
New issue created as #1321

**Comment by galli-leo** [comment]
Can you guys confirm this issue is fixed on the latest release?

**Comment by Stibbons** [comment]
I did not seen it so far since latest version.

**Comment by Grygon** [comment]
Experiencing this in .778

![image](https://user-images.githubusercontent.com/647846/29237984-cdfba310-7ef7-11e7-96e1-45dd19636941.png)
![image](https://user-images.githubusercontent.com/647846/29237986-db671e94-7ef7-11e7-8cc7-3d7f6f6d7343.png)

**Comment by 3phreal** [comment]
I've seen this problem in 0.2.0.846.

![image](https://user-images.githubusercontent.com/33040834/31912260-9343b890-b843-11e7-8c69-826f85cd3261.png)

![image](https://user-images.githubusercontent.com/33040834/31912277-a1f67f62-b843-11e7-9c6c-4a4c3c53b3aa.png)

![image](https://user-images.githubusercontent.com/33040834/31912293-adde8068-b843-11e7-917f-d6e0544b98ce.png)

Any suggestion on how to fix this 

Regards

**Comment by gold007eye** [comment]
Actually it's doing what I mentioned months ago still. It's using TV tags to mark quality.  HDTV is what is used in sonarr.  In my opinion these should be completely removed from radarr and that would fix the issue.

**Comment by 3phreal** [comment]
But not only HDTV its also setting the wrong resolution. it sets it to HDTV 720p. Is there a work around ?

**Comment by bott0r** [comment]
also seeing this issue

**Comment by galli-leo** [comment]
Can you guys post the name of the downloaded file / folder?

**Comment by tretneo** [comment]
I've seen this repeatedly with several movies over the past month after having no such issues for at least 6 months with the same setup. I'll provide some detail below:

Guest OS: Ubuntu Server 16.04.2 LTS x64 (VMware VM)
Radarr: Currently running 0.2.0.902
Downloader: SABnzbd+ 2.1.0 [443efb5] (Same Guest OS, separate VMware VM)
Storage: Synology SMB Share full read/write (DSM 6.1.3-15152 Update 8)

<img width="1355" alt="screen shot 2017-11-22 at 8 57 02 am" src="https://user-images.githubusercontent.com/33906766/33140118-e634a474-cf63-11e7-8c97-b482c2b0bdc2.png">

In the screenshot above, the following movies exhibited the behavior whereby it was re-downloaded at least once and it's quality (Bluray-1080p) wasn't recognized and it was imported as HDTV-720p.

- Valerian and the City of a Thousand Planets
- Atomic Blonde
- Jim & Andy: The Great Beyond - Featuring a Very Special, Contractually Obligated Mention of Tony Clifton

Here are the full paths for these titles. Note: The SMB share mount point root path is /mnt/caprica6/media/Movies

/mnt/caprica6/media/Movies/Valerian and the City of a Thousand Planets (2017)
/mnt/caprica6/media/Movies/Atomic Blonde (2017)
/mnt/caprica6/media/Movies/Jim & Andy The Great Beyond - Featuring a Very Special, Contractually Obligated Mention of Tony Clifton (2017)

Thanks,
Rob

**Comment by Frostosties** [comment]
![2017-12-07](https://user-images.githubusercontent.com/34330651/33700999-381cee32-db25-11e7-9124-a6026380f925.png)
![2017-12-07 2](https://user-images.githubusercontent.com/34330651/33701000-38524956-db25-11e7-9b4b-9d8fe7fa1fc4.png)
![2017-12-07 3](https://user-images.githubusercontent.com/34330651/33701001-38881a54-db25-11e7-9c19-d118dee77620.png)
I am also getting duplicate grabs, not sure if this is download station related ?
I was on stable build, upgraded to Ver. 0.2.0.903 nightly to see if it helps but still the same.

**Comment by eappell** [comment]
Can't tell if this has been resolved, but I'm on the current build (Ver. 0.2.0.910) and it happened to me just yesterday.  I have to turn off Radarr until this gets resolved.  I can't have this downloading movies 10+ times.  Any progress on this issue?  I'll be happy to upload any logs, screenshots, etc. if it would be helpful.  I'm running it on a Synology NAS (DS 415+) running the latest version of the OS.
<img width="1045" alt="screen shot 2018-01-17 at 4 59 29 pm" src="https://user-images.githubusercontent.com/85969/35075480-143d9d10-fba8-11e7-8d3f-22f02e08e92e.png">
<img width="1177" alt="screen shot 2018-01-17 at 6 42 44 am" src="https://user-images.githubusercontent.com/85969/35075481-14565760-fba8-11e7-81af-fbdc0721c7cb.png">

**Comment by Jbot747** [comment]
there are several posts with people reporting this problem, most end with the moderator stating its been fixed in the latest nightly build,. IT IS NOT fixed, I had two instance this week;

![image](https://user-images.githubusercontent.com/19929422/35189826-0d423acc-fe08-11e7-92d8-bce77e72923c.png)

![image](https://user-images.githubusercontent.com/19929422/35189849-7c0dc174-fe08-11e7-918b-b9d6f9ab2366.png)

Disabling the radarr service and switching back to Couch Potato until this is finally fixed

**Comment by jat80** [comment]
This is so annoying and still happening.  It’s downloaded the move “The Star 2017) via SABNZBD 24 times over night with totalling over 100gb of my data usage.  This is a HUGE PROBLEM.  

One thing I’ve noticed is if I have more than 10 movies on my list it won’t show the second page in raddar.  But when I search for the added movie it comes up.  All the recent movies added and have been downloaded multiply times were more than the initial 10 hence could not go to the 2nd page to view them without manually searching for them.

**Comment by jat80** [comment]
I’ve also noticed that the original file downloaded into its own movie folder was and AVI file which is not in the profile quality I use then all subsequent downloads are put into the parent movie folder without its own folder just the file itself which is the right quality but repeatedly downloads the same file over and over again

**Comment by victormarante** [comment]
Bump. Any new information regarding this? Still having the issues with Radarr and SABnzbd.

**Comment by fr33kster** [comment]
I have been having the same issue for a couple of weeks. The data usage is becoming a serious problem. Is there anyway to stop this?

**Comment by galli-leo** [comment]
@fr33kster @victormarante Please post some logs, as well as screenshots of the history of movies, where this happens. This is usually due to bad indexer naming and is fixed on the latest nightly.

**Comment by primeinc** [comment]
Definitely not fixed. I added a bunch of movies and had to delete the whole queue of like 5TB worth for 160+ Nzbs from SabNZB because of this. Figured maybe i added too many movies and it got confused, tried just a couple and then this happened.

![image](https://user-images.githubusercontent.com/4395149/46475867-aae56080-c7b4-11e8-895a-d70824071366.png)
![image](https://user-images.githubusercontent.com/4395149/46475884-b46ec880-c7b4-11e8-8290-b4b7cd8e22cb.png)

**Comment by galli-leo** [comment]
@primeinc It’s fixed on nightly

**Comment by primeinc** [comment]
@galli-leo  I switch to the nightly (sorry i really should have tried that first), and its pretty much fixed but it did do it at least one more time, This is from the nightly.  Maybe just a one off?

For example:
![image](https://user-images.githubusercontent.com/4395149/46507261-a85f2700-c805-11e8-9a10-9dec99ba40bb.png)
![image](https://user-images.githubusercontent.com/4395149/46507300-d93f5c00-c805-11e8-9409-a712cdedd64b.png)
![image](https://user-images.githubusercontent.com/4395149/46507334-02f88300-c806-11e8-93b9-690015e09220.png)

**Comment by galli-leo** [comment]
@primeinc Seems like Radarr had trouble getting a response from Sabnzbd, so it thought it hadn‘t added it yet (while it actually did). Thus it tried to add another release.

**Comment by AntaeusNar** [comment]
I am seeing the same thing happen with deluge and torrents. @galli-leo I think it is that it don't hear back from deluge and so tries sending more.

**Comment by achmetinternet** [comment]
I am having the same issue with torrents. Version 0.2.0.1120

**Comment by joelstad** [comment]
I am having the same issue with Radarr Ver. 0.2.0.1120 and Sabnzbd. I'm running Radarr on Windows 7 Professional, all updates/patches applied, with Sabnzbd on the same machine. I've tried starting and stopping each program (nothing is running as a service) with administrator rights and without; it doesn't seem to change the result.

**Comment by onedr0p** [comment]
You guys might want to upgrade to the new Pre-release as the fix I believe is in there.

**Comment by joelstad** [comment]
Radarr Ver. 0.2.0.1120 is the newest version I can find - is there another source I should download from. If this is the newest version available with the fix applied, the bug is still very much an issue; it's not fixed.

**Comment by primeinc** [comment]
Go to Settings->General and then scroll down to Updates, next to Branch type nightly and save. Should update to Version 0.2.0.1216

**Comment by primeinc** [comment]
If your still having a problem with 2.0.1216, (although I think it should be fixed in 1120 already) then please post some logs. I would recommend clearing all your download history from SabNZBd as well as limit the amount of queued downloads in SabNZBd. I still see this issue rarely if Sab is busy doing other things and is slow to respond to the Radarr sending over the NZB.

Definitely need those log files though, if the devs can't replicate the issue they can't fix it.

**Comment by joelstad** [comment]
Thanks for the help! I just updated to nightly, cleared Sabnzbd and restarted Radarr. I'll keep an eye on it.

**Comment by joelstad** [comment]
This is still happening. I have screenshots and can reproduce the issue. I don’t know who to get them to but leave me some instructions here and I’ll send logs and anything else you need. I’m almost always using my phone to reply and I don’t see any way to attach anything to this comment.

**Comment by galli-leo** [comment]
@joelstad On desktop you can easily attach log files. Please also post screenshots of the history for the movie in question.

**Comment by morganzero** [comment]
I'm having the same issue.
The last month or so, I've been struggling with duplicates in my sabs-queue.

This is my queue, I've highlted the duplicate ares on this page. I suspect I have a few hundreds.
![dup](https://user-images.githubusercontent.com/57449785/78032149-d8d54200-7364-11ea-8fbb-8cd74f7a490d.png)
This is a screenshot of my Sabs-queue.
![Screenshot_2020-03-31 107 9 MB s - 80 6 GB left - SABnzbd](https://user-images.githubusercontent.com/57449785/78032217-f86c6a80-7364-11ea-930c-9056a1e9d041.png)
And this is a screenshot of my queue in Radarr. Thus why I suspect a few hundreds of dupes.
![Screenshot_2020-03-31 Log Files - Radarr](https://user-images.githubusercontent.com/57449785/78032222-fb675b00-7364-11ea-8b19-f0b6e905ed02.png)

This is what I found in logs.
```
2020-3-31 13:29:57.0|Debug|Parser|Movie Parsed. Manzinger Z. Infinity - 2017 
2020-3-31 13:29:57.0|Debug|Parser|Languages parsed: French, English
2020-3-31 13:29:57.0|Debug|QualityParser|Trying to parse quality for Manzinger.Z.Infinity.2017.MULTi.1080p.BluRay.x264-Ulysse French
2020-3-31 13:29:57.0|Debug|Parser|Quality parsed: Bluray-1080p v1
2020-3-31 13:29:57.0|Debug|Parser|Release Group parsed: Ulysse
2020-3-31 13:29:57.0|Trace|ConfigService|Using default config value for 'parsingleniency' defaultValue:'Strict'
2020-3-31 13:29:57.0|Trace|ConfigService|Using default config value for 'parsingleniency' defaultValue:'Strict'
2020-3-31 13:29:57.0|Debug|Parser|Parsing string 'Manzinger.Z.Infinity.2017.MULTi.1080p.BluRay.x264-Ulysse French'
2020-3-31 13:29:57.0|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(1(8|9)|20)\d{2}(?!p|i|(1(8|9)|20)\d{2}|\]|\W(1(8|9)|20)\d{2})))+(\W+|_|$)(?!\\)
2020-3-31 13:29:57.0|Debug|Parser|Movie Parsed. Manzinger Z. Infinity - 2017 
2020-3-31 13:29:57.0|Debug|Parser|Languages parsed: French, English
2020-3-31 13:29:57.0|Debug|QualityParser|Trying to parse quality for Manzinger.Z.Infinity.2017.MULTi.1080p.BluRay.x264-Ulysse French
2020-3-31 13:29:57.0|Debug|Parser|Quality parsed: Bluray-1080p v1
2020-3-31 13:29:57.0|Debug|Parser|Release Group parsed: Ulysse
```
And here is the log attached.
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/4409343/radarr.trace.txt)

**Comment by onedr0p** [comment]
Please open a new issue, so much has changed since v2

**Comment by morganzero** [comment]
Thanks. I will!
