### ISSUE TITLE
Bug: 'Ignore Deleted Movies' not working with removed directories

### ISSUE THREAD

**Issue by 4getit** [Radarr/Radarr#1191]
The 'Ignore Deleted Movies' -option is working properly when files are removed. Movies with status 'Downloaded' change to 'Not Monitored' after the next disk scan.

However, when the directory is removed as well, this option doesn't work. The Movie stays in status 'Downloaded' and is not removed from Cutoff unmet.

(Linux latest nightly)

**Comment by galli-leo** [comment]
I know why that happens. Since atm Radarr still requires a folder for every movie, it will stop the disc scan if the folder is not there. Why would you need to delete the folder anyway?

**Comment by onedr0p** [comment]
This is prolly a duplicate of

https://github.com/Radarr/Radarr/issues/1161

**Comment by onedr0p** [comment]
Fixed in next release

**Comment by 4getit** [comment]
Thank you!

**Comment by 4getit** [comment]
I'm not sure if the 'next release' means the develop or nightly. But I just tried and it's still not working.
I think I see a message I didn't see before:

DiskScanService: Movies' root folder (/home/user/CompletedRD) is empty.

(Glad I backed up the 10K empty directories :) )

**Comment by Sek0n** [comment]
Just wanted to update that this is still happening on Dev 0.2.0.654.

Although not ideal, I setup mine to not delete directories for now, and it works like it should. It was driving me crazy until I found this post. Glad I don't have to redo my two installs. 😄

**Comment by Rouzax** [comment]
Just had this happen to me as well on Radarr Ver. 0.2.0.1120 on Windows.
@galli-leo 
Removed the Folder and file from the Movie `Tag (2018)` only to see it downloaded again couple of hours later.
The problem this is all done from private torrent trackers and since switching from CP it has really hurt my ratio because of all the undesired downloads.

Have the setting enabled to set movies to unmonitored
![image](https://user-images.githubusercontent.com/4103090/44530524-de7d9700-a6ee-11e8-9a56-978765c89516.png)

**Comment by galli-leo** [comment]
@Rouzax Radarr only sets the movies to unmonitored after running a disk scan. So during the time were you removed the folder and Radarr downloaded another copy, it very likely didn't run any disk scans. Next time you remove folders, try running a disk scan immediately after.

**Comment by Rouzax** [comment]
@galli-leo So that would only happen if for instance I have 2 qualities in my profile and when I watched the movie and deleted it it was still not the highest quality.

If it is already the highest quality Radarr would not know and have no reason to start a new download because it still thinks there is a file available, right?
