### ISSUE TITLE
Radarr picking wrong movie

### ISSUE THREAD

**Issue by Grimeton** [Radarr/Radarr#1285]
Hi,

when there are multiple movies available Radarr is picking the wrong one. 

E.g.:

- Beauty and the beast. Radarr downloads the version from 1991 even when the 2017 version is requested and when the search result contains 1991 in the file name of the NZB.
- Ghost in the Shell - Exactly the same.

Version
    0.2.0.535
Mono Version
    4.2.1 

Cu

**Comment by galli-leo** [comment]
Fixed on latest nightly version.

**Comment by onedr0p** [comment]
@galli-leo I believe this problem is still happening. Occured for me yesterday with Beauty and the Beast. I think we need to move up the logic that is search by imdbid and also pass the year to a overloaded `FindByImdbId(imdbId, year)` method.

**Comment by Grimeton** [comment]
Yeah or at least check the year in the filename. The file looks like Beauty.and.the.Beast.encoding.quality.fuzz.1991.[mp4|nzb] and is considered anyway.

**Comment by galli-leo** [comment]
@Grimeton we are doing that on the latest nightly.

**Comment by jscottdouglas** [comment]
I am on the latest nightly and have the same issue.

**Comment by vertigo235** [comment]
Having the same issue as well, only with RSS, search does not include the older movies.

**Comment by galli-leo** [comment]
Should be fixed on latest nightly. Please try it and report back.

**Comment by springjools** [comment]
It's still an issue with radarr 0.2.0.1358 (6.0.0.313 (tarball Sun Jul 14 10:28:06 UTC 2019)

Tried to download Lion King 2019 and it downloaded the one from 1984 or whatever year it's from

**Comment by Yangorang** [comment]
I'm still having this issue on 0.2.0.1504
Mulan: Rise Of A Warrior (2009) imported to Mulan (2020)
