### ISSUE TITLE
Indexer Issues on latest nightly/develop

### ISSUE THREAD

**Issue by Quiksmage** [Radarr/Radarr#1361]
I was on the latest nightly and switched back to the lastest develop after having problems, I'm getting the following when clicking test on the AHD indexer.

```
17-4-11 16:28:48.3|Debug|AwesomeHD|Downloading Feed https://awesome-hd.me/searchapi.php?action=latestmovies&passkey=(removed)
17-4-11 16:28:49.6|Warn|AwesomeHD|Unable to connect to indexer

[v0.2.0.596] NzbDrone.Core.Indexers.Exceptions.IndexerException: An error occurred while processing feed, feed invalid
   at NzbDrone.Core.Indexers.AwesomeHD.AwesomeHDRssParser.ParseResponse(IndexerResponse indexerResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\AwesomeHD\AwesomeHDRssParser.cs:line 89
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 297
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 324

17-4-11 16:28:49.7|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to indexer. An error occurred while processing feed, feed invalid
17-4-11 16:28:49.7|Debug|Api|[POST] /api/indexer/test: 400.BadRequest (1375 ms)
17-4-11 16:28:51.8|Debug|Api|[GET] /api/health: 200.OK (0 ms)
17-4-11 16:28:51.8|Debug|Api|[GET] /api/health: 200.OK (0 ms)
17-4-11 16:28:53.0|Debug|Api|[GET] /api/diskspace: 200.OK (1216 ms)
17-4-11 16:28:53.2|Debug|Api|[GET] /api/diskspace: 200.OK (218 ms)
17-4-11 16:28:54.2|Debug|Api|[GET] /api/log/file: 200.OK (15 ms)
```

I also got a 6 hour ban from PTP for failed logins from the latest nightly in radarr as well. When that ban is up, I'll see if the latest develop release has the same issue of not being able to log in. Not exactly sure what happened on this release. On another note, my Jackett torznabs are working fine.

```
17-4-11 14:54:15.8|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (15 ms)
17-4-11 14:54:15.8|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (15 ms)
17-4-11 14:54:16.3|Warn|HttpClient|HTTP Error - Res: [POST] https://passthepopcorn.me/ajax.php?action=login: 403.Forbidden
{"Result":"Error","Message":"Your username, password or the captcha was incorrect.","Attempts":2}
17-4-11 14:54:16.3|Warn|PassThePopcorn|PassThePopcorn HTTP request failed: [403:Forbidden] [POST] at [https://passthepopcorn.me/ajax.php?action=login]
```

It worked within the last 24 hours and I haven't changed anything. Once I get unbanned in ~5 hours. I'll re-enter my information and see if I still get the same problem.

**Comment by Quiksmage** [comment]
I re-entered my password for ptp and was successfully able to test. I'm not sure why updating would have broken this. AND is still throwing the same error as above

**Comment by galli-leo** [comment]
Seems like AwesomeHD might have changed their feed? I will have to wait on onedrop since he's the only one with an account.

**Comment by onedr0p** [comment]
I will take a look later today, I noticed it failing on my end too.

**Comment by Quiksmage** [comment]
AHD appears to be working right now when testing.

**Comment by animosity22** [comment]
I'm on the latest develop and AHD was broken for ~1day and a half and came back this morning. I made no changes. I was getting feed invalids and that went away this morning.

No PTP issues in my logs over the last few days.

**Comment by quikstrike** [comment]
I ran into this issue as well, started about three days ago for me. I've been doing some testing and it seems that disabling the "Require Internal" toggle makes my request start working again, but once I re-enable it my tests start failing again. Here are some debug logs of me testing with Require Internal enabled, then with Require Internal disabled, and finally a third time this time with Require Internal re-enabled. I'm using version 0.2.0.596, in the hotio/radarr nightly docker image.

```
17-4-12 22:53:43.6|Debug|AwesomeHD|Downloading Feed https://awesome-hd.me/searchapi.php?action=latestmovies&passkey=(removed)&internal=true
17-4-12 22:53:44.6|Warn|AwesomeHD|Unable to connect to indexer

[v0.2.0.596] NzbDrone.Core.Indexers.Exceptions.IndexerException: An error occurred while processing feed, feed invalid
  at NzbDrone.Core.Indexers.AwesomeHD.AwesomeHDRssParser.ParseResponse (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x0020e] in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\AwesomeHD\AwesomeHDRssParser.cs:89 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchPage (NzbDrone.Core.Indexers.IndexerRequest request, IParseIndexerResponse parser) [0x00008] in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:297 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () [0x0000e] in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:325 

17-4-12 22:53:44.6|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to indexer. An error occurred while processing feed, feed invalid
17-4-12 22:53:44.6|Debug|Api|[POST] /api/indexer/test: 400.BadRequest (1051 ms)
17-4-12 22:53:47.0|Debug|AwesomeHD|Downloading Feed https://awesome-hd.me/searchapi.php?action=latestmovies&passkey=(removed)
17-4-12 22:53:48.2|Debug|Api|[POST] /api/indexer/test: 200.OK (1186 ms)
17-4-12 22:53:50.7|Debug|AwesomeHD|Downloading Feed https://awesome-hd.me/searchapi.php?action=latestmovies&passkey=(removed)&internal=true
17-4-12 22:53:51.3|Warn|AwesomeHD|Unable to connect to indexer

[v0.2.0.596] NzbDrone.Core.Indexers.Exceptions.IndexerException: An error occurred while processing feed, feed invalid
  at NzbDrone.Core.Indexers.AwesomeHD.AwesomeHDRssParser.ParseResponse (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x0020e] in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\AwesomeHD\AwesomeHDRssParser.cs:89 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchPage (NzbDrone.Core.Indexers.IndexerRequest request, IParseIndexerResponse parser) [0x00008] in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:297 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () [0x0000e] in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:325 

17-4-12 22:53:51.3|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to indexer. An error occurred while processing feed, feed invalid
17-4-12 22:53:51.3|Debug|Api|[POST] /api/indexer/test: 400.BadRequest (605 ms)
```

**Comment by quikstrike** [comment]
I forgot to mention that I also manually did a test request(via curl) , using the api endpoint listed in the logs and substituting my passkey, and I am able to successfully make the CURL request that is failing on Radarr. Let me know if I can help in any way.

**Comment by galli-leo** [comment]
@quickstrike Do you see a difference between the return of the curl request with internal required enabled and with it disabled?

**Comment by quikstrike** [comment]
@galli-leo Yes, but only the movies in the search results are different. The structure of the payloads are the same. I can provide the XML payloads if you would like.

**Comment by galli-leo** [comment]
@quikstrike No I think it should be fine. Was just curious if that maybe causes the issue.

**Comment by jrsdead** [comment]
AHD rss had a stray & which was causing the issue. Should all be good now

**Comment by galli-leo** [comment]
@Quiksmage @quikstrike @onedr0p Can you confirm this is fixed?

**Comment by Quiksmage** [comment]
Hi,

I can confirm that it has been working since my original message 3 days ago.

I went ahead and did a test on my 2 AHD Indexers. 

One requiring internals and one not.

They both successfully tested.

I did manual searches of a few movies and all of them returned the expected results from AHD.

For me, this is good to be closed.

**Comment by Quiksmage** [comment]
It looks like this issue has returned for both of my trackers after automatically upgrading to the latest develop, 0.2.0.654

```
17-4-20 13:15:02.2|Debug|AwesomeHD|Downloading Feed https://awesome-hd.me/searchapi.php?action=latestmovies&passkey=(removed)
17-4-20 13:15:03.5|Warn|AwesomeHD|Unable to connect to indexer

[v0.2.0.654] NzbDrone.Core.Indexers.Exceptions.IndexerException: An error occurred while processing feed, feed invalid
   at NzbDrone.Core.Indexers.AwesomeHD.AwesomeHDRssParser.ParseResponse(IndexerResponse indexerResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\AwesomeHD\AwesomeHDRssParser.cs:line 96
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 297
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 324

17-4-20 13:15:03.6|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to indexer. An error occurred while processing feed, feed invalid
17-4-20 13:15:03.6|Debug|Api|[POST] /api/indexer/test: 400.BadRequest (1373 ms)
```

```
17-4-20 13:14:32.3|Warn|HttpClient|HTTP Error - Res: [POST] https://passthepopcorn.me/ajax.php?action=login: 403.Forbidden
{"Result":"Error","Message":"Your username, password or the captcha was incorrect.","Attempts":4}
17-4-20 13:14:32.3|Warn|PassThePopcorn|Unable to connect to indexer

[v0.2.0.654] NzbDrone.Common.Http.HttpException: HTTP request failed: [403:Forbidden] [POST] at [https://passthepopcorn.me/ajax.php?action=login]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 99
   at NzbDrone.Core.Indexers.PassThePopcorn.PassThePopcornRequestGenerator.Authenticate() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\PassThePopcorn\PassThePopcornRequestGenerator.cs:line 77
   at NzbDrone.Core.Indexers.PassThePopcorn.PassThePopcornRequestGenerator.<GetRequest>d__18.MoveNext() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\PassThePopcorn\PassThePopcornRequestGenerator.cs:line 38
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 324
{"Result":"Error","Message":"Your username, password or the captcha was incorrect.","Attempts":4}
```

It is likely that this problem, at least with PTP, was present on nightly, but not develop, so when I reverted to develop, the issue went away. Since the develop has merged since then, the PTP issue is back.

My login information is correct. I tried re-entering my information and it is still giving me login errors.

The errors started 1 day, 20 hours ago, which is when it automatically upgraded to the latest version.

http://i.imgur.com/FhzEGTU.png

I am currently not banned from logging in, so I am able to test anything you think might help.

Thanks!

**Comment by galli-leo** [comment]
Hmm AHD makes sense since the api returns some non xml stuff.

@jrsdead Returned before xml: ```
Notice: Memcache::pconnect(): Server unix:///var/run/memcached.sock (tcp 0) failed with: Connection refused (111) in /var/www/ahd4/classes/class_cache.php on line 39

Warning: Memcache::pconnect(): Can't connect to unix:///var/run/memcached.sock:0, Connection refused (111) in /var/www/ahd4/classes/class_cache.php on line 39
``` 
I would suggest disable PHP Errors in the API scripts? You can always catch them and return an error in xml format.

**Comment by galli-leo** [comment]
@Quiksmage Can you try testing the PTP indexer and also restarting Radarr?

**Comment by jrsdead** [comment]
@galli-leo That should be resolved now

**Comment by galli-leo** [comment]
@jrsdead Yup xml returned is now correct. Thanks a ton:)

@Quiksmage Can you try AHD again?

**Comment by Quiksmage** [comment]
AHD is working now. 

Testing PTP failed. Restarting Radarr now.
PTP is still not working after restart. I've erased the credentials and re-entered them and it's still giving me the below error.


```

17-4-20 18:36:02.9|Warn|HttpClient|HTTP Error - Res: [POST] https://passthepopcorn.me/ajax.php?action=login: 403.Forbidden
{"Result":"Error","Message":"Your username, password or the captcha was incorrect.","Attempts":3}
17-4-20 18:36:02.9|Warn|PassThePopcorn|Unable to connect to indexer

[v0.2.0.654] NzbDrone.Common.Http.HttpException: HTTP request failed: [403:Forbidden] [POST] at [https://passthepopcorn.me/ajax.php?action=login]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 99
   at NzbDrone.Core.Indexers.PassThePopcorn.PassThePopcornRequestGenerator.Authenticate() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\PassThePopcorn\PassThePopcornRequestGenerator.cs:line 77
   at NzbDrone.Core.Indexers.PassThePopcorn.PassThePopcornRequestGenerator.<GetRequest>d__18.MoveNext() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\PassThePopcorn\PassThePopcornRequestGenerator.cs:line 38
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 324
{"Result":"Error","Message":"Your username, password or the captcha was incorrect.","Attempts":3}

17-4-20 18:36:03.0|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to indexer, check the log for more details
17-4-20 18:36:03.0|Debug|Api|[POST] /api/indexer/test: 400.BadRequest (546 ms)
17-4-20 18:36:11.4|Debug|Api|[PUT] /api/indexer/1: 202.Accepted (46 ms)
17-4-20 18:36:11.6|Debug|Api|[GET] /api/health: 200.OK (0 ms)
17-4-20 18:36:13.3|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (15 ms)
17-4-20 18:36:13.3|Debug|Api|[GET] /api/system/task?sort_by=name&order=asc: 200.OK (0 ms)
17-4-20 18:36:13.3|Debug|Api|[GET] /api/system/task?sort_by=name&order=asc: 200.OK (15 ms)
17-4-20 18:36:13.3|Debug|Api|[GET] /api/system/task?sort_by=name&order=asc: 200.OK (15 ms)
17-4-20 18:36:13.4|Debug|Api|[GET] /api/system/task?sort_by=name&order=asc: 200.OK (31 ms)
17-4-20 18:36:15.8|Warn|HttpClient|HTTP Error - Res: [POST] https://passthepopcorn.me/ajax.php?action=login: 403.Forbidden
{"Result":"Error","Message":"Your username, password or the captcha was incorrect.","Attempts":2}
17-4-20 18:36:15.8|Warn|PassThePopcorn|Unable to connect to indexer

[v0.2.0.654] NzbDrone.Common.Http.HttpException: HTTP request failed: [403:Forbidden] [POST] at [https://passthepopcorn.me/ajax.php?action=login]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 99
   at NzbDrone.Core.Indexers.PassThePopcorn.PassThePopcornRequestGenerator.Authenticate() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\PassThePopcorn\PassThePopcornRequestGenerator.cs:line 77
   at NzbDrone.Core.Indexers.PassThePopcorn.PassThePopcornRequestGenerator.<GetRequest>d__18.MoveNext() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\PassThePopcorn\PassThePopcornRequestGenerator.cs:line 38
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 324
{"Result":"Error","Message":"Your username, password or the captcha was incorrect.","Attempts":2}

17-4-20 18:36:15.9|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to indexer, check the log for more details
```

I also tried adding a brand new PTP indexer into radarr thinking that maybe the old one had problems for one reason or another. It will not allow me to add another PTP indexer as it drops the following.

```
17-4-20 18:38:40.9|Warn|HttpClient|HTTP Error - Res: [POST] https://passthepopcorn.me/ajax.php?action=login: 403.Forbidden
{"Result":"Error","Message":"Your username, password or the captcha was incorrect.","Attempts":4}
17-4-20 18:38:40.9|Warn|PassThePopcorn|Unable to connect to indexer

[v0.2.0.654] NzbDrone.Common.Http.HttpException: HTTP request failed: [403:Forbidden] [POST] at [https://passthepopcorn.me/ajax.php?action=login]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 99
   at NzbDrone.Core.Indexers.PassThePopcorn.PassThePopcornRequestGenerator.Authenticate() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\PassThePopcorn\PassThePopcornRequestGenerator.cs:line 77
   at NzbDrone.Core.Indexers.PassThePopcorn.PassThePopcornRequestGenerator.<GetRequest>d__18.MoveNext() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\PassThePopcorn\PassThePopcornRequestGenerator.cs:line 38
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 324
{"Result":"Error","Message":"Your username, password or the captcha was incorrect.","Attempts":4}

17-4-20 18:38:40.9|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to indexer, check the log for more details
17-4-20 18:38:41.0|Debug|Api|[POST] /api/indexer/test: 400.BadRequest (406 ms)
17-4-20 18:38:43.4|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (0 ms)
17-4-20 18:38:43.5|Debug|Api|[GET] /api/system/task?sort_by=name&order=asc: 200.OK (0 ms)
17-4-20 18:38:43.5|Debug|Api|[GET] /api/system/task?sort_by=name&order=asc: 200.OK (15 ms)
17-4-20 18:38:43.5|Debug|Api|[GET] /api/system/task?sort_by=name&order=asc: 200.OK (15 ms)
17-4-20 18:38:43.5|Debug|Api|[GET] /api/system/task?sort_by=name&order=asc: 200.OK (31 ms)
17-4-20 18:38:44.4|Warn|HttpClient|HTTP Error - Res: [POST] https://passthepopcorn.me/ajax.php?action=login: 403.Forbidden
{"Result":"Error","Message":"Your username, password or the captcha was incorrect.","Attempts":3}
17-4-20 18:38:44.4|Warn|PassThePopcorn|Unable to connect to indexer

[v0.2.0.654] NzbDrone.Common.Http.HttpException: HTTP request failed: [403:Forbidden] [POST] at [https://passthepopcorn.me/ajax.php?action=login]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 99
   at NzbDrone.Core.Indexers.PassThePopcorn.PassThePopcornRequestGenerator.Authenticate() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\PassThePopcorn\PassThePopcornRequestGenerator.cs:line 77
   at NzbDrone.Core.Indexers.PassThePopcorn.PassThePopcornRequestGenerator.<GetRequest>d__18.MoveNext() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\PassThePopcorn\PassThePopcornRequestGenerator.cs:line 38
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 324
{"Result":"Error","Message":"Your username, password or the captcha was incorrect.","Attempts":3}

17-4-20 18:38:44.4|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to indexer, check the log for more details
17-4-20 18:38:44.4|Debug|Api|[POST] /api/indexer: 400.BadRequest (640 ms)
17-4-20 18:38:46.7|Warn|HttpClient|HTTP Error - Res: [POST] https://passthepopcorn.me/ajax.php?action=login: 403.Forbidden
{"Result":"Error","Message":"Your username, password or the captcha was incorrect.","Attempts":2}
17-4-20 18:38:46.7|Warn|PassThePopcorn|Unable to connect to indexer

[v0.2.0.654] NzbDrone.Common.Http.HttpException: HTTP request failed: [403:Forbidden] [POST] at [https://passthepopcorn.me/ajax.php?action=login]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 99
   at NzbDrone.Core.Indexers.PassThePopcorn.PassThePopcornRequestGenerator.Authenticate() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\PassThePopcorn\PassThePopcornRequestGenerator.cs:line 77
   at NzbDrone.Core.Indexers.PassThePopcorn.PassThePopcornRequestGenerator.<GetRequest>d__18.MoveNext() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\PassThePopcorn\PassThePopcornRequestGenerator.cs:line 38
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 324
{"Result":"Error","Message":"Your username, password or the captcha was incorrect.","Attempts":2}

17-4-20 18:38:46.7|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to indexer, check the log for more details
17-4-20 18:38:46.7|Debug|Api|[POST] /api/indexer: 400.BadRequest (374 ms)
17-4-20 18:38:54.4|Warn|HttpClient|HTTP Error - Res: [POST] https://passthepopcorn.me/ajax.php?action=login: 403.Forbidden
{"Result":"Error","Message":"Your username, password or the captcha was incorrect.","Attempts":1}
17-4-20 18:38:54.4|Warn|PassThePopcorn|Unable to connect to indexer

[v0.2.0.654] NzbDrone.Common.Http.HttpException: HTTP request failed: [403:Forbidden] [POST] at [https://passthepopcorn.me/ajax.php?action=login]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 99
   at NzbDrone.Core.Indexers.PassThePopcorn.PassThePopcornRequestGenerator.Authenticate() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\PassThePopcorn\PassThePopcornRequestGenerator.cs:line 77
   at NzbDrone.Core.Indexers.PassThePopcorn.PassThePopcornRequestGenerator.<GetRequest>d__18.MoveNext() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\PassThePopcorn\PassThePopcornRequestGenerator.cs:line 38
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 324
{"Result":"Error","Message":"Your username, password or the captcha was incorrect.","Attempts":1}

17-4-20 18:38:54.4|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to indexer, check the log for more details
```
I'm resetting my lockout attempts by manually logging out and back in on my web browser. If you have any ideas, let me know.

**Comment by Quiksmage** [comment]
I'm surprised no one else has commented saying that they aren't getting PTP working. Is it only me? If so, I've got to wonder what's going on. I've swapped over to nightly to see if any changes there could help, but no change. Is it possible to revert to the develop build 0.2.0.596 - Apr 10 2017.
There is no install option in the GUI for older builds.
I'd like to see if PTP becomes usable again as I find it weird no one else has complained.

**Comment by Quiksmage** [comment]
I reinstalled the old version where it was previously still working and it is still not working. Now this is confusing to me even more.

When I first created this issue, it happened on nightly, I reverted to this develop and after my ban had passed, it started working again.

Now, on the current develop it doesn't work and reverting back to the old one doesn't help.

I've now done a fresh install of radarr on a new VM and it still fails giving me this same output

```
17-4-22 21:19:47.9|Warn|HttpClient|HTTP Error - Res: [POST] https://passthepopcorn.me/ajax.php?action=login: 403.Forbidden
{"Result":"Error","Message":"Your username, password or the captcha was incorrect.","Attempts":4}
17-4-22 21:19:47.9|Warn|PassThePopcorn|Unable to connect to indexer

[v0.2.0.654] NzbDrone.Common.Http.HttpException: HTTP request failed: [403:Forbidden] [POST] at [https://passthepopcorn.me/ajax.php?action=login]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 99
   at NzbDrone.Core.Indexers.PassThePopcorn.PassThePopcornRequestGenerator.Authenticate() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\PassThePopcorn\PassThePopcornRequestGenerator.cs:line 77
   at NzbDrone.Core.Indexers.PassThePopcorn.PassThePopcornRequestGenerator.<GetRequest>d__18.MoveNext() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\PassThePopcorn\PassThePopcornRequestGenerator.cs:line 38
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 324
{"Result":"Error","Message":"Your username, password or the captcha was incorrect.","Attempts":4}

17-4-22 21:19:48.0|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to indexer, check the log for more details

```

**Comment by Quiksmage** [comment]
Okay.... so I think I've found out what's going on... and it perplexes me even more.

So, I tried to login to the website using my credentials from within the VM that radarr has been installed on. It fails with the correct information the same way radarr does.

I'll have to troubleshoot into this further. I'll keep this updated.

**Comment by Quiksmage** [comment]
Okay, I figured it out,

The password I was using was incorrect as the message said in my inbox.

However, PTP is allowing me to login with incorrect credentials on my main computer, the fuck...? 

Evidently, even when you click log out, it still caches your information and does NOT require a correct password to be typed in on the login page.

I literally just logged in with 1231251251251245.

I'm sorry for this whole thing and I'll be closing this. I've never seen a website do that when you're logged out, or evidently I'm not really logged out even though it shows it.

**Comment by Quiksmage** [comment]
For completions sake. I  reported this over to the PTP IRC. They worked with me through it and it appears that my password manager is filling a hidden form between when I input an incorrect password, and when I complete the captcha. After I select the correct captcha, there's a hidden form where it's inputting my correct login data. Hopefully this will help someone in the future.
