### ISSUE TITLE
UI infinite loading - Nightly

### ISSUE THREAD

**Issue by tiphae** [Radarr/Radarr#1639]
Latest nightly version displays a Radarr background and the loading circles moving left to right, but never loads anything else. Tried clearing cache/cookies, several browsers, incognito/private browsing, setting authentication to none, system restart, force stop/start of Radarr.

Version: Last nightly as of 6/6/17 on Qnap NAS

Logs:

17-6-6 15:51:52.5|Info|DownloadDecisionMaker|No results found
17-6-6 15:51:52.5|Info|RssSyncService|RSS Sync Completed. Reports found: 0, Reports grabbed: 0
17-6-6 16:14:30.1|Info|PreDBService|Starting PreDB Sync
17-6-6 16:15:00.5|Info|NetImportSearchService|No lists are enabled for auto-import.
17-6-6 16:26:05.2|Info|InstallUpdateService|Deleting old update files
17-6-6 16:26:05.3|Info|InstallUpdateService|Downloading update 0.2.0.743
17-6-6 16:26:08.0|Info|InstallUpdateService|Verifying update package
17-6-6 16:26:08.3|Info|InstallUpdateService|Update package verified successfully
17-6-6 16:26:08.3|Info|InstallUpdateService|Extracting Update package
17-6-6 16:26:09.2|Info|InstallUpdateService|Update package extracted successfully
17-6-6 16:26:09.2|Info|BackupService|Starting Backup
17-6-6 16:26:10.9|Info|InstallUpdateService|Preparing client
17-6-6 16:26:10.9|Info|InstallUpdateService|Starting update client /tmp/radarr_update/Radarr.Update.exe
17-6-6 16:26:10.9|Info|InstallUpdateService|Radarr will restart shortly.
17-6-6 16:26:11.3|Info|InstallUpdateService|Updater Arguments: 27277 /tmp/radarr_update /share/CACHEDEV1_DATA/.qpkg/Radarr/Radarr/Radarr.exe /nobrowser
17-6-6 16:26:32.9|Info|Bootstrap|Starting Radarr - /share/CACHEDEV1_DATA/.qpkg/Radarr/Radarr/Radarr.exe - Version 0.2.0.743
17-6-6 16:26:35.7|Info|MigrationLogger|*** Migrating data source=/share/CACHEDEV1_DATA/.qpkg/Radarr/Home/.config/Radarr/nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-6-6 16:26:36.0|Info|MigrationLogger|*** Migrating data source=/share/CACHEDEV1_DATA/.qpkg/Radarr/Home/.config/Radarr/logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-6-6 16:26:36.0|Info|Router|Application mode: Interactive
17-6-6 16:26:36.0|Info|OwinHostController|Listening on the following URLs:
17-6-6 16:26:36.0|Info|OwinHostController|  http://*:7878/
17-6-6 16:26:36.3|Info|NancyBootstrapper|Starting NzbDrone API
17-6-6 16:52:16.5|Info|RssSyncService|Starting RSS Sync
17-6-6 16:52:16.6|Error|FetchAndParseRssService|Error during RSS Sync

[v0.2.0.743] System.Net.WebException: Error: ConnectFailure (Connection refused) ---> System.Net.Sockets.SocketException: Connection refused
  at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000cb] in /SRC/mono-4.6.2/mcs/class/System/System.Net.Sockets/Socket.cs:1313 
  at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0019b] in /SRC/mono-4.6.2/mcs/class/System/System.Net/WebConnection.cs:195 
   --- End of inner exception stack trace ---
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00065] in /SRC/mono-4.6.2/mcs/class/System/System.Net/HttpWebRequest.cs:1025 
  at System.Net.HttpWebRequest.GetResponse () [0x0000e] in /SRC/mono-4.6.2/mcs/class/System/System.Net/HttpWebRequest.cs:1037 
  at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookies) [0x000fe] in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:61 

17-6-6 16:52:16.6|Info|DownloadDecisionMaker|No results found
17-6-6 16:52:16.6|Info|RssSyncService|RSS Sync Completed. Reports found: 0, Reports grabbed: 0
17-6-6 17:14:54.1|Info|PreDBService|Starting PreDB Sync
17-6-6 17:15:24.5|Info|NetImportSearchService|No lists are enabled for auto-import.
17-6-6 17:31:30.8|Info|HousekeepingService|Running housecleaning tasks
17-6-6 17:31:31.3|Info|Database|Vacuuming Log database
17-6-6 17:31:31.5|Info|Database|Log database compressed
17-6-6 17:31:43.4|Info|Database|Vacuuming Main database
17-6-6 17:31:43.5|Info|Database|Main database compressed
17-6-6 17:52:38.1|Info|RssSyncService|Starting RSS Sync
17-6-6 17:52:38.1|Error|FetchAndParseRssService|Error during RSS Sync

[v0.2.0.743] System.Net.WebException: Error: ConnectFailure (Connection refused) ---> System.Net.Sockets.SocketException: Connection refused
  at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000cb] in /SRC/mono-4.6.2/mcs/class/System/System.Net.Sockets/Socket.cs:1313 
  at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0019b] in /SRC/mono-4.6.2/mcs/class/System/System.Net/WebConnection.cs:195 
   --- End of inner exception stack trace ---
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00065] in /SRC/mono-4.6.2/mcs/class/System/System.Net/HttpWebRequest.cs:1025 
  at System.Net.HttpWebRequest.GetResponse () [0x0000e] in /SRC/mono-4.6.2/mcs/class/System/System.Net/HttpWebRequest.cs:1037 
  at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookies) [0x000fe] in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:61 

17-6-6 17:52:38.1|Info|DownloadDecisionMaker|No results found
17-6-6 17:52:38.1|Info|RssSyncService|RSS Sync Completed. Reports found: 0, Reports grabbed: 0
17-6-6 18:15:16.1|Info|PreDBService|Starting PreDB Sync
17-6-6 18:15:46.5|Info|NetImportSearchService|No lists are enabled for auto-import.
17-6-6 18:53:02.2|Info|RssSyncService|Starting RSS Sync
17-6-6 18:53:02.2|Error|FetchAndParseRssService|Error during RSS Sync

[v0.2.0.743] System.Net.WebException: Error: ConnectFailure (Connection refused) ---> System.Net.Sockets.SocketException: Connection refused
  at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000cb] in /SRC/mono-4.6.2/mcs/class/System/System.Net.Sockets/Socket.cs:1313 
  at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0019b] in /SRC/mono-4.6.2/mcs/class/System/System.Net/WebConnection.cs:195 
   --- End of inner exception stack trace ---
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00065] in /SRC/mono-4.6.2/mcs/class/System/System.Net/HttpWebRequest.cs:1025 
  at System.Net.HttpWebRequest.GetResponse () [0x0000e] in /SRC/mono-4.6.2/mcs/class/System/System.Net/HttpWebRequest.cs:1037 
  at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookies) [0x000fe] in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:61 

17-6-6 18:53:02.2|Info|DownloadDecisionMaker|No results found
17-6-6 18:53:02.2|Info|RssSyncService|RSS Sync Completed. Reports found: 0, Reports grabbed: 0
17-6-6 18:58:54.6|Info|Bootstrap|Starting Radarr - /share/CACHEDEV1_DATA/.qpkg/Radarr/Radarr/Radarr.exe - Version 0.2.0.743
17-6-6 18:58:57.4|Info|MigrationLogger|*** Migrating data source=/share/CACHEDEV1_DATA/.qpkg/Radarr/Home/.config/Radarr/nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-6-6 18:58:57.8|Info|MigrationLogger|*** Migrating data source=/share/CACHEDEV1_DATA/.qpkg/Radarr/Home/.config/Radarr/logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-6-6 18:58:57.8|Info|Router|Application mode: Interactive
17-6-6 18:58:57.9|Info|OwinHostController|Listening on the following URLs:
17-6-6 18:58:57.9|Info|OwinHostController|  http://*:7878/
17-6-6 18:58:58.1|Info|NancyBootstrapper|Starting NzbDrone API
17-6-6 19:04:07.7|Info|Bootstrap|Starting Radarr - /share/CACHEDEV1_DATA/.qpkg/Radarr/Radarr/Radarr.exe - Version 0.2.0.743
17-6-6 19:04:10.7|Info|MigrationLogger|*** Migrating data source=/share/CACHEDEV1_DATA/.qpkg/Radarr/Home/.config/Radarr/nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-6-6 19:04:11.0|Info|MigrationLogger|*** Migrating data source=/share/CACHEDEV1_DATA/.qpkg/Radarr/Home/.config/Radarr/logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-6-6 19:04:11.0|Info|Router|Application mode: Interactive
17-6-6 19:04:11.0|Info|OwinHostController|Listening on the following URLs:
17-6-6 19:04:11.0|Info|OwinHostController|  http://*:7878/
17-6-6 19:04:11.3|Info|NancyBootstrapper|Starting NzbDrone API
17-6-6 19:07:09.9|Fatal|NzbDroneErrorPipeline|Request Failed

[v0.2.0.743] System.InvalidOperationException: Sequence contains more than one matching element
  at System.Linq.Enumerable.SingleOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x0009d] in <5f01f5aacbb346938d6f9b4e69d4383a>:0 
  at NzbDrone.Api.Frontend.StaticResourceModule.Index () [0x000a5] in <82d5001ba0814b919525d99a97b074ce>:0 
  at NzbDrone.Api.Frontend.StaticResourceModule.<.ctor>b__3_0 (System.Object x) [0x00000] in <82d5001ba0814b919525d99a97b074ce>:0 
  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0 

17-6-6 19:07:33.6|Fatal|NzbDroneErrorPipeline|Request Failed

[v0.2.0.743] System.InvalidOperationException: Sequence contains more than one matching element
  at System.Linq.Enumerable.SingleOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x0009d] in <5f01f5aacbb346938d6f9b4e69d4383a>:0 
  at NzbDrone.Api.Frontend.StaticResourceModule.Index () [0x000a5] in <82d5001ba0814b919525d99a97b074ce>:0 
  at NzbDrone.Api.Frontend.StaticResourceModule.<.ctor>b__3_0 (System.Object x) [0x00000] in <82d5001ba0814b919525d99a97b074ce>:0 
  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0 

17-6-6 19:15:16.9|Info|PreDBService|Starting PreDB Sync
17-6-6 19:15:47.1|Info|NetImportSearchService|No lists are enabled for auto-import.
17-6-6 19:28:33.1|Info|Bootstrap|Starting Radarr - /share/CACHEDEV1_DATA/.qpkg/Radarr/Radarr/Radarr.exe - Version 0.2.0.743
17-6-6 19:28:37.1|Info|MigrationLogger|*** Migrating data source=/share/CACHEDEV1_DATA/.qpkg/Radarr/Home/.config/Radarr/nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-6-6 19:28:37.7|Info|MigrationLogger|*** Migrating data source=/share/CACHEDEV1_DATA/.qpkg/Radarr/Home/.config/Radarr/logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-6-6 19:28:37.8|Info|Router|Application mode: Interactive
17-6-6 19:28:37.8|Info|OwinHostController|Listening on the following URLs:
17-6-6 19:28:37.8|Info|OwinHostController|  http://*:7878/
17-6-6 19:28:38.5|Info|NancyBootstrapper|Starting NzbDrone API
17-6-6 19:53:21.3|Info|RssSyncService|Starting RSS Sync
17-6-6 19:53:46.8|Info|DownloadDecisionMaker|Processing 200 releases
17-6-6 19:54:06.5|Info|RssSyncService|RSS Sync Completed. Reports found: 200, Reports grabbed: 0

**Comment by tusharbhutt** [comment]
Same result here... hours and hours at 25% CPU usage

**Comment by dr0ther** [comment]
I have the same issue. I even rolled back from .696 to .692. The only way to get it to load is to completely uninstall it, and reinstall it. The UI is only usable for about 30 seconds, and then once again unusable.

**Comment by dr0ther** [comment]
Wow I guess it was automatically updating to Version 0.2.0.743. I changed updates to master (from nightly) in the config.xml and re-installed again. No more infinite loading.

**Comment by gold007eye** [comment]
Same issue here.  Thought it was something to do with my fresh install, but then realized rolling back to previous nightly worked fine; so definitely something wrong with .743 nightly breaking the UI.

**Comment by fevkalbeser** [comment]
Same here. Any suggestions?

**Comment by chuckkay** [comment]
same here...
here's a temp fix... no need to uninstall, just roll back to previous version.

shutdown radarr
find config.xml in C:\ProgramData\Radarr
edit xml  
change <Branch>nightly </Branch> to <Branch>Develop</Branch>
(otherwise radarr will just download the same bad build again)
find backup build in C:\Users\[username]\AppData\Local\Temp\radarr_update\radarr_backup
copy all 78+/- files and the UI directory and paste into your radarr install directory..

start radarr....

when a new fixed nightly build is released,  go to general settings and change updates back to nightly

**Comment by galli-leo** [comment]
Fixed on latest nightly. Sorry about that, forgot to include a js file on the commit late last night :/

**Comment by tusharbhutt** [comment]
How do we download the latest nightly to correct this?  I tried the method from @chuckkay to deleted all the files and then copy from the backup but I still have the infinite loop.
