### ISSUE TITLE
Import error:  "C:\Windows\System32\5\" ??

### ISSUE THREAD

**Issue by seanvree** [Radarr/Radarr#1697]
**Description:**

Started to get this weird error when importing SOME movies.  I can't pin it down to why it does this with SOME movies and not others,  Happens with both torrents and NZBs.  

I can take the same file and drop it into the drone factor, same error. 

i can also try to manually import it from the drone factory, same error. 

**Radarr Version:**
Windows 10E
Version 0.2.0.696 (Service)
AppData directory: C:\ProgramData\Radarr
Startup directory C:\ProgramData\Radarr\bin

**Logs:**

```
couldn't import movie C:\Media\PlexDownloads\Drone\mclaren.2016.1080p.bluray.x264-ghouls.mkv: Root folder 'C:\Windows\System32\5\' was not found
```

```
System.IO.DirectoryNotFoundException: Root folder 'C:\Windows\System32\5\' was not found.
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.EnsureMovieFolder(MovieFile movieFile, Movie movie, String filePath) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 172
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.MoveMovieFile(MovieFile movieFile, LocalMovie localMovie) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 78
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile movieFile, LocalMovie localMovie, Boolean copyOnly) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 73
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedMovie.cs:line 103
```

**Comment by galli-leo** [comment]
Did you add those movies via a list?

**Comment by seanvree** [comment]
@galli-leo 

Yes, via IMDB.

**Comment by galli-leo** [comment]
@seanvree See https://github.com/Radarr/Radarr/wiki/Common-Problems#root-path-for-movies-imported-from-lists-becomes-cwindowssystem32 for why this is happening. I fixed the UI glitch that enabled it to happen, so for now you should be able to correct root path for all existing movies via movie editor and correct the path of the list.

**Comment by seanvree** [comment]
@galli-leo  - This doesn't work for me.

Are you saying that the root path will display c:\windows\system32?  Because in my webui, the paths are displaying correctly, but it still won't import.
