### ISSUE TITLE
CouchPotatoImport fails 'Object reference not set to an instance of an object'

### ISSUE THREAD

**Issue by airmarshall** [Radarr/Radarr#1792]
**Description:**

When running a list connection test to CP following error occurs and list does not import.

**Radarr Version:**

Radarr Ver. 0.2.0.778
develop

**Logs:**

```
17-7-12 22:48:41.1|Debug|CouchPotatoImport|Downloading List http://192.168.50.50:8083/api/5c9954b09da1447e965377f5ceb9c69a/movie.list/?status=active
17-7-12 22:48:41.7|Warn|CouchPotatoImport|Unable to connect to list

[v0.2.0.778] System.NullReferenceException: Object reference not set to an instance of an object
  at NzbDrone.Core.NetImport.CouchPotato.CouchPotatoParser.ParseResponse (NzbDrone.Core.NetImport.NetImportResponse importResponse) [0x0004b] in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\CouchPotato\CouchPotatoParser.cs:46 
  at NzbDrone.Core.NetImport.HttpNetImportBase`1[TSettings].FetchPage (NzbDrone.Core.NetImport.NetImportRequest request, NzbDrone.Core.NetImport.IParseNetImportResponse parser) [0x00008] in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:110 
  at NzbDrone.Core.NetImport.HttpNetImportBase`1[TSettings].TestConnection () [0x0000e] in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:145 

17-7-12 22:48:41.8|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to list, check the log for more details
17-7-12 22:48:41.8|Debug|Api|[POST] /api/netimport/test: 400.BadRequest (668 ms)
17-7-12 22:48:47.6|Debug|Api|[GET] /api/log/file: 200.OK (6 ms)
17-7-12 22:48:47.7|Debug|Api|[GET] /api/log/file/radarr.trace.txt: 200.OK (33 ms)
```

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by hotio** [comment]
Make sure radarr has permission to access couchpotato

**Comment by screwyluie** [comment]
I have the same issue with the same errors.

**Comment by galli-leo** [comment]
@airmarshall @screwyluie Can you guys open the url Radarr downloads (http://192.168.50.50:8083/api/5c9954b09da1447e965377f5ceb9c69a/movie.list/?status=active as an example), copy the contents and post it here?

**Comment by screwyluie** [comment]
[radarr_cp_url.txt](https://github.com/Radarr/Radarr/files/1190143/radarr_cp_url.txt)

there ya go

**Comment by airmarshall** [comment]
sure thang!
[cp_apicall.txt](https://github.com/Radarr/Radarr/files/1190324/cp_apicall.txt)

**Comment by airmarshall** [comment]
@galli-leo any progress on this bug? Or anything more we can do to help? Thanks

**Comment by galli-leo** [comment]
Sorry have been kinda busy in the last few days. Should be fixed now though.

**Comment by airmarshall** [comment]
Sorry for delay, had to wait for author to resync the docker I use. Unfortunately issue still seems to be present:

`17-8-26 09:43:47.5|Debug|CouchPotatoImport|Downloading List http://192.168.50.50:8083/api/5c9954b09da1447e965377f5ceb9c69a/movie.list/?status=active
17-8-26 09:43:47.7|Warn|CouchPotatoImport|Unable to connect to list

[v0.2.0.778] System.NullReferenceException: Object reference not set to an instance of an object
  at NzbDrone.Core.NetImport.CouchPotato.CouchPotatoParser.ParseResponse (NzbDrone.Core.NetImport.NetImportResponse importResponse) [0x0004b] in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\CouchPotato\CouchPotatoParser.cs:46 
  at NzbDrone.Core.NetImport.HttpNetImportBase`1[TSettings].FetchPage (NzbDrone.Core.NetImport.NetImportRequest request, NzbDrone.Core.NetImport.IParseNetImportResponse parser) [0x00008] in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:110 
  at NzbDrone.Core.NetImport.HttpNetImportBase`1[TSettings].TestConnection () [0x0000e] in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:145 

17-8-26 09:43:47.8|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to list, check the log for more details`

Anywhere I can look to make sure your change made it through the latest docker build?

**Comment by hotio** [comment]
Which docker?

**Comment by galli-leo** [comment]
Yeah what version does the web ui show?

**Comment by airmarshall** [comment]
> Which docker?
This one - https://hub.docker.com/r/linuxserver/radarr/

> Yeah what version does the web ui show?
```
Radarr Ver. 0.2.0.778
develop
```

**Comment by galli-leo** [comment]
@airmarshall Yeah the fix isn't on that version. I should have a develop release (with the fix) hopefully ready in the next few days.

**Comment by airmarshall** [comment]
Yep - all fixed. Thanks for your help and efforts.

**Comment by screwyluie** [comment]
updated radarr and upon launch it loaded up my CP database so that's an improvement yay! There seems to be some issues still though and I don't know if you would prefer a new bug tracker for them.

First some of the movies imported queued two identical downloads. it was maybe 4 out of 60+ seems random. Easy fix but I wonder if I'm doing something wrong or if it's a one off that won't cause any future issues.

Second, it didn't import all of my CP wanted list some movies are missing. The only error I see in the log is this:

> Error occurred while executing task NetImportSync: constraint failed
> UNIQUE constraint failed: Movies.TitleSlug

> System.Data.SQLite.SQLiteException (0x80004005): constraint failed
> UNIQUE constraint failed: Movies.TitleSlug
>    at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
>    at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
>    at System.Data.SQLite.SQLiteDataReader.NextResult()
>    at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
>    at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
>    at System.Data.SQLite.SQLiteCommand.ExecuteScalar(CommandBehavior behavior)
>    at System.Data.SQLite.SQLiteCommand.ExecuteScalar()
>    at Marr.Data.QGen.InsertQueryBuilder\`1.Execute() in C:\projects\radarr-usby1\src\Marr.Data\QGen\InsertQueryBuilder.cs:line 138
>    at Marr.Data.DataMapper.Insert[T](T entity) in C:\projects\radarr-usby1\src\Marr.Data\DataMapper.cs:line 728
>    at NzbDrone.Core.Datastore.BasicRepository\`1.Insert(TModel model) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 109
>    at NzbDrone.Core.Tv.MovieService.AddMovie(Movie newMovie) in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieService.cs:line 181
>    at NzbDrone.Core.NetImport.NetImportSearchService.Execute(NetImportSyncCommand message) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\NetImportSearchService.cs:line 136
>    at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 91
>    at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
>    at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
>    at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
>    at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 41

**Comment by galli-leo** [comment]
Seems like they might be the same movie? Have you tried importing a second time? Also multiple downloads can happen if Radarr cannot properly communicate with your dl client, so it tries to add a download again.

**Comment by screwyluie** [comment]
I have it setup to ping CP every ten minutes so I can test things between them. Every 10mins I get that same error and I'm missing movies from the wanted list in CP.

**Comment by galli-leo** [comment]
Interesting can you enable trace logging and post what comes before the above?

**Comment by screwyluie** [comment]
https://pastebin.com/3vX6inHm

the error is at the end, I searched for 'netimportsync' and grabbed everything above it until there were no more results.

**Comment by galli-leo** [comment]
What happens when you go to radarr-url/movies/armed-response-450932 in your browser?

**Comment by screwyluie** [comment]
I get the normal movie page showing info, art, downloads, etc.

**Comment by screwyluie** [comment]
it shows four downloads in the history, two pairs of repeats really. one of each shows failed while the other says grabbed. I clicked the X on each to mark as failed but they don't get marked as failed it just tried to download a release each time I click one of the red X's. That doesn't seem like normal behaviour. Should I delete this whole entry and see if it fixes anything?

**Comment by galli-leo** [comment]
Ah i know whats happening. Can you open another issue titles: 'NetImportSync does not recongize existing movie when only presented with a title'? (Including the log from above)
