### ISSUE TITLE
"Cutoff Unmet" page won't load 

### ISSUE THREAD

**Issue by chuckkay** [Radarr/Radarr#1905]
**Description:**
the Wanted / Cutoff Unmet tab won't load
this happened sometime after 0.2.0.804 
Not sure if i have a corrupt database.

but looks like it has to do with  "t1.Quality" whatever that is

**Radarr Version:**
0.2.0.814

**Logs:**

17-8-10 13:49:52.1|Fatal|NzbDroneErrorPipeline|Request Failed

[v0.2.0.814] System.Data.SQLite.SQLiteException (0x80004005): SQL logic error or missing database
no such column: t1.Quality
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Marr.Data.DataMapper.QueryToGraph[T](String sql, EntityGraph graph, List`1 childrenToLoad) in C:\projects\radarr-usby1\src\Marr.Data\DataMapper.cs:line 624
   at Marr.Data.QGen.QueryBuilder`1.ToList() in C:\projects\radarr-usby1\src\Marr.Data\QGen\QueryBuilder.cs:line 275
   at Marr.Data.QGen.SortBuilder`1.ToList() in C:\projects\radarr-usby1\src\Marr.Data\QGen\SortBuilder.cs:line 176
   at NzbDrone.Core.Tv.MovieRepository.MoviesWhereCutoffUnmet(PagingSpec`1 pagingSpec, List`1 qualitiesBelowCutoff) in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieRepository.cs:line 197
   at NzbDrone.Core.Tv.MovieCutoffService.MoviesWhereCutoffUnmet(PagingSpec`1 pagingSpec) in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieCutoffService.cs:line 45
   at NzbDrone.Api.NzbDroneRestModule`1.ApplyToPage[TModel](Func`2 function, PagingSpec`1 pagingSpec, Converter`2 mapper) in C:\projects\radarr-usby1\src\NzbDrone.Api\NzbDroneRestModule.cs:line 27
   at NzbDrone.Api.Wanted.MovieCutoffModule.GetCutoffUnmetMovies(PagingResource`1 pagingResource) in C:\projects\radarr-usby1\src\NzbDrone.Api\Wanted\MovieCutoffModule.cs:line 30
   at NzbDrone.Api.REST.RestModule`1.<set_GetResourcePaged>b__35_0(Object options) in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:line 126
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

17-8-10 13:49:52.1|Debug|Api|[GET] /api/wanted/cutoff?page=1&pageSize=50&sortKey=title&sortDir=asc&filterKey=monitored&filterValue=true&filterType=equal: 500.InternalServerError (79 ms)
17-8-10 13:49:52.2|Error|NzbDroneErrorPipeline|[GET /api/wanted/cutoff]

[v0.2.0.814] System.Data.SQLite.SQLiteException (0x80004005): SQL logic error or missing database
no such column: t1.Quality
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Marr.Data.DataMapper.QueryToGraph[T](String sql, EntityGraph graph, List`1 childrenToLoad) in C:\projects\radarr-usby1\src\Marr.Data\DataMapper.cs:line 624
   at Marr.Data.QGen.QueryBuilder`1.ToList() in C:\projects\radarr-usby1\src\Marr.Data\QGen\QueryBuilder.cs:line 275
   at Marr.Data.QGen.SortBuilder`1.ToList() in C:\projects\radarr-usby1\src\Marr.Data\QGen\SortBuilder.cs:line 176
   at NzbDrone.Core.Tv.MovieRepository.MoviesWhereCutoffUnmet(PagingSpec`1 pagingSpec, List`1 qualitiesBelowCutoff) in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieRepository.cs:line 197
   at NzbDrone.Core.Tv.MovieCutoffService.MoviesWhereCutoffUnmet(PagingSpec`1 pagingSpec) in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieCutoffService.cs:line 45
   at NzbDrone.Api.NzbDroneRestModule`1.ApplyToPage[TModel](Func`2 function, PagingSpec`1 pagingSpec, Converter`2 mapper) in C:\projects\radarr-usby1\src\NzbDrone.Api\NzbDroneRestModule.cs:line 27
   at NzbDrone.Api.Wanted.MovieCutoffModule.GetCutoffUnmetMovies(PagingResource`1 pagingResource) in C:\projects\radarr-usby1\src\NzbDrone.Api\Wanted\MovieCutoffModule.cs:line 30
   at NzbDrone.Api.REST.RestModule`1.<set_GetResourcePaged>b__35_0(Object options) in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:line 126
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

**Comment by galli-leo** [comment]
Fixed in latest nightly.

**Comment by chuckkay** [comment]
Please reopen
The latest nightly did fix the Radar wont start error...
But has NOT FIXED the "Cutoff Unmet" page not loading..

"T1 Quality"

**Comment by galli-leo** [comment]
Can you post the full log?

**Comment by chuckkay** [comment]
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/1216495/radarr.debug.txt)

**Comment by phil-lavin** [comment]
Confirmed not working on 0.2.0.814.

```17-8-11 12:51:43.2|Error|NzbDroneErrorPipeline|[GET /api/wanted/cutoff]

[v0.2.0.814] System.Data.SQLite.SQLiteException (0x80004005): SQL logic error or missing database
no such column: t1.Quality
  at System.Data.SQLite.SQLite3.Prepare (System.Data.SQLite.SQLiteConnection cnn, System.String strSql, System.Data.SQLite.SQLiteStatement previous, System.UInt32 timeoutMS, System.String& strRemain) [0x0033c] in <61a20cde294d4a3eb43b9d9f6284613b>:0
  at System.Data.SQLite.SQLiteCommand.BuildNextCommand () [0x000f6] in <61a20cde294d4a3eb43b9d9f6284613b>:0
  at System.Data.SQLite.SQLiteCommand.GetStatement (System.Int32 index) [0x00008] in <61a20cde294d4a3eb43b9d9f6284613b>:0
  at (wrapper remoting-invoke-with-check) System.Data.SQLite.SQLiteCommand:GetStatement (int)
  at System.Data.SQLite.SQLiteDataReader.NextResult () [0x0011e] in <61a20cde294d4a3eb43b9d9f6284613b>:0
  at System.Data.SQLite.SQLiteDataReader..ctor (System.Data.SQLite.SQLiteCommand cmd, System.Data.CommandBehavior behave) [0x00090] in <61a20cde294d4a3eb43b9d9f6284613b>:0
  at (wrapper remoting-invoke-with-check) System.Data.SQLite.SQLiteDataReader:.ctor (System.Data.SQLite.SQLiteCommand,System.Data.CommandBehavior)
  at System.Data.SQLite.SQLiteCommand.ExecuteReader (System.Data.CommandBehavior behavior) [0x0000c] in <61a20cde294d4a3eb43b9d9f6284613b>:0
  at System.Data.SQLite.SQLiteCommand.ExecuteDbDataReader (System.Data.CommandBehavior behavior) [0x00000] in <61a20cde294d4a3eb43b9d9f6284613b>:0
  at System.Data.Common.DbCommand.ExecuteReader () [0x00000] in <cdc42ce9980a4941a4ca468faca7f261>:0
  at (wrapper remoting-invoke-with-check) System.Data.Common.DbCommand:ExecuteReader ()
  at Marr.Data.DataMapper.QueryToGraph[T] (System.String sql, Marr.Data.EntityGraph graph, System.Collections.Generic.List`1[T] childrenToLoad) [0x00031] in C:\projects\radarr-usby1\src\Marr.Data\DataMapper.cs:625
  at Marr.Data.QGen.QueryBuilder`1[T].ToList () [0x00028] in C:\projects\radarr-usby1\src\Marr.Data\QGen\QueryBuilder.cs:275
  at Marr.Data.QGen.SortBuilder`1[T].ToList () [0x00000] in C:\projects\radarr-usby1\src\Marr.Data\QGen\SortBuilder.cs:176
  at NzbDrone.Core.Tv.MovieRepository.MoviesWhereCutoffUnmet (NzbDrone.Core.Datastore.PagingSpec`1[TModel] pagingSpec, System.Collections.Generic.List`1[T] qualitiesBelowCutoff) [0x000c3] in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieRepository.cs:197
  at NzbDrone.Core.Tv.MovieCutoffService.MoviesWhereCutoffUnmet (NzbDrone.Core.Datastore.PagingSpec`1[TModel] pagingSpec) [0x000c5] in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieCutoffService.cs:45
  at NzbDrone.Api.NzbDroneRestModule`1[TResource].ApplyToPage[TModel] (System.Func`2[T,TResult] function, NzbDrone.Core.Datastore.PagingSpec`1[TModel] pagingSpec, System.Converter`2[TInput,TOutput] mapper) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\NzbDroneRestModule.cs:27
  at NzbDrone.Api.Wanted.MovieCutoffModule.GetCutoffUnmetMovies (NzbDrone.Api.PagingResource`1[TResource] pagingResource) [0x0002b] in C:\projects\radarr-usby1\src\NzbDrone.Api\Wanted\MovieCutoffModule.cs:30
  at NzbDrone.Api.REST.RestModule`1[TResource].<set_GetResourcePaged>b__35_0 (System.Object options) [0x0002d] in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:132
  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0

17-8-11 12:51:43.3|Fatal|NzbDroneErrorPipeline|Request Failed

[v0.2.0.814] System.Data.SQLite.SQLiteException (0x80004005): SQL logic error or missing database
no such column: t1.Quality
  at System.Data.SQLite.SQLite3.Prepare (System.Data.SQLite.SQLiteConnection cnn, System.String strSql, System.Data.SQLite.SQLiteStatement previous, System.UInt32 timeoutMS, System.String& strRemain) [0x0033c] in <61a20cde294d4a3eb43b9d9f6284613b>:0
  at System.Data.SQLite.SQLiteCommand.BuildNextCommand () [0x000f6] in <61a20cde294d4a3eb43b9d9f6284613b>:0
  at System.Data.SQLite.SQLiteCommand.GetStatement (System.Int32 index) [0x00008] in <61a20cde294d4a3eb43b9d9f6284613b>:0
  at (wrapper remoting-invoke-with-check) System.Data.SQLite.SQLiteCommand:GetStatement (int)
  at System.Data.SQLite.SQLiteDataReader.NextResult () [0x0011e] in <61a20cde294d4a3eb43b9d9f6284613b>:0
  at System.Data.SQLite.SQLiteDataReader..ctor (System.Data.SQLite.SQLiteCommand cmd, System.Data.CommandBehavior behave) [0x00090] in <61a20cde294d4a3eb43b9d9f6284613b>:0
  at (wrapper remoting-invoke-with-check) System.Data.SQLite.SQLiteDataReader:.ctor (System.Data.SQLite.SQLiteCommand,System.Data.CommandBehavior)
  at System.Data.SQLite.SQLiteCommand.ExecuteReader (System.Data.CommandBehavior behavior) [0x0000c] in <61a20cde294d4a3eb43b9d9f6284613b>:0
  at System.Data.SQLite.SQLiteCommand.ExecuteDbDataReader (System.Data.CommandBehavior behavior) [0x00000] in <61a20cde294d4a3eb43b9d9f6284613b>:0
  at System.Data.Common.DbCommand.ExecuteReader () [0x00000] in <cdc42ce9980a4941a4ca468faca7f261>:0
  at (wrapper remoting-invoke-with-check) System.Data.Common.DbCommand:ExecuteReader ()
  at Marr.Data.DataMapper.QueryToGraph[T] (System.String sql, Marr.Data.EntityGraph graph, System.Collections.Generic.List`1[T] childrenToLoad) [0x00031] in C:\projects\radarr-usby1\src\Marr.Data\DataMapper.cs:625
  at Marr.Data.QGen.QueryBuilder`1[T].ToList () [0x00028] in C:\projects\radarr-usby1\src\Marr.Data\QGen\QueryBuilder.cs:275
  at Marr.Data.QGen.SortBuilder`1[T].ToList () [0x00000] in C:\projects\radarr-usby1\src\Marr.Data\QGen\SortBuilder.cs:176
  at NzbDrone.Core.Tv.MovieRepository.MoviesWhereCutoffUnmet (NzbDrone.Core.Datastore.PagingSpec`1[TModel] pagingSpec, System.Collections.Generic.List`1[T] qualitiesBelowCutoff) [0x000c3] in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieRepository.cs:197
  at NzbDrone.Core.Tv.MovieCutoffService.MoviesWhereCutoffUnmet (NzbDrone.Core.Datastore.PagingSpec`1[TModel] pagingSpec) [0x000c5] in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieCutoffService.cs:45
  at NzbDrone.Api.NzbDroneRestModule`1[TResource].ApplyToPage[TModel] (System.Func`2[T,TResult] function, NzbDrone.Core.Datastore.PagingSpec`1[TModel] pagingSpec, System.Converter`2[TInput,TOutput] mapper) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\NzbDroneRestModule.cs:27
  at NzbDrone.Api.Wanted.MovieCutoffModule.GetCutoffUnmetMovies (NzbDrone.Api.PagingResource`1[TResource] pagingResource) [0x0002b] in C:\projects\radarr-usby1\src\NzbDrone.Api\Wanted\MovieCutoffModule.cs:30
  at NzbDrone.Api.REST.RestModule`1[TResource].<set_GetResourcePaged>b__35_0 (System.Object options) [0x0002d] in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:132
  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0

17-8-11 12:51:43.3|Error|NzbDroneErrorPipeline|[GET /api/wanted/cutoff]

[v0.2.0.814] System.Data.SQLite.SQLiteException (0x80004005): SQL logic error or missing database
no such column: t1.Quality
  at System.Data.SQLite.SQLite3.Prepare (System.Data.SQLite.SQLiteConnection cnn, System.String strSql, System.Data.SQLite.SQLiteStatement previous, System.UInt32 timeoutMS, System.String& strRemain) [0x0033c] in <61a20cde294d4a3eb43b9d9f6284613b>:0
  at System.Data.SQLite.SQLiteCommand.BuildNextCommand () [0x000f6] in <61a20cde294d4a3eb43b9d9f6284613b>:0
  at System.Data.SQLite.SQLiteCommand.GetStatement (System.Int32 index) [0x00008] in <61a20cde294d4a3eb43b9d9f6284613b>:0
  at (wrapper remoting-invoke-with-check) System.Data.SQLite.SQLiteCommand:GetStatement (int)
  at System.Data.SQLite.SQLiteDataReader.NextResult () [0x0011e] in <61a20cde294d4a3eb43b9d9f6284613b>:0
  at System.Data.SQLite.SQLiteDataReader..ctor (System.Data.SQLite.SQLiteCommand cmd, System.Data.CommandBehavior behave) [0x00090] in <61a20cde294d4a3eb43b9d9f6284613b>:0
  at (wrapper remoting-invoke-with-check) System.Data.SQLite.SQLiteDataReader:.ctor (System.Data.SQLite.SQLiteCommand,System.Data.CommandBehavior)
  at System.Data.SQLite.SQLiteCommand.ExecuteReader (System.Data.CommandBehavior behavior) [0x0000c] in <61a20cde294d4a3eb43b9d9f6284613b>:0
  at System.Data.SQLite.SQLiteCommand.ExecuteDbDataReader (System.Data.CommandBehavior behavior) [0x00000] in <61a20cde294d4a3eb43b9d9f6284613b>:0
  at System.Data.Common.DbCommand.ExecuteReader () [0x00000] in <cdc42ce9980a4941a4ca468faca7f261>:0
  at (wrapper remoting-invoke-with-check) System.Data.Common.DbCommand:ExecuteReader ()
  at Marr.Data.DataMapper.QueryToGraph[T] (System.String sql, Marr.Data.EntityGraph graph, System.Collections.Generic.List`1[T] childrenToLoad) [0x00031] in C:\projects\radarr-usby1\src\Marr.Data\DataMapper.cs:625
  at Marr.Data.QGen.QueryBuilder`1[T].ToList () [0x00028] in C:\projects\radarr-usby1\src\Marr.Data\QGen\QueryBuilder.cs:275
  at Marr.Data.QGen.SortBuilder`1[T].ToList () [0x00000] in C:\projects\radarr-usby1\src\Marr.Data\QGen\SortBuilder.cs:176
  at NzbDrone.Core.Tv.MovieRepository.MoviesWhereCutoffUnmet (NzbDrone.Core.Datastore.PagingSpec`1[TModel] pagingSpec, System.Collections.Generic.List`1[T] qualitiesBelowCutoff) [0x000c3] in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieRepository.cs:197
  at NzbDrone.Core.Tv.MovieCutoffService.MoviesWhereCutoffUnmet (NzbDrone.Core.Datastore.PagingSpec`1[TModel] pagingSpec) [0x000c5] in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieCutoffService.cs:45
  at NzbDrone.Api.NzbDroneRestModule`1[TResource].ApplyToPage[TModel] (System.Func`2[T,TResult] function, NzbDrone.Core.Datastore.PagingSpec`1[TModel] pagingSpec, System.Converter`2[TInput,TOutput] mapper) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\NzbDroneRestModule.cs:27
  at NzbDrone.Api.Wanted.MovieCutoffModule.GetCutoffUnmetMovies (NzbDrone.Api.PagingResource`1[TResource] pagingResource) [0x0002b] in C:\projects\radarr-usby1\src\NzbDrone.Api\Wanted\MovieCutoffModule.cs:30
  at NzbDrone.Api.REST.RestModule`1[TResource].<set_GetResourcePaged>b__35_0 (System.Object options) [0x0002d] in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:132
  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0

17-8-11 12:51:43.3|Fatal|NzbDroneErrorPipeline|Request Failed

[v0.2.0.814] System.Data.SQLite.SQLiteException (0x80004005): SQL logic error or missing database
no such column: t1.Quality
  at System.Data.SQLite.SQLite3.Prepare (System.Data.SQLite.SQLiteConnection cnn, System.String strSql, System.Data.SQLite.SQLiteStatement previous, System.UInt32 timeoutMS, System.String& strRemain) [0x0033c] in <61a20cde294d4a3eb43b9d9f6284613b>:0
  at System.Data.SQLite.SQLiteCommand.BuildNextCommand () [0x000f6] in <61a20cde294d4a3eb43b9d9f6284613b>:0
  at System.Data.SQLite.SQLiteCommand.GetStatement (System.Int32 index) [0x00008] in <61a20cde294d4a3eb43b9d9f6284613b>:0
  at (wrapper remoting-invoke-with-check) System.Data.SQLite.SQLiteCommand:GetStatement (int)
  at System.Data.SQLite.SQLiteDataReader.NextResult () [0x0011e] in <61a20cde294d4a3eb43b9d9f6284613b>:0
  at System.Data.SQLite.SQLiteDataReader..ctor (System.Data.SQLite.SQLiteCommand cmd, System.Data.CommandBehavior behave) [0x00090] in <61a20cde294d4a3eb43b9d9f6284613b>:0
  at (wrapper remoting-invoke-with-check) System.Data.SQLite.SQLiteDataReader:.ctor (System.Data.SQLite.SQLiteCommand,System.Data.CommandBehavior)
  at System.Data.SQLite.SQLiteCommand.ExecuteReader (System.Data.CommandBehavior behavior) [0x0000c] in <61a20cde294d4a3eb43b9d9f6284613b>:0
  at System.Data.SQLite.SQLiteCommand.ExecuteDbDataReader (System.Data.CommandBehavior behavior) [0x00000] in <61a20cde294d4a3eb43b9d9f6284613b>:0
  at System.Data.Common.DbCommand.ExecuteReader () [0x00000] in <cdc42ce9980a4941a4ca468faca7f261>:0
  at (wrapper remoting-invoke-with-check) System.Data.Common.DbCommand:ExecuteReader ()
  at Marr.Data.DataMapper.QueryToGraph[T] (System.String sql, Marr.Data.EntityGraph graph, System.Collections.Generic.List`1[T] childrenToLoad) [0x00031] in C:\projects\radarr-usby1\src\Marr.Data\DataMapper.cs:625
  at Marr.Data.QGen.QueryBuilder`1[T].ToList () [0x00028] in C:\projects\radarr-usby1\src\Marr.Data\QGen\QueryBuilder.cs:275
  at Marr.Data.QGen.SortBuilder`1[T].ToList () [0x00000] in C:\projects\radarr-usby1\src\Marr.Data\QGen\SortBuilder.cs:176
  at NzbDrone.Core.Tv.MovieRepository.MoviesWhereCutoffUnmet (NzbDrone.Core.Datastore.PagingSpec`1[TModel] pagingSpec, System.Collections.Generic.List`1[T] qualitiesBelowCutoff) [0x000c3] in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieRepository.cs:197
  at NzbDrone.Core.Tv.MovieCutoffService.MoviesWhereCutoffUnmet (NzbDrone.Core.Datastore.PagingSpec`1[TModel] pagingSpec) [0x000c5] in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieCutoffService.cs:45
  at NzbDrone.Api.NzbDroneRestModule`1[TResource].ApplyToPage[TModel] (System.Func`2[T,TResult] function, NzbDrone.Core.Datastore.PagingSpec`1[TModel] pagingSpec, System.Converter`2[TInput,TOutput] mapper) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\NzbDroneRestModule.cs:27
  at NzbDrone.Api.Wanted.MovieCutoffModule.GetCutoffUnmetMovies (NzbDrone.Api.PagingResource`1[TResource] pagingResource) [0x0002b] in C:\projects\radarr-usby1\src\NzbDrone.Api\Wanted\MovieCutoffModule.cs:30
  at NzbDrone.Api.REST.RestModule`1[TResource].<set_GetResourcePaged>b__35_0 (System.Object options) [0x0002d] in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:132
  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0```

**Comment by jaycedk** [comment]
Hi just did some testing, after Firefox had this issue.
Firefox , Edge and IE11 has this issue.
But in chrome it works, really strange.

**Comment by chuckkay** [comment]
Bump - works fine with 0.2.0.804 but after that version "cutoff unmet" page won't load 
(I am using chrome)

**Comment by chuckkay** [comment]
still happening on 0.2.0.831

**Comment by chuckkay** [comment]
Is this happening to evryone on nightlies after 0.2.0.804, or just some of us?

**Comment by galli-leo** [comment]
Everyone. Its a bad sql query thats kinda hard to fix without it being very hack

**Comment by chuckkay** [comment]
???“Without it being very hack”????

**Comment by galli-leo** [comment]
Very hacky. Sorry wrote that on mobile in a hurry.

**Comment by galli-leo** [comment]
Fixed on latest nightly.

**Comment by jaycedk** [comment]
Nice Thank you :D 
Just checked and it works for me 👍
