### ISSUE TITLE
Unable to Delete Old File already on disk after downloading the new file

### ISSUE THREAD

**Issue by julestop** [Radarr/Radarr#207]
![screen shot 2017-01-12 at 6 38 11 pm](https://cloud.githubusercontent.com/assets/1585230/21912826/7e57801a-d8f6-11e6-87b6-4b8700217df9.png)

**Comment by julestop** [comment]
I'm not sure if this helps:

17-1-12 18:04:57.5|Warn|ImportApprovedMovie|Couldn't import episode C:\Users\Jules\Downloads\MoviesRadarr\Anchorman.The.Legend.Of.Ron.Burgundy.2004.UNRATED.720p.HDDVD.x264-SiNNERS\Anchorman.The.Legend.Of.Ron.Burgundy.2004.UNRATED.720p.HDDVD.x264-SiNNERS.mkv

[v0.2.0.99] System.IO.IOException: Destination already exists [D:\Movies\Anchorman- The Legend of Ron Burgundy (2004)\Anchorman- The Legend of Ron Burgundy (2004).mkv]
   at NzbDrone.Common.Disk.DiskTransferService.ClearTargetPath(String targetPath, Boolean overwrite) in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 331
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, DiskTransferVerificationMode verificationMode) in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 244
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, Boolean verified) in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 183
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.TransferFile(MovieFile movieFile, Movie movie, String destinationFilePath, TransferMode mode) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 117
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.MoveMovieFile(MovieFile movieFile, LocalMovie localMovie) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 77
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile episodeFile, LocalMovie localEpisode, Boolean copyOnly) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 67
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedMovie.cs:line 102

17-1-12 18:04:57.5|Error|DownloadMonitoringService|Couldn't process tracked download Anchorman.The.Legend.Of.Ron.Burgundy.2004.UNRATED.720p.HDDVD.x264-SiNNERS

**Comment by onedr0p** [comment]
@galli-leo Related: #131

**Comment by julestop** [comment]
Yes, although, it seems like it is persistent in the log because it is trying to delete the movie in the destination directory, but can't... So therefore, it can't replace the file.

**Comment by onedr0p** [comment]
The odd thing also, is I removed these entries from the sqlite db and it is still giving me the DownloadMonitoringService error

**Comment by galli-leo** [comment]
This should be fixed in the latest release as the history of movie files is now correctly handeled and therefore, Radarr does not try to import the same movie file twice.

**Comment by Milupa5** [comment]
I still have this problem. It cant delete existing files; how do I fix that (synology)?
