### ISSUE TITLE
When adding Movie - already exists

### ISSUE THREAD

**Issue by gregcbrown** [Radarr/Radarr#2141]
I have had this issue for some time, but just decided to document it. When I search for a movie, to see if I already added it, it's not found. I ADD it and it says "already exists". I have tried updating my library, but I am still seeing this issue.
RADARR Version: 0.2.0.852
Windows 10 pro, current
[RADARR Log.txt](https://github.com/Radarr/Radarr/files/1358975/RADARR.Log.txt)

**Comment by galli-leo** [comment]
This is fixed on the latest nightly.

**Comment by gregcbrown** [comment]
I am still experiencing this issue. When will it be added to the develop version. I am on 0.2.0.870.

**Comment by razlebol** [comment]
I'm still having this issue as well and i'm on the nightly.

**Comment by wuast94** [comment]
have the same issue and dont know how to fix
