### ISSUE TITLE
Issues importing and Weird things in logs

### ISSUE THREAD

**Issue by madvtak** [Radarr/Radarr#221]
Hi

I'm having issues with Radarr not importing any movies in either a "Completed" folder or an "Unsorted" folder.  I've tried both.  I have this running in a docker. I had it set so that when the movie has completed the download it will throw the finished download in the"Unsorted" folder. I pathed it correctly in docker. Granted CP is still running, so if Radarr didnt import it and rename it, CP would within the hour, since it is set to scan that folder once an hour.

I've spoke with a few people in the linuxserer.io chatroom and they suggested that i just have the API do its job. 

So I currently have it set up so that SAB will download the movie, and when it completes it will throw it in the "Completed" folder. Nothing else really sits in there. (Also CP is not associated with that folder at all) Sonarr already grabs what goes in there and distributes accordingly to the /TV folder. (YAY Sonarr)

If anyone can help with this issues it would be greatly appreciated. I can't wait to not have to rely on CouchPotato anymore. (Right now the only good thing is it imports and renames as it should. Downloading and being all automated, not so much) 

I am on the latest version just as an FYI (as up to date when this was typed out)

![image](https://cloud.githubusercontent.com/assets/18261123/21920421/d6f60268-d915-11e6-81fc-934f1203e78d.png)

Within Radarr when a movie has completed the download the activity number will change from Blue to Amber.  When I hover over the amber this is what it says.

Under activity 
![Under Activity ](https://cloud.githubusercontent.com/assets/18261123/21920028/64f76168-d913-11e6-9da5-62916c235c0f.png)

Download folder
![So I go and check the download folder](https://cloud.githubusercontent.com/assets/18261123/21920038/7aed44a6-d913-11e6-9c61-7b35aa1693a0.png)

Paths in docker
![Paths under docker](https://cloud.githubusercontent.com/assets/18261123/21920048/891d8b26-d913-11e6-9a8a-62d140e317bc.png)

When i want to go check logs, i have a whole bunch of TV items in there even tho they shouldn't see each other. Also with this being in Docker running on a Synology, i see weird errors talking about a C: drive.

Logs
![image](https://cloud.githubusercontent.com/assets/18261123/21920295/0b4f289c-d915-11e6-9e18-c162c38ad45a.png)

Within the error
![image](https://cloud.githubusercontent.com/assets/18261123/21920301/1b5bb8a4-d915-11e6-9ae9-a699983512c1.png)

Lastly the error for the import
![image](https://cloud.githubusercontent.com/assets/18261123/21920308/2be7cd66-d915-11e6-80fc-5810131baa7d.png)

**Comment by galli-leo** [comment]
The issues with DownloadMonitoringService is probably because Radarr uses the same category Sonarr and sees the downloads of Sonarr as well. However, these should not cause a problem (They just throw an error but that's it). Try setting a category in your download client's settings.

Regarding the import. It seems like Radarr ties to check the lowercase downloads folder instead of the uppercase one. Maybe that's the problem? It also seems like it does not look in the /complete folder but rather in the /downloads one. Radarr should use the folder your download client tells it downloaded the file to, so unless that does not work, there is nothing much I can do.

What download client are you using?

**Comment by madvtak** [comment]
I'm using SABnzbd. It puts the finished downloads in /Downloads/Completed.  The path i used in docker is in the screen shot.

/Downloads/Complete --> /complete
/Downloads --> Downloads

I'll try and change the mount point to /downloads so its lowercase.

**Comment by madvtak** [comment]
Cleared the log @ 0247

![image](https://cloud.githubusercontent.com/assets/18261123/21927594/27152f2e-d93b-11e6-8117-48776f66d492.png)

![image](https://cloud.githubusercontent.com/assets/18261123/21927587/1c302596-d93b-11e6-8dde-1771d217ed86.png)

Changed the mount path to reflect the lowercase "downloads" 
![image](https://cloud.githubusercontent.com/assets/18261123/21927649/605a3eb4-d93b-11e6-996d-20a34abc3043.png)

![image](https://cloud.githubusercontent.com/assets/18261123/21927635/51a90f3a-d93b-11e6-97fa-cd0e67df6ad8.png)

**Comment by madvtak** [comment]
Trying one more Mount path file change

![image](https://cloud.githubusercontent.com/assets/18261123/21927911/c906ca8a-d93c-11e6-95ad-f3976e9cf743.png)

**Comment by madvtak** [comment]
Okay that seem to do something different. Here's the error it threw out.

![image](https://cloud.githubusercontent.com/assets/18261123/21927971/21b75866-d93d-11e6-90d0-ae8f5f602697.png)

**Comment by galli-leo** [comment]
That's at least something 😬. Can you check if the permissions and owner of these folders are correctly set?

**Comment by madvtak** [comment]
Maybe the owner of this folder should not be root?

![image](https://cloud.githubusercontent.com/assets/18261123/21928555/52497e2a-d940-11e6-9840-23d663e50402.png)

**Comment by galli-leo** [comment]
Yeah that shouldn't be. Try setting it to user or something like that.

**Comment by galli-leo** [comment]
You could also try running Radarr as root

**Comment by madvtak** [comment]
I'm running this in docker, i can run an container as root?

**Comment by galli-leo** [comment]
I don't know mich about docker 😬 Try asking around in the linuxserver.io

**Comment by madvtak** [comment]
You know whats weird. i just tested this with Sonarr. 

![image](https://cloud.githubusercontent.com/assets/18261123/21928931/8c81fb42-d942-11e6-9abb-d8305a6a7924.png)

Even tho it said it said  import failed, it still imported just fine.

![image](https://cloud.githubusercontent.com/assets/18261123/21928942/a669613a-d942-11e6-9d08-8f988ca30af4.png)

**Comment by galli-leo** [comment]
Interesting. Did you look if it imported the movie correctly?

**Comment by madvtak** [comment]
Very weird again, i checked all my movies i have waiting. Stage Coach did create a folder in my /Movies section. But its empty.

**Comment by madvtak** [comment]
Running a fresh test. Sorry I have to cut up these log files. There thousands of "DownloadMonitoringService" 

![image](https://cloud.githubusercontent.com/assets/18261123/21929779/85eb4612-d947-11e6-9b2a-f7cef6c25d11.png)


![image](https://cloud.githubusercontent.com/assets/18261123/21929812/b33f3268-d947-11e6-9172-4b2a9bbb4d5c.png)

Just about done.
![image](https://cloud.githubusercontent.com/assets/18261123/21929887/037a0a00-d948-11e6-9416-63e0bb9f1fb7.png)

![image](https://cloud.githubusercontent.com/assets/18261123/21929902/12c66a76-d948-11e6-8002-40e3677b91a7.png)

![image](https://cloud.githubusercontent.com/assets/18261123/21930012/9e11f654-d948-11e6-8e85-5c8634a553d5.png)

![image](https://cloud.githubusercontent.com/assets/18261123/21930020/aa905970-d948-11e6-891c-a162256617a8.png)

![image](https://cloud.githubusercontent.com/assets/18261123/21930043/c2158782-d948-11e6-8cc1-8f4e6ed4cb60.png)


Final Verdict, it's sitting in the /Downloads/Complete folder, which i have pathed as 

/Downloads/Complete --> /downloads

**Comment by galli-leo** [comment]
Did you check the movie folder displayed in the movie details page? It could be that loving is failing and Radarr falls back to hardlinking.

**Comment by madvtak** [comment]
The folder it should be
![image](https://cloud.githubusercontent.com/assets/18261123/21930794/c55a697c-d94c-11e6-9049-78a74f504526.png)

I Just moved it back my default CP renamer folder. and it moved it.

![image](https://cloud.githubusercontent.com/assets/18261123/21930862/225c97d0-d94d-11e6-8429-7489da80067b.png)

I just "update movie and scan disk" and it found it just fine. It just isn't importing. I guess until that portion is fixed have CP as my renamer. :man_shrugging:

**Comment by galli-leo** [comment]
I have fixed a few things in the latest release regarding the import process. Can you try this again? (You will have to download a new movie to try this out)

**Comment by madvtak** [comment]
I tried a new one, still not working as it should. 

![image](https://cloud.githubusercontent.com/assets/18261123/21971654/8c9ee140-db67-11e6-9ff8-78c084c95495.png)

**Comment by madvtak** [comment]
I think i'm going to try to do a fresh install. Will follow up.

**Comment by madvtak** [comment]
Figured it out, owner needed to be added in permissions with full control.

![image](https://cloud.githubusercontent.com/assets/18261123/21973947/cc06fb86-db78-11e6-8c2a-cf83ebfced66.png)

**Comment by madvtak** [comment]
Looks to be having issues still. Here are the logs.

![image](https://cloud.githubusercontent.com/assets/18261123/21977758/6c8b58e6-db8c-11e6-86b7-fa20039f3968.png)

![image](https://cloud.githubusercontent.com/assets/18261123/21977776/8619a952-db8c-11e6-9916-c4d71bb4e651.png)

It did however try and create the folder.

![image](https://cloud.githubusercontent.com/assets/18261123/21977812/b4522132-db8c-11e6-92ca-da48a069195d.png)

**Comment by madvtak** [comment]
Manually import works, but does not delete the original file causing double files.

**Comment by daveguerra** [comment]
Create a user and group and assign the RW permissions to the group. 

Then set the Environment to something like this where PUID = userID and PGID = groupID.   Once I did this I was able to resolve the similar issues you were having 

![image](https://cloud.githubusercontent.com/assets/24866112/22261976/a4db420c-e234-11e6-83b3-876248e1f5c1.png)


To find the PGID & PUID use the following:

  $ id <dockeruser>
    uid=1001(dockeruser) gid=1001(dockergroup) groups=1001(dockergroup)

**Comment by madvtak** [comment]
This is how i have mine set up. 

![image](https://cloud.githubusercontent.com/assets/18261123/22279394/728ee6aa-e27f-11e6-8ed1-9e3563bf66f5.png)

![image](https://cloud.githubusercontent.com/assets/18261123/22279437/bb04bd24-e27f-11e6-9088-673d88b9c74a.png)

**Comment by madvtak** [comment]
Testing fresh grab....

**Comment by madvtak** [comment]
New errors

I gave RW to /Movies & /Downloads so that it can move from /Downloads to /Movies. 

![image](https://cloud.githubusercontent.com/assets/18261123/22279979/c2347712-e282-11e6-98f6-09aa941ff384.png)

**Comment by madvtak** [comment]
Okay deleted comment, i already had that movie. It should have shown it?

Anyways tested with a new movie. (Speed), Seems like now it copies and movies it, the original download does not get deleted. However, after a few seconds or minutes, in /Downloads/Speed (1994) the file is deleted, and manual import no longer works. (It says it was imported, yet the folder shows otherwise.)

![image](https://cloud.githubusercontent.com/assets/18261123/22280184/05dddeee-e284-11e6-8e58-43fa847947e0.png)


![image](https://cloud.githubusercontent.com/assets/18261123/22280207/30f16574-e284-11e6-832f-fc091295f020.png)

![image](https://cloud.githubusercontent.com/assets/18261123/22280221/437e685e-e284-11e6-99c4-8ffacff5c85d.png)

![image](https://cloud.githubusercontent.com/assets/18261123/22280241/5f610bbc-e284-11e6-984e-abb4a415c178.png)

![image](https://cloud.githubusercontent.com/assets/18261123/22280438/92c06272-e285-11e6-8f40-7a4d1adc9897.png)

**Comment by magaman** [comment]
I'm having a similar issue in OSX. After download no import occurs, logs say it can't access, UI says no files exist. Also manual import works strange, I can't manually import from the Activity tab, I have to go to Wanted, then I have to search for the downloaded movie's folder, can't use the folder where all movies are downloaded, once I do that Manual import doesn't work, but if I do manual import then  Import files automatically it works.

**Comment by onedr0p** [comment]
Closing issue,  this issue is a multi issue. Please open a issue if you're still having a issue
