### ISSUE TITLE
Feature request: {original filename} renaming option

### ISSUE THREAD

**Issue by stevekr** [Radarr/Radarr#2253]
Add `{original filename}` renaming option to keep original file name like in Sonarr (`{original title}` is not the same).

**Comment by galli-leo** [comment]
We have that already?

**Comment by stevekr** [comment]
If I enter `{original filename}` to the Standard Movie Format input I get “Must contain movie title” error.
Radarr version 0.2.0.870

**Comment by galli-leo** [comment]
Can you try Original Filename?

**Comment by stevekr** [comment]
Same error.

**Comment by cryodream** [comment]
Same here.
Is there any way to stop Radarr from renaming anything, ie: keep the original folder name and original file name? I can't seem to find how to do that. I have rename disabled, and still the folder gets renamed to `Movie Title (Year)`.
If not - that's a real deal breaker.
Actually, not having an option to disable renaming completely would be really weird...

**Comment by cuki** [comment]
@galli-leo It seems the `{Original Title}` token is [defined](https://github.com/Radarr/Radarr/blob/520836f475cd5ed79e72b663c8b3cceb820a5f4f/src/NzbDrone.Core/Organizer/FileNameBuilder.cs#L552), but it was forgotten to add the possibility to [FileNameBuilder.MovieTitleRegex](https://github.com/Radarr/Radarr/blob/520836f475cd5ed79e72b663c8b3cceb820a5f4f/src/NzbDrone.Core/Organizer/FileNameBuilder.cs#L64), resulting file name validation to fail with error "Must contain movie title".

**Comment by stevekr** [comment]
So is there a plan to fix this?

**Comment by galli-leo** [comment]
Fixed in latest release.

**Comment by stevekr** [comment]
Thanks!

**Comment by martinbenny** [comment]
I still have this problem. Folders get renamed to movie title (year)
