### ISSUE TITLE
Import List error

### ISSUE THREAD

**Issue by Miloune** [Radarr/Radarr#2295]
Hello,

**Description:**
Radarr is trying to import list i added, but when it found a movie already added in past, it just throw an error, stop task and didn't continue to add other movie from list.

**Radarr Version:**
0.2.0.870

**Logs:**
Error occurred while executing task NetImportSync: constraint failed
UNIQUE constraint failed: Movies.TitleSlug

```
System.Data.SQLite.SQLiteException (0x80004005): constraint failed
UNIQUE constraint failed: Movies.TitleSlug
  at System.Data.SQLite.SQLite3.Reset (System.Data.SQLite.SQLiteStatement stmt) [0x00083] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at System.Data.SQLite.SQLite3.Step (System.Data.SQLite.SQLiteStatement stmt) [0x0003c] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at System.Data.SQLite.SQLiteDataReader.NextResult () [0x0016b] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at System.Data.SQLite.SQLiteDataReader..ctor (System.Data.SQLite.SQLiteCommand cmd, System.Data.CommandBehavior behave) [0x00090] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at (wrapper remoting-invoke-with-check) System.Data.SQLite.SQLiteDataReader:.ctor (System.Data.SQLite.SQLiteCommand,System.Data.CommandBehavior)
  at System.Data.SQLite.SQLiteCommand.ExecuteReader (System.Data.CommandBehavior behavior) [0x0000c] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at System.Data.SQLite.SQLiteCommand.ExecuteScalar (System.Data.CommandBehavior behavior) [0x00006] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at System.Data.SQLite.SQLiteCommand.ExecuteScalar () [0x00006] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at Marr.Data.QGen.InsertQueryBuilder`1[T].Execute () [0x00051] in <0858619ae33842c3a98f8405ba7d36b2>:0 
  at Marr.Data.DataMapper.Insert[T] (T entity) [0x0005d] in <0858619ae33842c3a98f8405ba7d36b2>:0 
  at NzbDrone.Core.Datastore.BasicRepository`1[TModel].Insert (TModel model) [0x00033] in <9ad4852ba2664806bd2189b6172b8818>:0 
  at NzbDrone.Core.Tv.MovieService.AddMovie (NzbDrone.Core.Tv.Movie newMovie) [0x0012c] in <9ad4852ba2664806bd2189b6172b8818>:0 
  at NzbDrone.Core.NetImport.NetImportSearchService.Execute (NzbDrone.Core.NetImport.NetImportSyncCommand message) [0x000e3] in <9ad4852ba2664806bd2189b6172b8818>:0 
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand] (TCommand command, NzbDrone.Core.Messaging.Commands.CommandModel commandModel) [0x000ec] in <9ad4852ba2664806bd2189b6172b8818>:0 
  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
  at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2] (System.Runtime.CompilerServices.CallSite site, T0 arg0, T1 arg1, T2 arg2) [0x00110] in <521f3fe476f34ea88748e97b3b984d05>:0 
  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands () [0x0008c] in <9ad4852ba2664806bd2189b6172b8818>:0 
```

**Comment by galli-leo** [comment]
Can you post the list you are using as well as an extended log?

**Comment by Miloune** [comment]
Here is the list i'm trying to import: http://rss.allocine.fr/ac/cine/topfilms

```
17-12-12 21:32:29.9|Debug|NetImportSearchService|Found 20 movies from list(s) Allocine - Top Films
17-12-12 21:32:29.9|Info|NetImportSearchService|Found 20 movies on your auto enabled lists not in your library
17-12-12 21:32:29.9|Debug|Parser|Parsing string 'Coco'
17-12-12 21:32:29.9|Debug|Parser|Unable to parse Coco
17-12-12 21:32:30.3|Info|MovieService|Adding Movie [][Coco (2017)] Path: [/mnt/multimedia/Films/Coco (2017)]
17-12-12 21:32:30.3|Error|CommandExecutor|Error occurred while executing task NetImportSync

[v0.2.0.870] System.Data.SQLite.SQLiteException (0x80004005): constraint failed
UNIQUE constraint failed: Movies.TitleSlug
  at System.Data.SQLite.SQLite3.Reset (System.Data.SQLite.SQLiteStatement stmt) [0x00083] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at System.Data.SQLite.SQLite3.Step (System.Data.SQLite.SQLiteStatement stmt) [0x0003c] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at System.Data.SQLite.SQLiteDataReader.NextResult () [0x0016b] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at System.Data.SQLite.SQLiteDataReader..ctor (System.Data.SQLite.SQLiteCommand cmd, System.Data.CommandBehavior behave) [0x00090] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at (wrapper remoting-invoke-with-check) System.Data.SQLite.SQLiteDataReader:.ctor (System.Data.SQLite.SQLiteCommand,System.Data.CommandBehavior)
  at System.Data.SQLite.SQLiteCommand.ExecuteReader (System.Data.CommandBehavior behavior) [0x0000c] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at System.Data.SQLite.SQLiteCommand.ExecuteScalar (System.Data.CommandBehavior behavior) [0x00006] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at System.Data.SQLite.SQLiteCommand.ExecuteScalar () [0x00006] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at Marr.Data.QGen.InsertQueryBuilder`1[T].Execute () [0x00046] in C:\projects\radarr-usby1\src\Marr.Data\QGen\InsertQueryBuilder.cs:140 
  at Marr.Data.DataMapper.Insert[T] (T entity) [0x0005d] in C:\projects\radarr-usby1\src\Marr.Data\DataMapper.cs:728 
  at NzbDrone.Core.Datastore.BasicRepository`1[TModel].Insert (TModel model) [0x0002d] in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\BasicRepository.cs:114 
  at NzbDrone.Core.Tv.MovieService.AddMovie (NzbDrone.Core.Tv.Movie newMovie) [0x0012c] in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieService.cs:181 
  at NzbDrone.Core.NetImport.NetImportSearchService.Execute (NzbDrone.Core.NetImport.NetImportSyncCommand message) [0x000e3] in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\NetImportSearchService.cs:136 
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand] (TCommand command, NzbDrone.Core.Messaging.Commands.CommandModel commandModel) [0x000ec] in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:91 
  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
  at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2] (System.Runtime.CompilerServices.CallSite site, T0 arg0, T1 arg1, T2 arg2) [0x00035] in <521f3fe476f34ea88748e97b3b984d05>:0 
  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands () [0x00027] in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:41 

```

**Comment by galli-leo** [comment]
Oh wow, surprised you got that to even work 😬. Anyways, looks like it's not correctly parsing movie information and so doesn't know those are already added.

**Comment by galli-leo** [comment]
Should be fixed in next release

**Comment by Miloune** [comment]
Many thanks! :)

**Comment by Miloune** [comment]
Hello,
Your fix worked fews days, but now i still have the same issue. Here are my logs:

`17-12-21 18:03:42.6|Debug|RSSImport|Downloading List http://rss.allocine.fr/ac/cine/topfilms
17-12-21 18:03:42.7|Debug|Parser|Parsing string 'Coco'
17-12-21 18:03:42.7|Debug|Parser|Unable to parse Coco
17-12-21 18:03:42.7|Debug|Parser|Parsing string 'Star Wars - Les Derniers Jedi'
17-12-21 18:03:42.7|Debug|Parser|Unable to parse Star Wars - Les Derniers Jedi
17-12-21 18:03:42.7|Debug|Parser|Parsing string 'Santa & Cie'
17-12-21 18:03:42.7|Debug|Parser|Unable to parse Santa & Cie
17-12-21 18:03:42.7|Debug|Parser|Parsing string 'Paddington 2'
17-12-21 18:03:42.7|Debug|Parser|Unable to parse Paddington 2
17-12-21 18:03:42.7|Debug|Parser|Parsing string 'Ferdinand'
17-12-21 18:03:42.7|Debug|Parser|Unable to parse Ferdinand
17-12-21 18:03:42.7|Debug|Parser|Parsing string 'La DeuxiÃ¨me Ã©toile'
17-12-21 18:03:42.7|Debug|Parser|Unable to parse La DeuxiÃ¨me Ã©toile
17-12-21 18:03:42.7|Debug|Parser|Parsing string 'Jumanji : Bienvenue dans la jungle'
17-12-21 18:03:42.7|Debug|Parser|Unable to parse Jumanji : Bienvenue dans la jungle
17-12-21 18:03:42.7|Debug|Parser|Parsing string 'La Promesse de l'aube'
17-12-21 18:03:42.7|Debug|Parser|Unable to parse La Promesse de l'aube
17-12-21 18:03:42.7|Debug|Parser|Parsing string 'Le Crime de l'Orient-Express'
17-12-21 18:03:42.7|Debug|Parser|Unable to parse Le Crime de l'Orient-Express
17-12-21 18:03:42.7|Debug|Parser|Parsing string 'Stars 80, la suite'
17-12-21 18:03:42.7|Debug|Parser|Unable to parse Stars 80, la suite
17-12-21 18:03:42.7|Debug|Parser|Parsing string 'La Villa'
17-12-21 18:03:42.7|Debug|Parser|Unable to parse La Villa
17-12-21 18:03:42.7|Debug|Parser|Parsing string 'Les Gardiennes'
17-12-21 18:03:42.7|Debug|Parser|Unable to parse Les Gardiennes
17-12-21 18:03:42.7|Debug|Parser|Parsing string 'DrÃ´les de petites bÃªtes'
17-12-21 18:03:42.7|Debug|Parser|Unable to parse DrÃ´les de petites bÃªtes
17-12-21 18:03:42.7|Debug|Parser|Parsing string 'Garde alternÃ©e'
17-12-21 18:03:42.7|Debug|Parser|Unable to parse Garde alternÃ©e
17-12-21 18:03:42.7|Debug|Parser|Parsing string 'Le Brio'
17-12-21 18:03:42.7|Debug|Parser|Unable to parse Le Brio
17-12-21 18:03:42.7|Debug|Parser|Parsing string 'L'Etoile de NoÃ«l'
17-12-21 18:03:42.7|Debug|Parser|Unable to parse L'Etoile de NoÃ«l
17-12-21 18:03:42.7|Debug|Parser|Parsing string 'Tout lÃ -haut'
17-12-21 18:03:42.7|Debug|Parser|Unable to parse Tout lÃ -haut
17-12-21 18:03:42.7|Debug|Parser|Parsing string 'Ernest et CÃ©lestine en hiver'
17-12-21 18:03:42.7|Debug|Parser|Unable to parse Ernest et CÃ©lestine en hiver
17-12-21 18:03:42.7|Debug|Parser|Parsing string 'Wonder'
17-12-21 18:03:42.7|Debug|Parser|Unable to parse Wonder
17-12-21 18:03:42.7|Debug|Parser|Parsing string 'Myrtille et la lettre au PÃ¨re NoÃ«l'
17-12-21 18:03:42.7|Debug|Parser|Unable to parse Myrtille et la lettre au PÃ¨re NoÃ«l
17-12-21 18:03:42.7|Debug|NetImportSearchService|Found 20 movies from list(s) Allocine - Top Films
17-12-21 18:03:42.8|Info|NetImportSearchService|Found 6 movies on your auto enabled lists not in your library
17-12-21 18:03:42.8|Debug|Parser|Parsing string 'Star Wars - Les Derniers Jedi'
17-12-21 18:03:42.8|Debug|Parser|Unable to parse Star Wars - Les Derniers Jedi
17-12-21 18:03:43.3|Info|MovieService|Adding Movie [][Star Wars: The Last Jedi (2017)] Path: [/mnt/multimedia/Films/Star Wars The Last Jedi (2017)]
17-12-21 18:03:43.4|Error|CommandExecutor|Error occurred while executing task NetImportSync

[v0.2.0.910] System.Data.SQLite.SQLiteException (0x80004005): constraint failed
UNIQUE constraint failed: Movies.TitleSlug
  at System.Data.SQLite.SQLite3.Reset (System.Data.SQLite.SQLiteStatement stmt) [0x00083] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at System.Data.SQLite.SQLite3.Step (System.Data.SQLite.SQLiteStatement stmt) [0x0003c] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at System.Data.SQLite.SQLiteDataReader.NextResult () [0x0016b] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at System.Data.SQLite.SQLiteDataReader..ctor (System.Data.SQLite.SQLiteCommand cmd, System.Data.CommandBehavior behave) [0x00090] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at (wrapper remoting-invoke-with-check) System.Data.SQLite.SQLiteDataReader:.ctor (System.Data.SQLite.SQLiteCommand,System.Data.CommandBehavior)
  at System.Data.SQLite.SQLiteCommand.ExecuteReader (System.Data.CommandBehavior behavior) [0x0000c] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at System.Data.SQLite.SQLiteCommand.ExecuteScalar (System.Data.CommandBehavior behavior) [0x00006] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at System.Data.SQLite.SQLiteCommand.ExecuteScalar () [0x00006] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at Marr.Data.QGen.InsertQueryBuilder`1[T].Execute () [0x00046] in C:\projects\radarr-usby1\src\Marr.Data\QGen\InsertQueryBuilder.cs:140 
  at Marr.Data.DataMapper.Insert[T] (T entity) [0x0005d] in C:\projects\radarr-usby1\src\Marr.Data\DataMapper.cs:728 
  at NzbDrone.Core.Datastore.BasicRepository`1[TModel].Insert (TModel model) [0x0002d] in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\BasicRepository.cs:114 
  at NzbDrone.Core.Tv.MovieService.AddMovie (NzbDrone.Core.Tv.Movie newMovie) [0x0012c] in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieService.cs:181 
  at NzbDrone.Core.NetImport.NetImportSearchService.Execute (NzbDrone.Core.NetImport.NetImportSyncCommand message) [0x000e3] in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\NetImportSearchService.cs:136 
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand] (TCommand command, NzbDrone.Core.Messaging.Commands.CommandModel commandModel) [0x000ec] in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:91 
  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
  at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2] (System.Runtime.CompilerServices.CallSite site, T0 arg0, T1 arg1, T2 arg2) [0x00035] in <521f3fe476f34ea88748e97b3b984d05>:0 
  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands () [0x00027] in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:41 
`

**Comment by 11001010111111101011101010111110** [comment]
Any update on this? I have had the same issue for a few months.

**Comment by mbc0** [comment]
Hi, I just started using lists and have the same problem, any updates?

Many Thanks
