### ISSUE TITLE
After download and import, disk isn't refreshed automatically

### ISSUE THREAD

**Issue by fryfrog** [Radarr/Radarr#2367]
**Description:**
After a movie downloads and successfully imports, it isn't reflected. If the movie was missing, it still appears missing. If it was there, but a different version... it doesn't get updated. The 12/24h refresh fixes it, as does going to a movie and specifically doing a refresh.

I've seen many reports of this on both reddit and in #support on Discord.

**Radarr Version:**
 0.2.0.912

**Logs:**
Will try and repro and get specific logs. :/

**Comment by galli-leo** [comment]
Does this still occur on the latest version (after a browser refresh)?

**Comment by fryfrog** [comment]
A full browser refresh shows it there. As does clicking the refresh button. So I guess this is simply a poor display behavior. Close if you want.

**Comment by theotherp** [comment]
Similar problem here but disk scan doesn't help.

Media management settings: https://i.imgur.com/9mCwQjt.png

I've added a movie and searched for it. Radarr finds it on the indexer, downloads it, moves it to the correct folder and then says the files are missing. It's also shown yellow in the Activity tab. Manual import says "No video files were found in the selected folder.".

Full log from start to finish (I've change the movie title...):

```
18-2-11 08:07:55.4|Info|MovieService|Adding Movie [][Madman: Nottingham by Daylight (2018)] Path: [E:\Download\Movies\Madman Nottingham by Daylight (2018)]
18-2-11 08:07:55.4|Info|MediaCoverService|Downloading Poster for [][Madman: Nottingham by Daylight (2018)] http://image.tmdb.org/t/p/original/7souLi5zqQCnpZVghaXv0Wowi0y.jpg
18-2-11 08:07:55.4|Info|RefreshMovieService|Updating Info for Madman: Nottingham by Daylight
18-2-11 08:07:56.2|Info|DiskScanService|Scanning disk for Madman: Nottingham by Daylight
18-2-11 08:07:56.2|Info|MovieScannedHandler|[Madman: Nottingham by Daylight] was recently added, performing post-add actions
18-2-11 08:07:56.3|Info|NzbSearchService|Searching 1 indexers for [Madman: Nottingham by Daylight]
18-2-11 08:07:56.3|Info|MediaCoverService|Downloading Banner for [tt7167630][Madman: Nottingham by Daylight (2018)] http://image.tmdb.org/t/p/original/9ojJB7vZR2uDqXdxOzYaADthEBT.jpg
18-2-11 08:07:56.8|Info|DownloadDecisionMaker|Processing 19 releases
18-2-11 08:07:58.8|Info|Nzbget|Adding report [Madman.Nottingham.By.Daylight.2018.HDRip.XviD.AC3-EVO] to the queue.
18-2-11 08:07:59.1|Info|DownloadService|Report sent to nzbget. Madman.Nottingham.By.Daylight.2018.HDRip.XviD.AC3-EVO
18-2-11 08:07:59.1|Info|MovieSearchService|Movie search completed. 1 reports downloaded.
18-2-11 08:09:32.7|Warn|ImportApprovedMovie|Couldn't import movie e:\dl\Madman.Nottingham.By.Daylight.2018.HDRip.XviD.AC3-EVO\Madman Nottingham by Daylight.2018.HDRip.XviD.AC3-EVO.avi

[v0.2.0.935] System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\Download\Movies\Madman Nottingham by Daylight (2018)'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at NzbDrone.Common.Disk.DiskProviderBase.GetFiles(String path, SearchOption searchOption) in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 177
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.TransferFile(MovieFile movieFile, Movie movie, String destinationFilePath, TransferMode mode) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 147
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.MoveMovieFile(MovieFile movieFile, LocalMovie localMovie) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 80
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile movieFile, LocalMovie localMovie, Boolean copyOnly) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 73
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedMovie.cs:line 106

18-2-11 08:10:22.9|Info|RefreshMovieService|Updating Info for Madman: Nottingham by Daylight
18-2-11 08:10:23.4|Info|DiskScanService|Scanning disk for Madman: Nottingham by Daylight
```
This is reproducible and happens with any movie I add.

When I try to set the movie folder to the correct folder (i.e. change it from `E:\Download\Movies\Madman Nottingham by Daylight (2018)` to `E:\Download\Movies\Madman Nottingham by Daylight (2018) - WEBDL-480p`) and press "Update movie and scan disk" it renames the folder to the one using the default format (i.e. `E:\Download\Movies\Madman Nottingham by Daylight (2018)`) and then complains it can't find the movie in the folder that would match the pattern I've set:

```
18-2-11 08:10:22.9|Info|RefreshMovieService|Updating Info for Madman: Nottingham by Daylight
18-2-11 08:10:23.4|Info|DiskScanService|Scanning disk for Madman: Nottingham by Daylight
18-2-11 08:15:35.7|Info|RefreshMovieService|Updating Info for Madman: Nottingham by Daylight
18-2-11 08:15:36.3|Info|RenameMovieFileService|[tt7167630][Madman: Nottingham by Daylight (2018)]'s movie folder changed to: E:\Download\Movies\Madman Nottingham by Daylight (2018)
18-2-11 08:15:36.3|Error|EventAggregator|DiskScanService failed while processing [MovieUpdatedEvent]

[v0.2.0.935] System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\Download\Movies\Madman Nottingham by Daylight (2018) - WEBDL-480p'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption saearchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at NzbDrone.Common.Disk.DiskProviderBase.GetFiles(String path, SearchOption searchOption) in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 177
   at NzbDrone.Core.MediaFiles.RenameMovieFileService.RenameMoviePath(Movie movie, Boolean shouldRenameFiles) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\RenameMovieFileService.cs:line 162
   at NzbDrone.Core.MediaFiles.DiskScanService.Scan(Movie movie) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 142
   at NzbDrone.Core.MediaFiles.DiskScanService.Handle(MovieUpdatedEvent message) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 279
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event) in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:line 56

```

**Comment by galli-leo** [comment]
@theotherp This is fixed on the latest nightly.

**Comment by joshgx** [comment]
I think there is still an issue going on with this. After the Feb 6th update, Radarr is no longer detecting the movies as downloaded and keeps trying to download alternate copies. This is happening even though Radarr has already moved the first copy it downloaded to the proper folder and renamed it. I do have rename movies and rename folders enabled and have hardlinks disabled.. This worked beautifully until the 6th. Thanks guys for all your work!! Radarr is awesome.

**Comment by galli-leo** [comment]
@joshgx Without any logs it is impossible to tell what's going wrong. Also this is more of a support question (better fitted for the discord or subreddit).

**Comment by theotherp** [comment]
I'll test it again tonight and if I can reproduce it I will post the logs (if it's fixed I will tell you).

**Comment by galli-leo** [comment]
@theotherp Sorry that wasn't ment at you. Your issue should be fixed on the latest nightly.

**Comment by theotherp** [comment]
Right, sorry, I read the message on my phone and skipped the @...

Thank you.

**Comment by theotherp** [comment]
For what it's worth I can confirm this was fixed. I still need to refresh the page for the files to be shown but that's a minor inconvenience. Thanks.
