### ISSUE TITLE
736341 days - Wrong torrent age manual search (Indexer: TorrentPotato/Jackett)

### ISSUE THREAD

**Issue by hotio** [Radarr/Radarr#239]
![age](https://cloud.githubusercontent.com/assets/25102010/21945375/371d53ba-d9db-11e6-8f56-98ad71947694.png)

**Comment by onedr0p** [comment]
Fixed in next release.

**Comment by onedr0p** [comment]
Well, I fixed it for some indexers, some don't have a age so it defaults to those crazy amount of days.

![image](https://cloud.githubusercontent.com/assets/213795/21948289/2b4c7a02-d9b8-11e6-8fdb-418c42a54fd4.png)

**Comment by hotio** [comment]
Just installed build `0.2.0.119`, now it says `736342 days`. Not yet fixed I think.

**Comment by onedr0p** [comment]
Did you read my comment before you posted? Some indexers don't have age in jackett, there's nothing we can do about that.

**Comment by hotio** [comment]
All of my indexers are showing a proper and correct age in Jackett

**Comment by onedr0p** [comment]
Hmm, I'll take another glance at this today. What indexes show incorrect age in radarr using jacket? If I'm a member I'll test it out on my end.

**Comment by hotio** [comment]
They all show up correct inside Jackett and wrong inside Radarr

TorrentPotato (TL, AR, IPT, TD)

**Comment by onedr0p** [comment]
I'll take a look today, sorry!

**Comment by hotio** [comment]
Thanks!

**Comment by onedr0p** [comment]
Still seems to be an issue with Jacket I opened a GH issue there.

**Comment by hotio** [comment]
I also get it when using Cardigann

**Comment by onedr0p** [comment]
It's prolly the same thing.

**Comment by onedr0p** [comment]
I created a PR for Jackett to add the release date.

https://github.com/Jackett/Jackett/pull/934

**Comment by onedr0p** [comment]
Created a PR for Cardigann

https://github.com/cardigann/cardigann/pull/305

**Comment by hotio** [comment]
Yep, I saw, thanks

**Comment by onedr0p** [comment]
OKAY working for me now using Jackett 0.7.885.0

**Comment by hotio** [comment]
Yes working now
