### ISSUE TITLE
Radarr Deleting Extra Files

### ISSUE THREAD

**Issue by haleswd** [Radarr/Radarr#2639]
**Radarr Version:**
0.2.0.995

I have been using a program called Media Center Master for years. It organized my collection, and downloaded a lot of extras for my movies. Things like subtitles, banners, and disc art.

I have only had Radarr running for an hour, so I am extremely new. However, I have it set to monitor my movies. It downloaded one, and instead of just replacing the movie, it deleted all of my extras in the folder, and then moved the updated movie in.

Can a feature be added that will allow me to keep all of my extras, and just replace the actual movie?

**Comment by galli-leo** [comment]
Do you have automatic folder rename on? It should leave all other files alone, not sure why it did that.

**Comment by haleswd** [comment]
I do not have automatic folder rename on.  
I have added the extensions of my extra files to the Import Extra Files feature.  I was hoping that this might solve my issue.

**Comment by galli-leo** [comment]
Can you turn on debug logging, and save the logs the next time this happens?

**Comment by haleswd** [comment]
I just switched on debug logging.  I'll post back here once I notice it happen again.  I have almost 1300 movies.  I hate to think how big that log will be if the library updates.

**Comment by Qstick** [comment]
nfo processing changes in a current Sonarr PR should help us greatly here. I can pull them over so we can test out.

**Comment by haleswd** [comment]
If you see that I am being a dumb ass with something, please let me know.  I am brand new at Radarr.  So, Dr Strange downloaded, and deleted all of my extra files.

[radarr.debug.txt](https://github.com/Radarr/Radarr/files/1821002/radarr.debug.txt)

**Comment by Qstick** [comment]
It’s deleting everything during upgrade as radarr sees all of these files as being tied to the original movie file. We likely need to add an option or something around this. @galli-leo thoughts?

**Comment by galli-leo** [comment]
@haleswd What exact files were deleted? Just the backdrop images?

@Qstick Maybe handle the case where the File deletion reason is upgrade better? No idea why Sonarr doesn't do that though.

So when handling the MovieFileDeletedMessage, check reason for upgrade. If so only delete files pertaining to the movie file (subtitles and scene nfo)?

**Comment by haleswd** [comment]
@galli-leo  I can't be sure what exactly was in there, but there could have been a few different types of artworks.  backdrops, disk images, covers., etc..  Plus xml files and srt files.  I have the option to get the subtitles turned on now in Radarr, so those are not that big of a deal, as they get put back.

I would think that only the movie would be deleted by default.  An option could be added, that when selected, the entire folder is cleared.  My 2cents.

**Comment by galli-leo** [comment]
@haleswd IMO, subtitle files and movie file nfo should be deleted by default, since they are tied to the movie file and not the movie itself. But I agree that we shouldn't delete files belonging to the whole movie (backdrop, other images, kodi nfo)

**Comment by Qstick** [comment]
Agreed as we are storing file specific info in the nfo files and subs are definitely in same boat. What makes images file specific in many cases is naming. They are many times named `<moviefilename>-poster.jpg` In these cases we have to either delete and re-create or add some logic around renaming them for the new incoming movie file

**Comment by tusharbhutt** [comment]
@Qstick Maybe the logic could be to only look for movie media types and .nfo/.xml files to rename and leave the rest alone?  And, if the movie is being upgraded and the metadata settings are off, leave the .nfo/.xml files alone regardless.

**Comment by nmadole** [comment]
I've having this issue also; I had bonus three bonus video files for a film that were deleted when I scanned for new media.

**Comment by tyblu** [comment]
The fix for this may also affect an error in bulk movie import, where the Plex local extras are being identified as the main movie file. For example, `/media/DiskStation/media/movies/Indiana Jones and the Kingdom of the Crystal Skull (2008)/Adventures in Post-Production-behindthescenes.mkv` is presented as the movie file. Here's the entire folder contents:

```
pi@raspberrypi:/media/DiskStation/media/movies/Indiana Jones and the Kingdom of the Crystal Skull (2008) $ ls -lah
total 19G
drwxr-xr-x 2 pi plugdev    0 Jan 29 21:52 .
drwxr-xr-x 2 pi plugdev    0 Apr  3 17:51 ..
-rwxr-xr-x 1 pi plugdev 496M Jan 24 13:12 Adventures in Post-Production-behindthescenes.mkv
-rwxr-xr-x 1 pi plugdev 145M Jan 24 13:13 Closing - Team Indy-behindthescenes.mkv
-rwxr-xr-x 1 pi plugdev 390M Jan 24 13:06 Iconic Props-behindthescenes.mkv
-rwxr-xr-x 1 pi plugdev 8.0G Nov 11 07:44 Indiana Jones and the Kingdom of the Crystal Skull (2008) 1080p.BluRay.x264-SiNNERS.mkv
-rwxr-xr-x 1 pi plugdev  46M Jan 24 13:17 Indiana Jones - The Ultimate Action Hero-trailer.mkv
-rwxr-xr-x 1 pi plugdev 439M Jan 24 02:01 Pre-Production-behindthescenes.mkv
-rwxr-xr-x 1 pi plugdev 171M Jan 24 13:16 Pre-Visualization Sequence - Ants Attack-behindthescenes.mkv
-rwxr-xr-x 1 pi plugdev 148M Jan 24 13:14 Pre-Visualization Sequence - Area 51 Escape-behindthescenes.mkv
-rwxr-xr-x 1 pi plugdev 221M Jan 24 13:15 Pre-Visualization Sequence - Jungle Chase-behindthescenes.mkv
-rwxr-xr-x 1 pi plugdev 3.3G Jan 24 12:47 Production Diary #0 - Making 'Kingdom of the Crystal Skull' (All)-behindthescenes.mkv
-rwxr-xr-x 1 pi plugdev 588M Jan 24 12:51 Production Diary #1 - Shooting Begins - New Mexico-behindthescenes.mkv
-rwxr-xr-x 1 pi plugdev 422M Jan 24 12:53 Production Diary #2 - Back To School - New Haven Connecticut-behindthescenes.mkv
-rwxr-xr-x 1 pi plugdev 264M Jan 24 12:55 Production Diary #3 - Welcome to th Jungle - Hilo, Hawaii-behindthescenes.mkv
-rwxr-xr-x 1 pi plugdev 1.1G Jan 24 12:59 Production Diary #4 - On-Set Action-behindthescenes.mkv
-rwxr-xr-x 1 pi plugdev 593M Jan 24 13:02 Production Diary #5 - Exploring Akator-behindthescenes.mkv
-rwxr-xr-x 1 pi plugdev 307M Jan 24 13:03 Production Diary #6 - Wrapping Up!-behindthescenes.mkv
-rwxr-xr-x 1 pi plugdev 1.4K Jan 24 13:26 special-features.txt
-rwxr-xr-x 1 pi plugdev  76M Jan 24 13:16 Theatrical Trailer #1-trailer.mkv
-rwxr-xr-x 1 pi plugdev  78M Jan 24 13:17 Theatrical Trailer #2-trailer.mkv
-rwxr-xr-x 1 pi plugdev 397M Jan 24 13:05 The Crystal Skulls-behindthescenes.mkv
-rwxr-xr-x 1 pi plugdev 884M Jan 24 13:10 The Effects of Indy-behindthescenes.mkv
-rwxr-xr-x 1 pi plugdev 657M Jan 24 01:58 The Return of a Legend-featurette.mkv
-rwxr-xr-x 1 pi plugdev 218M Jan 24 13:03 Warrior Makeup-behindthescenes.mkv
```

Complete list of local video extra postfixes (from [here](https://support.plex.tv/articles/200220677-local-media-assets-movies/)): `-behindthescenes`, `-deleted`, `-featurette`, `-interview`, `-scene`, `-short`, `-trailer`.

**Comment by Qstick** [comment]
Correct, I thought import decision maker sorted by size to figure out what file to use for the main movie though.

**Comment by Geek16432** [comment]
This is still occurring. Why did the issue get closed?

**Comment by Qstick** [comment]
@Geek16432 because it was fixed in #2642

**Comment by AwesomeAustn** [comment]
Why was this closed? It's not fixed. It's annoying. I'm glad I have the recycle bin setup.

**Comment by AwesomeAustn** [comment]
This is still happening and I'm on version 3.0.0.3964.

**Comment by bakerboy448** [comment]
@AwesomeAustn please don't comment on closed, 1.5yr old issues
