### ISSUE TITLE
Screen jumps back to the top when adding a movie from "Recommendations"

### ISSUE THREAD

**Issue by jolaroux** [Radarr/Radarr#2781]
- "Add Movie"
- "Recommendations" tab 
- scroll down
- add movie either with + button or with search icon button
-screen jumps back to the top

very annoying. love y'all, thanks.

**Comment by stuntguy3000** [comment]
@jolaroux I've tested this and it does not seem to be a problem any more, can you confirm this is fixed?

**Comment by jolaroux** [comment]
Is this: https://hub.docker.com/r/linuxserver/radarr/ the correct docker version to be using? Because I have the most updated version, says it updated 3 days ago, and it's still a problem. If this isn't the correct radarr version though I'll correct my software

**Comment by stuntguy3000** [comment]
Go System -> About
![image](https://user-images.githubusercontent.com/1522389/48457757-b5fbc980-e813-11e8-88a5-743ca707edf9.png)


What version are you running? I'm on the dev branch.

**Comment by jolaroux** [comment]
<img width="629" alt="image" src="https://user-images.githubusercontent.com/19803454/48457816-915b0f80-e789-11e8-9180-d630eaf0da1e.png">

**Comment by jolaroux** [comment]
Same version it looks like, happens on both Safari and Firefox Nightly, 
Add Movies -> Discover -> is where it's happening

**Comment by stuntguy3000** [comment]
Same version, maybe I am doing something wrong. Let me investigate.
