### ISSUE TITLE
qBittorrent client exception: initial state failed (HTTP error 400: resume BadRequest)

### ISSUE THREAD

**Issue by nistorj** [Radarr/Radarr#2785]
Hello,

Sonarr Version: 0.2.0.1067
Operating System: CentOS 7
mono (macOS/Linux) Version: 5.12.0.233 (from Mono repo)
Link to Log Files (debug or trace): https://pastebin.com/8NH1wMBk
Browser (for UI bugs): N/A

This issue is (what appears to be) identical to the issue found in Sonarr @ https://github.com/Sonarr/Sonarr/issues/2565

The torrent hash gets passed as uppercase however the API was looking for lowercase:

[Warn] HttpClient: HTTP Error - Res: [POST] http://127.0.0.1:8080/command/resume: 400.BadRequest
[Warn] QBittorrent: Failed to set inital state for DD0EB941DA6A842FD1763B6926C0BD276403CCA8.

[v0.2.0.1067] NzbDrone.Core.Download.Clients.DownloadClientException: Failed to connect to qBittorrent, check your settings. ---> NzbDrone.Common.Http.HttpException: HTTP request failed: [400:BadRequest] [POST] at [http://127.0.0.1:8080/command/resume]
  at NzbDrone.Common.Http.HttpClient.Execute (NzbDrone.Common.Http.HttpRequest request) [0x00130] in <77141d2a9480457c809d7c30879133c8>:0
  at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.ProcessRequest (NzbDrone.Common.Http.HttpRequestBuilder requestBuilder, NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentSettings settings) [0x00017] in <24e1ead4ad1e4cd483b3cbe4518022dd>:0
   --- End of inner exception stack trace ---
  at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.ProcessRequest (NzbDrone.Common.Http.HttpRequestBuilder requestBuilder, NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentSettings settings) [0x00073] in <24e1ead4ad1e4cd483b3cbe4518022dd>:0
  at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.ResumeTorrent (System.String hash, NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentSettings settings) [0x00022] in <24e1ead4ad1e4cd483b3cbe4518022dd>:0
  at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.SetInitialState (System.String hash) [0x00042] in <24e1ead4ad1e4cd483b3cbe4518022dd>:0

Thank you,

**Comment by Qstick** [comment]
Seems the actual problem here was on qbit side with pause and resume endpoints https://github.com/qbittorrent/qBittorrent/issues/8880 and was fixed here https://github.com/qbittorrent/qBittorrent/commit/88f2a66aacedecf2eb0c8c46d7ef9c9ce05ddbd7 for 4.1.1 release

**Comment by nistorj** [comment]
Fantastic find!  Thank you!  I can confirm that the latest master of QBT works fine and we don't see any errors in the tracelogs from it.

**Comment by galli-leo** [comment]
Seems like our commit didn't actually fix it @Qstick : https://pastebin.com/1SHWvMBV
