### ISSUE TITLE
Radarr Incorrectly Grabs Movie Quality

### ISSUE THREAD

**Issue by vortexrap** [Radarr/Radarr#324]
For instance, the latest movie, Surfs Up 2. When adding to Radarr, the app searches and grabs the 720p copy. 
![image](https://cloud.githubusercontent.com/assets/15331068/22049059/057b4502-dcff-11e6-94da-d023132deeca.png)

Looking at the available releases:
![image](https://cloud.githubusercontent.com/assets/15331068/22049069/15943066-dcff-11e6-8a39-0dfefda8edfb.png)

Radarr should grab the 1080p copy since it ranks higher on the priority list.

My Quality Profile:
![image](https://cloud.githubusercontent.com/assets/15331068/22049007/ac32f242-dcfe-11e6-8edc-642977688a6b.png)

**Comment by julestop** [comment]
This happens with me as well... it looks like it's grabbing the youngest release first, rather than the best quality. Hope this gets fixed.

**Comment by simonk83** [comment]
Guess we need some sort of score like CP has, unless it's already doing similar stuff in the background (and just on the fritz at the moment)

**Comment by galli-leo** [comment]
@julestop @simonk83 This should be fixed in the latest nightly. It did not make it into the release yesterday.

**Comment by vortexrap** [comment]
Please re-open as 0.2.0.182 - Jan 18 2017 Wednesday, January 18 2017 5:45pm build does not fix the incorrect grabbing.

Profile is:
![image](https://cloud.githubusercontent.com/assets/15331068/22131147/107ab330-de7f-11e6-8674-0dcfcf000c7b.png)

Search :
![image](https://cloud.githubusercontent.com/assets/15331068/22131118/eb024c8a-de7e-11e6-8045-dcefdd207f1c.png)

Copy it snatched:
![image](https://cloud.githubusercontent.com/assets/15331068/22131158/26634df6-de7f-11e6-9130-213ddb189fe8.png)

**Comment by julestop** [comment]
Seems to still not grab the best release... I'm currently checking in on it every day and seeing what it's doing and manually searching and selecting the best release if it grabbed the wrong one.

**Comment by galli-leo** [comment]
@julestop Do you find anything in the logs? I can't seem to reproduce that.

**Comment by julestop** [comment]
I'll turn on TRACE Log and run a test.

**Comment by julestop** [comment]
Alrighty - Here we go... I just looked over the DEBUG log because... well, the TRACE log is intense!

Here is a screenshot of the manual search:
![image](https://cloud.githubusercontent.com/assets/1585230/22267618/7c728de8-e252-11e6-8f14-cdd95ffb8460.png)
I searched the log for the first hit, and I put what I found in the paste log, as well as the decision maker... I'm not clear why it picks the 720P release.

Here is the log:

http://pastebin.com/h9V11R1a

**Comment by julestop** [comment]
Line 48 of the log shows when it downloads the 720P version.
However, higher up in the log (I deleted the processing of other releases) on Line 19, you can see that it accepts the 1080P version as a valid release.

**Comment by galli-leo** [comment]
@julestop When doing the manual search, what does the downloaded 720p show as rejection?
Also could you post the log of the specifications for that release?

**Comment by julestop** [comment]
So, here is some more info... looks like the one it picked is simply the very first release it found that it accepted... not necessarily the best quality, just meets the minimum requirements:
http://pastebin.com/iN4zn5df

Also, I think the first two lines of that log is the search specifications... not sure at all.
Below are some pictures to give more info:

![screen shot 2017-01-24 at 5 03 46 pm](https://cloud.githubusercontent.com/assets/1585230/22268954/7384723c-e257-11e6-9fba-d5c3dc598948.png)
![screen shot 2017-01-24 at 5 05 56 pm](https://cloud.githubusercontent.com/assets/1585230/22268957/75bd7f94-e257-11e6-8451-039596ffebee.png)
![screen shot 2017-01-24 at 5 06 14 pm](https://cloud.githubusercontent.com/assets/1585230/22268958/7770f956-e257-11e6-90bc-b42fa6f79703.png)

**Comment by mow4cash** [comment]
I had it grab the correct quality but ignore the max size limit.

**Comment by galli-leo** [comment]
@julestop This should be fixed in the latest nightly. Somehow I forgot to change the old Series prioritization call to the new movie one.
