### ISSUE TITLE
Missing movie posters

### ISSUE THREAD

**Issue by theebanka** [Radarr/Radarr#341]
As a test I added 10 or so movies to Radarr... some in theatres, some not even in theatres, and other that have been previously released and are available for download.

Out of all of these movies added only 1 has a corresponding poster. All of them have the correct background image when viewing the specific movie page but only the one was able to display a poster. I have refreshed individual movies as well as all of them at once (from the home page) without any luck.

If I am just missing something silly let me know and I can close this... if you need any more info or pictures let me know and I can do my best to get what you need

**Comment by Benni-chan** [comment]
same for me.
it seems, so far radarr only downloads the poster, when the movie was added and sometimes an error occurs. deleting the movie and adding it again helped. (sometimes had to repeat this multiple times)

radarr should reload the poster, when a movie is refreshed.

**Comment by galli-leo** [comment]
Can you check the MediaCover folder in the AppData directory?

**Comment by Benni-chan** [comment]
there are a few empty folders (get messages in the logs about that):

>MediaCoverMapper	File /config/MediaCover/236/poster.jpg not found

And there are folders with corrupted jpg files (can't open them). Even if I delete those, they are not replaced when updating the movie.

There are error messages in the logs when updating a movie:

>EventAggregator	ExtraService failed while processing [MediaCoversUpdatedEvent]: Object reference not set to an instance of an object

**Comment by theebanka** [comment]
@galli-leo Where would I go about finding that folder on the macOS compiled app version?

**Comment by theebanka** [comment]
@galli-leo I am seeing similar things as Benni posted above. Within the folder there are multiple versions of each Banner photo but all of the folders except one (same one that shows poster in Radarr) have Poster files that wont open and I would assume are corrupt

**Comment by simonk83** [comment]
Same, same behaviour here.  There's always one super low res banner file as well :D

**Comment by galli-leo** [comment]
@Benni-chan @theebanka @simonk83 The newest nightly version (0.2.0.187) should fix your issues. Can you try that one?

**Comment by simonk83** [comment]
Sure

**Comment by Benni-chan** [comment]
seems to work now. I had to manually delete the corrupted jpeg files and then after a refresh of all movies, the posters were downloaded.

**Comment by theebanka** [comment]
Wait did I miss something... did the release for tonight actually drop? I am not seeing it

**Comment by galli-leo** [comment]
@theebanka there is a fix on the nightly branch. However, it does not seem to fix it :/

**Comment by galli-leo** [comment]
@theebanka @Benni-chan @simonk83 The latest release of Radarr should fix this issue. Can you try and install that? (You may have to delete the corrupt poster files)

**Comment by Benni-chan** [comment]
seems to work now.
added a few movies and the poster was downloaded correctly...

there is still an error in the log:

>17-1-21 14:11:41.1|Error|EventAggregator|ExtraService failed while processing [MediaCoversUpdatedEvent]
>
>[v0.2.0.198] System.NullReferenceException: Object reference not set to an instance of an object
  at NzbDrone.Core.Extras.ExtraService.Handle (NzbDrone.Core.MediaCover.MediaCoversUpdatedEvent message) <0x42335c20 + 0x00030> in <filename unknown>:0 
  at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent] (NzbDrone.Core.Messaging.Events.TEvent event) [0x000c3] in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:56

**Comment by galli-leo** [comment]
@Benni-chan Good to hear. Yeah, those errors are unrelated and artifacts of Sonarr.

**Comment by theebanka** [comment]
@galli-Leo outside of waiting for the next release to drop in the release section how can I find this fix to test it? Feel like such an idiot right now haha

**Comment by galli-leo** [comment]
@theebanka The current release (.196) should contain the fix.

**Comment by theebanka** [comment]
Oh god okay I will delete some of these corrupt files in a few and give it a shot! Thank you!

**Comment by theebanka** [comment]
@galli-leo Okay so i removed corrupted files and the latest release fixed the posters for those!

since that worked so well I decided to add in a larger chunk of my library (another 80+ movies) and despite being on the most recent version some corrupted posters were still downloaded... Do i need to go back through and manually delete all corrupted files or will "Updating Library" eventually catch them?

**Comment by theebanka** [comment]
Just saw there was another update... let me install that and see if the issue persists
