### ISSUE TITLE
Radarr using "Obfuscated" as release group name

### ISSUE THREAD

**Issue by corwinx** [Radarr/Radarr#3685]
Running v0.2.0.1358

Resurrecting issue #3262 which was stale / closed due to inactivity...

Radarr seems to still be using "Obfuscated" as the release group name. Example:

Source Title:
Godzilla.King.Of.The.Monsters.2019.1080p.WEB-DL.H.264.AC3-EVO-Obfuscated

Movie Naming Format:
{Movie Title} ({Release Year}) - {[EDITION TAGS]}{[QUALITY FULL]}{[MEDIAINFO AUDIOCODEC}{ MEDIAINFO AUDIOCHANNELS]}{[MEDIAINFO VIDEOCODEC]}{-RELEASE GROUP}

Expected Result:
Godzilla King of the Monsters (2019) - [WEBDL-1080P][AC3 5.1][H264]-EVO.mkv

Actual Result:
Godzilla King of the Monsters (2019) - [WEBDL-1080P][AC3 5.1][H264]-OBFUSCATED.mkv

This may be happening with the word "SCRAMBLED" as well

**Comment by no84** [comment]
I see the same problem.
About 30 releases now have the name "obfuscated" as release group. I use the same naming scheme as the user abowe.

**Comment by jasonla** [comment]
I'm also seeing the same problem. The meta data is correctly picking up that the release group is DRONES, but when renaming, it uses Obfuscated.

**Comment by fryfrog** [comment]
I *swear* there is a whitelist that handles `-xpost` and `-Obfuscated`. And I swear it has been around for *ages* too. :/

**Comment by fryfrog** [comment]
Yeah, it should already be handled. Can you turn logging up to trace and repeat it? Capture a big chunk of the context around queuing up and import. It'll be big, so [pastebin](https://paste.ubuntu.com/) it. :)

https://github.com/Radarr/Radarr/blob/5291f42905c15493dca3f7a44331eecf4d3f7b0b/src/NzbDrone.Core/Parser/Parser.cs#L115

**Comment by corwinx** [comment]
https://paste.ubuntu.com/p/x7fCkpMvn3/

Release: 
Anna.2019.V2.1080p.WEB-DL.H.264.AC3-EVO-Obfuscated

Expected Result:
Anna (2019) - [WEBDL-1080P][AC3 5.1][H264]-EVO.mkv

Actual Result:
Anna (2019) - [WEBDL-1080P][AC3 5.1][H264]-OBFUSCATED.mkv

I'm not seeing a lot in that trace file besides this line, which doesn't show any regex before it:
19-9-10 21:21:07.7|Info|MovieService|Linking [Anna (2019) - [WEBDL-1080P][AC3 5.1][H264]-OBFUSCATED.mkv] > [[Anna (2019)][tt7456310, 484641]]

**Comment by kgulmer** [comment]
Issue present for me in 0.2.0.1358.

Seems that there may have been a potential solution that may have been sidelined before it was resolved:
[https://github.com/Radarr/Radarr/issues/3262#issuecomment-459931587](url)

> @galli-leo the issue here is that on import it Radarr uses `simpleReleaseTitle` to try and parse the Release Group instead of using the release title. Because `simpleReleaseTitle` is the `release title / filename` ex. `Jurassic.World.2015.720p.BluRay.x265-NtB-Obfuscated QaQV3WK3z2mUI0YY19xcP1VKqN` the regex fails to clean as it looks for keyword (Obfuscated/pre/et..) at end of string.
> 
> To fix we likely need to use the original release title and not the simple release title for parsing of release group. Agree?
> 
> Or we modify the regex to not require end of string behind the cleaned word. Looks like this got introduced in the custom formats PR

The thread for the other issue is closed so I'll reference it here.

**Comment by corwinx** [comment]
This is still happening:

Ready Or Not 2019 720p BluRay DD5 1 X264-IFT-Obfuscated
became
Ready or Not (2019) - [BLURAY-720P][AC3 5.1][X264]-OBFUSCATED

**Comment by fryfrog** [comment]
@Qstick, any changes to this in v2?

**Comment by Qstick** [comment]
Does this occur in v2 at all, can you confirm?

**Comment by fryfrog** [comment]
I'm not even sure I've observed it in v0.2. @corwinx, do you want to setup a v2 *test* instance? I don't quite suggest flipping over and mainlining it yet. :/

**Comment by corwinx** [comment]
Sure, I can try that

**Comment by no84** [comment]
I'm on 0.2.0.1453

**Name:**
Movie1.2019.720p.BluRay.x264-DON-Obfuscated
**Source:**
/mnt/temp/radarr/Movie1.2019.720p.BluRay.x264-DON-Obfuscated/1876865764565465654.mkv
**Imported To:**
/movies/Movie1 (2019)/Movie1 (2019) - [BLURAY-720P][AC3 5.1][X264]-OBFUSCATED.mkv

**Name:**
Movie2.2019.1080p.WEBRip.x264.AC3-RPG-Obfuscated
**Source:**
/mnt/temp/radarr/Movie2.2019.1080p.WEBRip.x264.AC3-RPG-Obfuscated/cb1234567846443543.mkv
**Imported To:**
/movies/Movie2 (2019)/Movie2 (2019) - [WEBDL-1080P][AC3 5.1][X264]-OBFUSCATED.mkv

--

**Standard Movie Format**
{Movie Title} ({Release Year}) - {[EDITION TAGS]}{[QUALITY FULL]}{[MEDIAINFO AUDIOCODEC}{ MEDIAINFO AUDIOCHANNELS]}{[MEDIAINFO VIDEOCODEC]}{-RELEASE GROUP}

**Movie Folder Format**
{Movie Title} ({Release Year})

**Comment by Rubeast** [comment]
I'm also interested in a solution to exclude "Obfuscated" from the release names. It wouldn't be that bad if it also included the release group when renaming, but it simply replaces the release group.

**Comment by Qstick** [comment]
We are talking about Aphrodite branch, Radarr v3, does this issue occur in V3 alpha builds?

**Comment by Rubeast** [comment]
For the people that use NZBget, I have found a possible solution.
I'ts a script for NZBget that will remove these kind of names.
I haven't tested it yet, but looks promising.
https://github.com/TRaSH-/Tutorials-FAQ/tree/master/NZBGet/scripts/Clean

**Comment by Qstick** [comment]
From my tests last night, this is fixed in v3

**Comment by Rubeast** [comment]
> From my tests last night, this is fixed in v3

Is this version already available for Radarr?
