### ISSUE TITLE
Movie "Flu" is corrupt

### ISSUE THREAD

**Issue by Viceman256** [Radarr/Radarr#4117]
**Describe the bug**
The movie Flu (2013) says it exists when I search for it, but it's not in my movie editor nor can I search for it. When I try to access the page using the "Already exists" button, I receive a 404 error. The end of the URL is: flu-200085

**To Reproduce**
1. Search for Flu 
2. Click on 'Flu'
3. 404 page

**Expected behavior**
To view the movie.

[**Screenshots**]
![flu](https://user-images.githubusercontent.com/47254767/73584253-57406100-4454-11ea-8e4b-348da78d0b49.JPG)
![flu2](https://user-images.githubusercontent.com/47254767/73584288-92429480-4454-11ea-8cd4-d28a0123414f.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.2.0.1450

**Debug Logs**
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/4141997/radarr.debug.txt)

**Comment by kSotin** [comment]
Actually it's related to #3972.

**Comment by Qstick** [comment]
Dupe and fixed in Aphrodite since we return the db object for existing items now, thus title slug isn’t built from new search result that’s in another language.

**Comment by kSotin** [comment]
@Qstick That means #3972 is fixed?

**Comment by Viceman256** [comment]
Sorry if I'm not following @Qstick, but the issue is still present for me on release: 0.2.0.1450.

**Comment by ta264** [comment]
Yeah it's fixed in the V3 unstable builds. v0.2 isn't really being worked on any more

**Comment by Viceman256** [comment]
Got it, thanks! Is V3 only available via Docker? I can't seem to find any Windows install info.

**Comment by Viceman256** [comment]
> 
> 
> Yeah it's fixed in the V3 unstable builds. v0.2 isn't really being worked on any more

@ta264

**Comment by Qstick** [comment]
There are binary builds for all os. Jump on discord for links

**Comment by SF4L** [comment]
Now works for me in 0.2.0.1480
