### ISSUE TITLE
V3: Not removing completed torrents after seeding ratio is met

### ISSUE THREAD

**Issue by arpitgupta** [Radarr/Radarr#4363]
After latest update i see that torrents that met the seeding limit set would get paused in download client and never get removed from it.

Movie is correctly linked after the download completed but i see no event called for remove the torrent from the download client.

Running:
```
Version
3.0.0.2878
Package Version
3.0.0.2878-ls5 by linuxserver.io
.NET Core
Yes
Docker
Yes
DB Migration
172
```
Recently had seen the same issue in Sonarr https://github.com/Sonarr/Sonarr/issues/3693. 

I am now running Radarr V3 with trace logs to see if i can generate more info.

**Comment by Qstick** [comment]
Thanks, I’ll pull the Sonarr fix

**Comment by arpitgupta** [comment]
Awesome. FYI i have not yet validated on my end the sonarr fix is working or not.

**Comment by Qstick** [comment]
Fixed 0f0afd62bbf4b4ea2287ae22baf96a98006fa91c

**Comment by arpitgupta** [comment]
I am still seeing this issue? Would it only be fixed for new content that started downloading after the fix was applied or should it apply to older/in progress downloads? fwiw people are reporting on the sonarr issue that they still are still seeing the issue with newer build.

**Comment by Qstick** [comment]
Probably going to have to wait for them to fix it proper

**Comment by arpitgupta** [comment]
Can we re open this issue or do we want to track that in a new bug?

**Comment by Qstick** [comment]
Fixed
