### ISSUE TITLE
Error in Radarr API when importing IMDB list

### ISSUE THREAD

**Issue by Morten14** [Radarr/Radarr#4863]
The Radarr API seems to incorrectly process some IMDB lists. My main watchlist can't be imported while there is no issue with my girlfriends list. 

Radarr is running via Docker
OS: DSM 6.2.3
Browser: Chrome
Version: 3.0.0.3396
Package Version: 3.0.0.3396-ls19 by linuxserver.io

Debug log:
2020-8-13 12:28:49.1|Debug|Api|[GET] /api/v3/health: 200.OK (12 ms)
2020-8-13 12:28:50.0|Debug|Api|[PUT] /api/v3/config/host: 202.Accepted (8027 ms)
2020-8-13 12:28:50.2|Debug|Api|[GET] /api/v3/health: 200.OK (3 ms)
2020-8-13 12:28:52.1|Debug|Api|[GET] /api/v3/exclusions: 200.OK (597 ms)
2020-8-13 12:28:52.3|Debug|Api|[GET] /api/v3/config/netimport: 200.OK (839 ms)
2020-8-13 12:28:52.3|Debug|Api|[GET] /api/v3/netimport: 200.OK (913 ms)
2020-8-13 12:28:52.5|Debug|RootFolderService|Generating list of unmapped folders
2020-8-13 12:28:53.7|Debug|RootFolderService|10 unmapped folders detected.
2020-8-13 12:28:53.8|Debug|Api|[GET] /api/v3/rootFolder: 200.OK (2344 ms)
2020-8-13 12:28:59.2|Debug|IMDbListImport|Downloading List https://radarrapi.servarr.com/v1/list/imdb/ls000533573
2020-8-13 12:29:05.3|Warn|IMDbListImport|Unable to connect to list

[v3.0.0.3396] NzbDrone.Core.NetImport.Exceptions.NetImportException: Radarr API call resulted in an unexpected StatusCode [InternalServerError]
   at NzbDrone.Core.NetImport.RadarrList2.RadarrList2Parser.PreProcess(NetImportResponse listResponse) in d:\a\1\s\src\NzbDrone.Core\NetImport\RadarrList2\RadarrList2Parser.cs:line 44
   at NzbDrone.Core.NetImport.RadarrList2.RadarrList2Parser.ParseResponse(NetImportResponse netMovieImporterResponse) in d:\a\1\s\src\NzbDrone.Core\NetImport\RadarrList2\RadarrList2Parser.cs:line 19
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.FetchPage(NetImportRequest request, IParseNetImportResponse parser) in d:\a\1\s\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 158
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.TestConnection() in d:\a\1\s\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 194

2020-8-13 12:29:05.6|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to list. Radarr API call resulted in an unexpected StatusCode [InternalServerError]
2020-8-13 12:29:05.6|Debug|Api|[POST] /api/v3/netimport/test: 400.BadRequest (6406 ms)
2020-8-13 12:29:12.9|Debug|Api|[GET] /api/v3/health: 200.OK (14 ms)
2020-8-13 12:29:13.1|Debug|Api|[GET] /api/v3/system/status: 200.OK (213 ms)
2020-8-13 12:29:13.4|Debug|Api|[GET] /api/v3/diskspace: 200.OK (488 ms)
2020-8-13 12:29:21.5|Debug|Api|[GET] /api/v3/log/file: 200.OK (20 ms)

**Comment by austinwbest** [comment]
I think @ta264 manages the lists. Ive also passed him a bug with my list throwing errors as well (except it is because mine is empty lol)

**Comment by Qstick** [comment]
Empty lists were fixed in a commit this AM. We'll look at what's blowing up server side on this case

**Comment by Morten14** [comment]
So I just made a new IMDB account and imported all the movies from the old watchlist to this new account. I still get the same error. I think the error may be related to some specific movie on IMDB.

**Comment by austinwbest** [comment]
You are gonna need to reproduce the issue and provide the logs from it

**Comment by ta264** [comment]
As I remember I could reproduce from the URL in the logs, I need to fix it server side. Not quite sure how yet...

**Comment by austinwbest** [comment]
Ah gotcha. Well not much I can do for that one lol

**Comment by Morten14** [comment]
Okay so the new list is working now, which is basically just a copy of the other list. 

When I export the lists from IMDb to .csv files, I notice one difference. Each seperate line in the bugged list ends with ",,". In the other list it just ends normally. I attached the two exported lists so you can see the difference. 

[lists.zip](https://github.com/Radarr/Radarr/files/5184858/lists.zip)

**Comment by Qstick** [comment]
Interesting, can you leave the old one up for testing for now?

**Comment by Qstick** [comment]
Got it fix PRd on metadata side for the cases that were returning status 500, looks like it was due to one or more items on the list returning error code from tmdb during the movie map. We'll just ignore the errors and still return movies with no error
