### ISSUE TITLE
Unable to find movie on indexer with special characters

### ISSUE THREAD

**Issue by gtalmor** [Radarr/Radarr#541]
My indexer doesn't allow searches with special characters (for example Mission: Impossible - Rogue Nation). Searching for the movie with ':' character manually on the indexer will return no results. Searching without it will result in a lot that also matches the profile requirement.

Examples:
"Mission: Impossible" -> no results. 
"Mission Impossible -> many results. 
"Impossible - Rogue" (checking is '-' isn't allowed as well) -> indexer will automatically omit the '-' sign and will search without it -> thus provides many results. 

Need to opt Radarr to omit special characters when searching the indexer.

**Comment by onedr0p** [comment]
Should be fixed in next update

**Comment by gtalmor** [comment]
Unfortunately this isn't resolved.
The inexer I'm using is omgwtfnzbs.me.
