### ISSUE TITLE
Bug Queue in other profile languages

### ISSUE THREAD

**Issue by Firemad03** [Radarr/Radarr#555]
Hi,

In my Radarr that is using the French profile only the movies that are downloading and waiting in sabnzbd to download isn't showing up in the queue for some reasons. I can see them in history only.

In my other Radarr that is using the English profile everything is fine. 

I think it's because of something to do with the title language ? or something link to the translation ? I don't know.

![image](https://cloud.githubusercontent.com/assets/24792889/22492984/c351708c-e7fa-11e6-9bd5-32eb26b152e8.png)

![image](https://cloud.githubusercontent.com/assets/24792889/22492988/d15a3fa6-e7fa-11e6-97e4-f37f88ef7b70.png)

Note: All the cloud one are waiting to download in sabnzbd

Thanks

**Comment by Firemad03** [comment]
Build: 0.2.0.274

**Comment by onedr0p** [comment]
Exactly, radarr cannot match the release title to any movie. I'll look at ways to improve this but it doesn't look easy.

**Comment by galli-leo** [comment]
@Firemad03 Can you verify that the issue still exists with the latest version of Radarr?

**Comment by Firemad03** [comment]
I will. I'm reinstalling my french radarr server. I will test it out when it's ready.

**Comment by Firemad03** [comment]
I confirm that it's fixed.

**Comment by Firemad03** [comment]
In case you want screenshot:

![image](https://cloud.githubusercontent.com/assets/24792889/24985961/8031141c-1fc5-11e7-8418-56ae54897411.png)

![image](https://cloud.githubusercontent.com/assets/24792889/24985955/77b071f2-1fc5-11e7-967c-0bbb44135131.png)

French title goes to history instead of queue.

**Comment by Firemad03** [comment]
This issue cause another problem. If I do a multiple search all...well you guess that if I press 3 times it will find and send to sabnzbd 3 times the same movies... 👎 not all of them but the one in the history tab.

**Comment by Firemad03** [comment]
Also because they don't show up in the queue I can't cancel / delete an import that failed. Maybe I can check every movies but it isn't very convenient like the queue tabs.

**Comment by galli-leo** [comment]
@Firemad03 Pretty sure that I fixed this now. Can you try the latest nightly and report back?

**Comment by Firemad03** [comment]
Well I think it's better because I saw more now in the queue but the problem is still there.

![image](https://cloud.githubusercontent.com/assets/24792889/25064885/6c076720-21d2-11e7-9c6e-b06ecd7d4388.png)

![image](https://cloud.githubusercontent.com/assets/24792889/25064887/789da12a-21d2-11e7-9014-55d8d1a473d3.png)

**Comment by Firemad03** [comment]
I'm grabbing more movies now in French :) with this fix.

**Comment by Firemad03** [comment]
In the English Radarr I got a new problem with this fix that I never had before:

![image](https://cloud.githubusercontent.com/assets/24792889/25065002/aee7fd78-21d4-11e7-8dd8-93076f534d48.png)

![image](https://cloud.githubusercontent.com/assets/24792889/25065006/bc8a01c4-21d4-11e7-80c9-55964a0ed7c1.png)

Same problems I think.

**Comment by Firemad03** [comment]
French Radar Updated screenshot:

![image](https://cloud.githubusercontent.com/assets/24792889/25065037/0ed47900-21d5-11e7-9d9f-721d2232c89c.png)


![image](https://cloud.githubusercontent.com/assets/24792889/25065035/057a120c-21d5-11e7-9001-722d541527fd.png)

**Comment by Firemad03** [comment]
Updated English Radarr:

![image](https://cloud.githubusercontent.com/assets/24792889/25065111/f23b6ca2-21d6-11e7-9987-6e0c64eea6e8.png)

![image](https://cloud.githubusercontent.com/assets/24792889/25065115/fd89cad6-21d6-11e7-8e1e-429c14ced523.png)

**Comment by Firemad03** [comment]
I think it's related to the task that check sabnzbd for the movie title if the movie is downloaded or not.

**Comment by galli-leo** [comment]
@Firemad03 Can you check that now all movies show up? It should be fixed due to #1390 being fixed.

**Comment by Firemad03** [comment]
@galli-leo Off course when I will see the update I will upgrade and I will check it out.

**Comment by Firemad03** [comment]
@galli-leo Did  you increment the build or it's the same build number ? because when I do the task update I don't see a new update yet.

**Comment by galli-leo** [comment]
@Firemad03 Seems like the tests failed and so the nightly did not activate. Should come up in a few minutes.

**Comment by Firemad03** [comment]
@galli-leo Now English Radarr is back to normal with the new build :) French one same problems.
I want to point out that it seem a lot more better vs before the title fix patch.

![image](https://cloud.githubusercontent.com/assets/24792889/25068104/1ec87f58-2227-11e7-8726-6bcc115b7cbc.png)

![image](https://cloud.githubusercontent.com/assets/24792889/25068109/3402d986-2227-11e7-9a1e-852f9307a3af.png)

300 isn't there and Beast of No Nation in the queue.

**Comment by Firemad03** [comment]
Btw Star Wars appeared later in the history don't worry. Only 300 and Beats of no nation didn't appear and I waited 5 minutes just to be sure.

**Comment by Firemad03** [comment]
Nevermind beast of no nation. Seriously I got everything (after 30 minutes of testing) but only 300 didn't show up. Maybe the comma broke something ? We got lot of comma in French for the title.

**Comment by Firemad03** [comment]
Update:


![image](https://cloud.githubusercontent.com/assets/24792889/25068162/b29bcf5e-2228-11e7-9ed6-7a6163d47142.png)


![image](https://cloud.githubusercontent.com/assets/24792889/25068161/a24096f8-2228-11e7-9a88-f08af9bb3973.png)

Only 300 got a problem :)

**Comment by galli-leo** [comment]
@Firemad03 Do you see anything in the logs? Cannot find a 300 french release, so kinda difficult to reproduce.

**Comment by galli-leo** [comment]
Or can you give me the full title of the release?

**Comment by Firemad03** [comment]
Sorry don't see anything in the logs. It's always downloading it and I don't have any errors.

300.2006.MULTi.TRUEFRENCH.1080p.BluRay.x264-AiRLiNE
or this one:
300.2006.TRUEFRENCH.720p.BluRay.x264-AiRLiNE

**Comment by Firemad03** [comment]
Hi,

I know you are working for other stuff but I wanted to make an update with the latest build and it's worst ;)

![image](https://user-images.githubusercontent.com/24792889/28240181-5b929904-694a-11e7-8b37-4ea45a929a13.png)

Now the queue is always empty...

![image](https://user-images.githubusercontent.com/24792889/28240185-668d11fe-694a-11e7-8560-eb3b23584db6.png)

![image](https://user-images.githubusercontent.com/24792889/28240188-75780502-694a-11e7-8630-1cbeab9a6f57.png)

**Comment by Firemad03** [comment]
I tested on latest build and everything is working fine! I think it's safe to close this issue if you want to.

![image](https://user-images.githubusercontent.com/24792889/28240221-2e600ca4-694b-11e7-8426-84800df374ff.png)
