### ISSUE TITLE
Deleting files not working

### ISSUE THREAD

**Issue by danpowell88** [Radarr/Radarr#694]
I'm using the delete functionality and trying to delete files. It correctly identifies that there is 1 file to delete and removes the data from the library but the file exists

```
Version: 0.2.0.299
AppData directory: C:\ProgramData\Radarr
Startup directory: C:\Program Files (x86)\Radarr
```

```
17-2-10 19:11:56.5|Trace|Http|Req: 6018 [DELETE] /api/movie/982??deleteFiles=true
17-2-10 19:11:56.5|Trace|EventAggregator|Publishing MovieDeletedEvent
17-2-10 19:11:56.5|Trace|EventAggregator|MovieDeletedEvent -> MovieModule
17-2-10 19:11:56.6|Trace|EventAggregator|MovieDeletedEvent <- MovieModule
17-2-10 19:11:56.6|Trace|EventAggregator|MovieDeletedEvent -> CalendarModule
17-2-10 19:11:56.6|Trace|EventAggregator|MovieDeletedEvent <- CalendarModule
17-2-10 19:11:56.6|Trace|Http|Res: 6018 [DELETE] /api/movie/982??deleteFiles=true: 200.OK (93 ms)
17-2-10 19:11:56.6|Trace|EventAggregator|MovieDeletedEvent ~> MediaFileService
17-2-10 19:11:56.6|Trace|EventAggregator|MovieDeletedEvent ~> BlacklistService
17-2-10 19:11:56.7|Trace|EventAggregator|MovieDeletedEvent <~ BlacklistService
17-2-10 19:11:56.6|Trace|EventAggregator|MovieDeletedEvent <~ MediaFileService
17-2-10 19:11:56.6|Debug|Api|[DELETE] /api/movie/982??deleteFiles=true: 200.OK (93 ms)
```
Tried to take a look and it looks like MediaFileService isn't actually deleting the files just the sql data
```
public void HandleAsync(MovieDeletedEvent message)
		{
			if (message.DeleteFiles == true)
			{
				var files = GetFilesByMovie(message.Movie.Id);
				_movieFileRepository.DeleteMany(files);
			}
		}
```

However looking at Sonarr it has the same code so I'm not sure what is going on.

The directory is a smb share using the \\\servername format, I don't this is related though as radarr is able to move newly downloaded files etc without issue.

**Comment by danpowell88** [comment]
If someone can point in the right direction I might be able to submit a pull request

**Comment by geogolem** [comment]
i noticed some issues with this while implementing another feature... im not sure what @galli-leo  wanted me to do about it. You can take a look at my stuff here. I do have some comments that show basically how to delete the files in the code; however, i dont think its in the right place as it should be in a generic place...... also the folder wasn't being deleted with my code.. not sure if i missed something else.:

https://github.com/Radarr/Radarr/pull/656

**Comment by greatvc** [comment]
i confirm, this did not work for me either when i try to delete a movie

**Comment by dan-the-man-nz** [comment]
I also have this issue on Windows 10 -  2.0.0.4578

Delete Movie with 'Delete All files' set to Yes, Will not Delete Movie Directory / Video File

there is nothing in the debug show showing any kind of action or error regarding the delete process

**Comment by o-mobile** [comment]
Same here. Deletes from database but folder and files remain on disk.

**Comment by mimminito** [comment]
Same here. File deletes from DB but folder and files remain on disk.

**Comment by hadim** [comment]
Same here.

**Comment by thejacer87** [comment]
ya i just had it delete the video file, but it leaves the folder (my movies are store Name_of_Movie(2017)/Name_of_Movie(2017).mp4) and the .srt files

**Comment by ginjohn5snaps** [comment]
Same here with Radarr on Synology. When checking "Delete all files" - nothing actually deletes, neither movie files, folder or anything else.

**Comment by Beardedwan** [comment]
same here, NFS mounted directories and files remain after delete

**Comment by frankkorrell** [comment]
same here.

**Comment by frankkorrell** [comment]
same here.

**Comment by frankfnord** [comment]
same here

**Comment by simkin** [comment]
Same here on Latest Debian. Radar user is owner of folders/files but none are deleted

**Comment by galli-leo** [comment]
Yeah, I know, code for deleting files is not implemented yet.

**Comment by raspdealer** [comment]
Same on Raspberry Pi just to let you know :)

**Comment by milika** [comment]
any ETA on this. Without deleting files/folder it is really cumbersome to organize...
Delete here, and then there, folder checking manually, well you know...

Thanks

**Comment by hartleigh** [comment]
Subscribing to thread. If the function doesn't exist then perhaps the option should be removed from UI. It's just causing unnecessary confusion.

**Comment by Fiala06** [comment]
Ok glad it wasn't just me. Need to start making room on my drive, pain essentially deleting stuff twice.  :(

**Comment by kameron-1590** [comment]
is there any ETA on this fix?

**Comment by octophetus** [comment]
Cool, thought I was going crazy.

**Comment by AlexWalder** [comment]
Has there been any progress on this front? I've been meaning to use Radarr to clean up my library but I'll just have to settle with going through and deleting files manually along with deleting the DB entry in radarr

**Comment by Korgun** [comment]
Previously I was deleting the movie in radarr first, then going to the Movies directory to find the movie and delete it there.  Seems it's not exactly necessary - I recently noticed that in the main page of a movie if you click the red x on the file line - that **does** delete the file.

So now if I want to delete a movie,  I click that red x to delete the physical file, then go to Edit Movie > Delete - at least it's on the same page, within Radarr and only one extra click

**Comment by AlexWalder** [comment]
@Korgun you legend, thanks heaps, I didn't even think of that. Makes it so much easier now to clean up my library

**Comment by ginjohn5snaps** [comment]
@Korgun - Not all heroes wear capes!

**Comment by octophetus** [comment]
Well, it isn't really a great solution because the folder still stays as well as any extras inside (subs, etc). It only deletes the actual movie file itself. Still need to keep it clean quite manually.

**Comment by galli-leo** [comment]
@octophetus Did you test the nightly? It should delete the whole folder.

**Comment by octophetus** [comment]
The nightly? I selected the red x to delete movie file from disk. Then I went to edit movie, delete, and toggled on 'delete all files'. The folder and other other files within it remained. Only the movie was deleted. It just goes back to the 'delete all files' mechanism not working as everyone in this thread is discussing. It doesn't delete the movie or any aspect of the directory itself. The red x "delete movie file from disk" will do what it says it does and only that.  @Korgun 's suggestion is good for saving space but not if you're trying to maintain a clean library.

**Comment by galli-leo** [comment]
@octophetus Yes, it fixed the issue explained here in the nightly. Now when you delete a movie and select delete files, it will delete the folder as well.

Only deleting the movie file as outlined by @Korgun above, shouldn't delete the folder. Since you might want to manually delete the old file (e.g. bad download), but still keep the folder.

**Comment by octophetus** [comment]
Ohhhh I wasn't aware it was fixed there. I thought this was closed on account of @korgun's suggestion lol. I was like..uhhhh wait a minute!!!! I have not tested it but I'm excited for its release. Thanks.

**Comment by steve1977** [comment]
Unfortunately, I am still facing the same or a related issue. When the quality get upgraded (e.g., 1080p becomes available and I had 720p before), the "old" movie file gets deleted. However, the "old" movie folder still remains. So, I now have two movie folder (movie [720p] and movie [1080p]).

Has this fix not been merged yet or is this a separate issue?

**Comment by galli-leo** [comment]
@steve1977 That's a separate issue. Movie folders with more than name and year are still in alpha. Folder was probably not deleted since there were still some leftover files (e.g. subtitles or artwork)

**Comment by steve1977** [comment]
Got it. Great to see this being worked on. No leftover. A completely empty folder. Having said this, I will soon start real upgrading activity and then indeed will also suffer from leftover files.

**Comment by jeanpoelie** [comment]
Is there a way to do this the opposite way? delete all movies that are not in the radarr db?
