### ISSUE TITLE
Deleted Movie Folder/Video file still shows as available in the GUI

### ISSUE THREAD

**Issue by dan-the-man-nz** [Radarr/Radarr#712]
0.2.0.324 on Win10

Delete a Movie manually (via explorer) including its directory folder.
In Radarr, for that movie, 'update movie info and scan disk'
Debug Log shows the movie folder no longer exists - correct
However the radarr GUI still shows the movie as been available. - incorrect

![image](https://cloud.githubusercontent.com/assets/906806/22856761/199aeeb8-f0fd-11e6-8106-c620f7fee9a8.png)

**Comment by fedoranimus** [comment]
I couldn't reproduce this exact issue, but made some changes to ensure that the Download status and the Files tabs respond to the 'Update Movie' button.

**Comment by fedoranimus** [comment]
We need to account for removing the folder as well.

**Comment by galli-leo** [comment]
@dan-the-man-nz Can you try to reproduce this in the latest version? I think this is fixed.

**Comment by dan-the-man-nz** [comment]
hi

its not fixed / working correctly

*deleted H:\Movies\Moviename (2016) directory
*went to the movie in radarr, did a 'update movie info and scan disk'
*seemed to work, under Files, the entry disappeared, and it said it was missing
*then i manually ran the task 'refresh movie' - now the entry under file is back  (yet the file and directory no longer exists), but it still says missing.

![image](https://cloud.githubusercontent.com/assets/906806/24977843/a83579fa-2022-11e7-8b9e-bc46b3ec7ca8.png)

0.2.0.610 nightly on windows 10

**Comment by galli-leo** [comment]
@dan-the-man-nz Can you try refreshing your browser window with force clearing the cache (IIRC shift-f5 on chrome) The file tab is often not so good in updating. When the movie is shown as missing, that should be the important part.

**Comment by dan-the-man-nz** [comment]
yes you are right, there is a caching issue with with Files tab...
