### ISSUE TITLE
import fails because video has a runtime of 0

### ISSUE THREAD

**Issue by thejacer87** [Radarr/Radarr#764]
**Description:**

Just importing my files and one movie wouldn't work.

**Radarr Version:**
0.2.0.299
**Logs:**
[/path_to_file/Movies/The_Hateful_Eight(2015)/The_Hateful_Eight(2015).mp4] has a runtime of 0, is it a valid video file?

**Comment by onedr0p** [comment]
Does that movie actually play? Maybe it's corrupt.

**Comment by thejacer87** [comment]
yes, emby recognised it and played it just fine...

**Comment by onedr0p** [comment]
We updated MediaInfo in recent builds are you on the latest pre-release?

**Comment by onedr0p** [comment]
For example I run:

`mediainfo /wash/Movies/Films/10\ Cloverfield\ Lane\ \(2016\)/10\ Cloverfield\ Lane\ \(2016\).mkv | grep Duration`

**Comment by thejacer87** [comment]
havent tried since that first day... i will take another look

**Comment by thejacer87** [comment]
`mediainfo WAC-47/Movies/The_Hateful_Eight\(2015\)/The_Hateful_Eight\(2015\).mp4 | grep -i Druartion`

nada, heres the full info

` mediainfo WAC-47/Movies/The_Hateful_Eight\(2015\)/The_Hateful_Eight\(2015\).mp4 
General
Complete name                            : WAC-47/Movies/The_Hateful_Eight(2015)/The_Hateful_Eight(2015).mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom
File size                                : 2.54 GiB
Duration                                 : 2h 47mn
Overall bit rate                         : 2 168 Kbps
Writing application                      : Lavf57.23.100

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 2h 47mn
Bit rate                                 : 2 050 Kbps
Width                                    : 1 920 pixels
Height                                   : 688 pixels
Display aspect ratio                     : 2.791
Frame rate mode                          : Constant
Frame rate                               : 23.976 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.065
Stream size                              : 2.40 GiB (95%)
Writing library                          : x264 core 148
Encoding settings                        : cabac=1 / ref=4 / deblock=1:-1:-1 / analyse=0x3:0x133 / me=umh / subme=9 / psy=1 / psy_rd=1.00:0.15 / mixed_ref=1 / me_range=24 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=0 / chroma_qp_offset=-3 / threads=12 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=60 / rc=2pass / mbtree=1 / bitrate=2050 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / vbv_maxrate=31250 / vbv_bufsize=31250 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=1:1.00

Audio
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : 40
Duration                                 : 2h 47mn
Bit rate mode                            : Constant
Bit rate                                 : 111 Kbps
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Compression mode                         : Lossy
Delay relative to video                  : -1s 166ms
Stream size                              : 133 MiB (5%)
`

**Comment by onedr0p** [comment]
Are you on the latest pre-release of Radarr?

**Comment by thejacer87** [comment]
sorry just a heads up, i updated my comment as you were probably responding... it does give a duration. but i still get the error message in the log

im on this version: 
![image](https://cloud.githubusercontent.com/assets/6412919/23313122/400039dc-fa71-11e6-849d-f6b9760b685f.png)

**Comment by onedr0p** [comment]
```
$ mediainfo --version
MediaInfo Command line, 
MediaInfoLib - v0.7.92.1
```

What is your mediainfo version?

**Comment by thejacer87** [comment]
```
mediainfo --version
MediaInfo Command line, 
MediaInfoLib - v0.7.58
```

**Comment by onedr0p** [comment]
This is the prob: your movie shows: `Duration : 2h 47mn` when it should say `Duration : 2h 47 min`

**Comment by thejacer87** [comment]
ill take a look when i get home, im running this server on OMV which uses debian 7 i believe. So this would just be whats in the repos. I should probably look into Docker (never used it). I don't know anything about it, but i thought you could install anything on each instance and not affect others stuff on the system. seems like everyone is using to compartmentalise everything

**Comment by JeromeMartinez** [comment]
> This is the prob: your movie shows: Duration : 2h 47mn when it should say Duration : 2h 47 min

I suggest you use "raw" values instead of the display intended for humans.
If you use the command line, you may use `mediainfo --Language=raw -f --ReadByHuman=0 FileName`, compatibility is kept with raw values.

**Comment by thejacer87** [comment]
ya seems like a human readable is unnecessary. also wonder why every other movie was fine except this one

**Comment by wifiuk** [comment]
so how do we import movies that get this error?

**Comment by galli-leo** [comment]
Wanted -> Manual Import

**Comment by Rick7C2** [comment]
I've tried Manual Import but they still fail to import.

Is there a way to disable mediainfo check when rescaning disk?

**Comment by galli-leo** [comment]
In that case not. Usually a runtime of 0 means a broken file though, so there's that. You can also manually move those files into your folder and rescan disk.

**Comment by Rick7C2** [comment]
They were already in the correct folders. Radarr just detected the movies as samples so it would not mark them as downloaded.

I got it fixed now though. I made a script to scan the folders for video files then edit the movie in radar db to hasFile = true and added the file paths.

**Comment by MattTwinkleToes** [comment]
I am still getting lots of .iso´s being downloaded and then not importing as radarr thinks the runtime is zero.

I would be happy to just block all .iso´s but i cant see where i should do that

**Comment by onedr0p** [comment]
@MattTwinkleToes It's impossible for Radarr to know the extension of the movie file at the time it goes to grab a movie. I would say get better indexers, and restrict release groups that are common offenders.

**Comment by MattTwinkleToes** [comment]
I am a life member of several reputable indexers, this is not the issues.
Releases are rated on my indexers.  The problem seems to be that I have my
quality settings, set high so that I can get the highest bit rate releases
on offer.

I don´t know why we can´t have a simple extension exclusion list like we
have in SAB?

I have set iso  in ¨Must not contain¨ for now and we will see if this helps.

If i block these extensions in the downloader, radarr still send jobs to it
which results in lots of failed jobs.

--Matt
I am in the process of migrating my personal email to a new provider.

My new address is matt.fletcher@protonmail.com

**Comment by galli-leo** [comment]
We will have better matching for isos and other full disk formats with Custom Formats. Then you just have to exclude BR-Disk from your quality profile.

**Comment by MattTwinkleToes** [comment]
BR-Disk is already excluded from my profile.  A lot of people I ask about this seem confused as to why I am moaning about this but I can´t see any obvious reason why I am getting this.

It´s not that I hate ISO images it is that they fill my hard drive.  Because radarr sends them to the client, they get downloaded and then radarr is unable to do anything with them, it just leaves them in the download directory where they build up until my disk is full which then makes everything stop working.

I am then faced with the task of manually re-wrapping them into mkv which although easy to do, is a manual intervention that don´t want to have to deal with.

I am thinking about writing a python script to mount and rewrap these as they appear but it´s a bit of a ¨band aid¨ solution that probably is not the best way forward.

**Comment by galli-leo** [comment]
@MattTwinkleToes Completely understand. Though currently BR-Disk is not really helpful, it will be in the future.

**Comment by galli-leo** [comment]
Could anyone supply me with a file that does this in Radarr?

**Comment by MattTwinkleToes** [comment]
A media file?

**Comment by MattTwinkleToes** [comment]
if you want me to reproduce it in full for you I probably could to help you out?

**Comment by galli-leo** [comment]
@MattTwinkleToes Sorry, should have been more specific, I meant a file that Radarr thinks has a runtime of 0, but mediainfo shows as having a valid runtime.

**Comment by MattTwinkleToes** [comment]
Sure, I used to have that error a lot but it was always down to broken media files (no idea why, it was not a radarr issue) or ISO´s.  I don´t think I can help you this time as everything that happened to me had a reasonable explanation.

**Comment by tml** [comment]
> @MattTwinkleToes Sorry, should have been more specific, I meant a file that Radarr thinks has a runtime of 0, but mediainfo shows as having a valid runtime.

@galli-leo Check your keybase chat.

**Comment by bverkron** [comment]
I'm running into this issue currently. mediainfo shows correct duration. File plays in every player I've tried without complaint.
```
mediainfo --version
MediaInfo Command line, 
MediaInfoLib - v19.07
```
```
General
Unique ID                                : 49159443453231481903099452388142844008 (0x24FBC3B100B9F17B666BCFBBD6AD8868)
Complete name                            : Smallfoot (2018).mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 2.25 GiB
Duration                                 : 1 h 36 min
Overall bit rate                         : 3 344 kb/s
Movie name                               : Smallfoot
Encoded date                             : UTC 2018-12-23T01:11:27Z
Writing application                      : HandBrake 1.1.2 2018090500
Writing library                          : Lavf57.7.2

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings                          : CABAC / 5 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 5 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 1 h 36 min
Bit rate                                 : 2 637 kb/s
Width                                    : 1 920 pixels
Height                                   : 800 pixels
Display aspect ratio                     : 2.40:1
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.072
Stream size                              : 1.77 GiB (79%)
Writing library                          : x264 core 155 r2901 7d0ff22
Encoding settings                        : cabac=1 / ref=5 / deblock=1:1:1 / analyse=0x3:0x133 / me=umh / subme=10 / psy=1 / psy_rd=0.40:0.00 / mixed_ref=1 / me_range=24 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=24 / lookahead_threads=6 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=10 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=240 / keyint_min=24 / scenecut=40 / intra_refresh=0 / rc_lookahead=60 / rc=crf / mbtree=1 / crf=21.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / vbv_maxrate=62500 / vbv_bufsize=78125 / crf_max=0.0 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=1:0.60
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio
ID                                       : 2
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 1 h 36 min
Bit rate mode                            : Constant
Bit rate                                 : 640 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Bit depth                                : 16 bits
Compression mode                         : Lossy
Stream size                              : 441 MiB (19%)
Title                                    : Surround
Language                                 : English
Service kind                             : Complete Main
Default                                  : Yes
Forced                                   : No

Text #1
ID                                       : 3
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Language                                 : English
Default                                  : No
Forced                                   : No

Text #2
ID                                       : 4
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Language                                 : French
Default                                  : No
Forced                                   : No

Text #3
ID                                       : 5
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Language                                 : Portuguese
Default                                  : No
Forced                                   : No

Text #4
ID                                       : 6
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Language                                 : Spanish
Default                                  : No
Forced                                   : No

Menu
00:00:00.000                             : :Chapter 1
00:09:56.262                             : :Chapter 2
00:21:36.295                             : :Chapter 3
00:32:10.637                             : :Chapter 4
00:38:33.603                             : :Chapter 5
00:49:59.705                             : :Chapter 6
00:55:37.167                             : :Chapter 7
01:01:53.210                             : :Chapter 8
01:12:04.278                             : :Chapter 9
01:18:26.076                             : :Chapter 10
01:26:16.880                             : :Chapter 11
01:31:12.300                             : :Chapter 12
```

**Comment by bverkron** [comment]
FYI I found the issue for me. Turns out a hidden file with a nearly identical name to the actual video file somehow got created or perhaps came along for the ride in the torrent.

So 
`._Smallfoot (2018).mkv`
in addition to 
`Smallfoot (2018).mkv`

Glancing at the logs I at first didn't notice the ._ I just skimmed past the filename visually.  Removing the hidden file fixed the issue.

**Comment by Qstick** [comment]
Closing this in v3, the iso/img cases now bypass runtime sample check
