### ISSUE TITLE
Import failures can create excessive deleted events in the history view

### ISSUE THREAD

**Issue by addisonbabcock** [Radarr/Radarr#8444]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

If a download fails to import because the destination already exists Radarr can flood the history for that movie with deleted events. 
![image](https://user-images.githubusercontent.com/2836233/236274512-9ec86060-91c4-4fba-a56e-7dad005412c4.png)

![image](https://user-images.githubusercontent.com/2836233/236274548-92045668-36bf-46f2-956e-97ce13c696f0.png)

The history events are generated once per every run of the import task, so once per minute. Importing the files stuck in the queue resolves the situation and the events are no longer generated. It's also noteworthy that the files being "deleted" were already deleted previously as part of another upgrade. 

### Expected Behavior

A deleted event should only be generated if a file is being deleted. 

### Steps To Reproduce

1. Import a low quality copy of a movie (1080p in my case).
2. Start a download for a quality upgrade for that movie (2160p in my case). 
3. After the download completes but before radarr gets a chance to import add another cross seeded torrent for that movie. 
4. Only one of the torrents will be imported on the next queue refresh. 
5. There is now a download stuck in the queue because the destination already exists. 
6. Now on every run of the download queue refresh task, radarr will generate a file deleted event for a movie that has already been previously deleted (the 1080p file from step 1). This will continue until either the download is removed from the queue or manually imported. 

### Environment

```markdown
- OS: Ubuntu 23.04
- Radarr: 4.4.4.7068
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Not UI related
- Database: Sqlite 3.38.5
```

### What branch are you running?

Master

### Trace Logs?

Trace logs of the import task: https://gist.github.com/addisonbabcock/9acf5bd017f7c32a7f174832f1caa2d5

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have followed the steps in the wiki link above and provided the required trace logs that are relevant and show this issue.

**Comment by Qstick** [comment]
Is this solved by https://github.com/Radarr/Radarr/commit/488f8c71e8e6534c23ea6d6f97879f963ae8895e?

**Comment by bakerboy448** [comment]
still occurring on 4.6.1.7453
![image](https://github.com/Radarr/Radarr/assets/55419169/59386608-79c5-4b0f-8a7f-badfa8155da6)


Additionally, rather than just staying stuck in queue - it continually tries to reimport.

```
Name
/data/media/media/movies/Fast and Furious 10 (2023) {imdb-tt5433140}/Fast X (2023) {imdb-tt5433140} [AMZN][WEBDL-1080p][EAC3 5.1][h264]-FAMiLYFOREVER.mkv
Reason
File was deleted to import an upgrade
```
it's also trying to delete a file that's not on disk at all.

relevant logs
https://gist.github.com/bakerboy448/e6128ba67cfb02b89879813fe7189417
whole log file
https://gist.github.com/bakerboy448/774cd3135acfdd86233a37ab63454447

`Fast X (2023) {imdb-tt5433140} [MA][WEBDL-1080p][EAC3 Atmos 5.1][x264]-CMRG.mkv` is current on disk.
note this was a manual rename (group edited for file; then rename triggered)
![image](https://github.com/Radarr/Radarr/assets/55419169/b78f72de-51ca-42d9-a416-95c94d46970d)

**Comment by addisonbabcock** [comment]
I do have an extra bit of info for this. Restarting radarr will allow the blocked items in the queue to import. Not sure why that is, but I thought it was interesting and maybe helpful for finding the root cause. I can also confirm that this is still happening on 5.3.3.8523.
