### ISSUE TITLE
New bulk importer finds movies based on folder name but not the files within

### ISSUE THREAD

**Issue by Jleagle** [Radarr/Radarr#853]
**Description:**

My folder structure is: /Movies/Movie Name/original.file.name.mkv

When I use the new importer it adds the movies to the database but does not populate the quality, profile, trailer or any actual video files inside the folder making the status is "Missing".

Refreshing the movie from the list doesn't change anything.

The old importer works fine.

**Radarr Version:**

Ver. 0.2.0.375

**Logs:**

https://goo.gl/4WAOOJ

**Comment by galli-leo** [comment]
I think you don't have a profile set for the movies. At least that's what the logs tell me. Try and set a Profile (If you already have, try setting it again.). Then do a rescan disk again for the movie.

**Comment by Jleagle** [comment]
You're right, I didn't set a profile for anything. When I set one and refreshed it fixes it. I'm guessing the old importer forces or encourages a profile and that's why it works.

It still seems to be broken, as why would it need the profile to find the files and trailer link etc.

**Comment by galli-leo** [comment]
@Jleagle Well that's because it uses the normal import process for existing movies (which checks the profile for the cutoff quality). But I agree we should force a default profile.

**Comment by flo80** [comment]
Is there a way to bulk-edit movies so I can set a profile for all at my imported movies at once?

**Comment by Jleagle** [comment]
You can do it on the move edit page (/movieeditor).

**Comment by galli-leo** [comment]
Fixed in one of the latest releases.

**Comment by chromerobv** [comment]
this still isnt working for me. i've tried several profiles. it still imports the movie but shows no file.

17-3-28 17:03:38.9|Debug|RefreshMovieService|Finished movie refresh for Atlas Shrugged Part I
17-3-28 17:03:38.9|Trace|EventAggregator|Publishing MovieUpdatedEvent
17-3-28 17:03:38.9|Trace|EventAggregator|MovieUpdatedEvent -> DiskScanService
17-3-28 17:03:39.3|Info|DiskScanService|Scanning disk for Atlas Shrugged Part I
17-3-28 17:03:39.3|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-3-28 17:03:39.3|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-3-28 17:03:39.3|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-3-28 17:03:39.3|Debug|DiskScanService|Scanning '/mnt/movies/Atlas Shrugged Part I' for video files
17-3-28 17:03:39.3|Debug|DiskScanService|1 video files were found in /mnt/movies/Atlas Shrugged Part I
17-3-28 17:03:39.3|Trace|DiskScanService|Finished getting episode files for: [tt0480239][Atlas Shrugged Part I] [00:00:00.0207117]
17-3-28 17:03:39.3|Debug|DiskScanService|[tt0480239][Atlas Shrugged Part I] Cleaning up media files in DB
17-3-28 17:03:39.3|Debug|ImportDecisionMaker|Analyzing 1/1 files.
17-3-28 17:03:39.3|Debug|Parser|Parsing string 'Atlas Shrugged Part I.avi'
17-3-28 17:03:39.3|Debug|Parser|Unable to parse Atlas Shrugged Part I.avi
17-3-28 17:03:39.3|Debug|Parser|Attempting to parse episode info using directory and file names. Atlas Shrugged Part I
17-3-28 17:03:39.3|Debug|Parser|Parsing string 'Atlas Shrugged Part I Atlas Shrugged Part I.avi'
17-3-28 17:03:39.3|Debug|Parser|Unable to parse Atlas Shrugged Part I Atlas Shrugged Part I.avi
17-3-28 17:03:39.3|Debug|Parser|Attempting to parse episode info using directory name. Atlas Shrugged Part I
17-3-28 17:03:39.3|Debug|Parser|Parsing string 'Atlas Shrugged Part I.avi'
17-3-28 17:03:39.3|Debug|Parser|Unable to parse Atlas Shrugged Part I.avi
17-3-28 17:03:39.3|Warn|ParsingService|Unable to parse movie info from path /mnt/movies/Atlas Shrugged Part I/Atlas Shrugged Part I.avi
17-3-28 17:03:39.3|Trace|DiskScanService|Import decisions complete for: [tt0480239][Atlas Shrugged Part I] [00:00:00.0060209]
17-3-28 17:03:39.3|Debug|ImportApprovedMovie|Decisions: 1
17-3-28 17:03:39.3|Info|DiskScanService|Completed scanning disk for Atlas Shrugged Part I

**Comment by chromerobv** [comment]
also if you look at when i import it shows most with "Movie file not found"

![radarr-1](https://cloud.githubusercontent.com/assets/10504727/24432875/c7e755de-13d9-11e7-906c-db2fd066c1a8.PNG)

**Comment by onedr0p** [comment]
@chromerobv what are the full movie filenames for the movies not found?

**Comment by chromerobv** [comment]
a couple examples that are from the above image
Animal House/Animal House.mkv
Anomalisa/Anomalisa.mkv

that's pretty much how all my movies are.

**Comment by onedr0p** [comment]
Try adding year to at least the folder, if not.. the folder and filename.

**Comment by phynias** [comment]
i will but not sure why the year is needed to find a file. the imdb is already found from the above image. so finding a file shouldn't need a year. i could see this being needed if it was being identified wrong. not to mention if this is the case, i have no desire to redo all my movie folders/files. it would screw up so many other things.

**Comment by arm3n** [comment]
Agreed - would donate a beer if functionality to rename folders after the scan already determined the import with lacking years.
