### ISSUE TITLE
Unable to import upgraded movie (via download) with same title, year and quality

### ISSUE THREAD

**Issue by jscottdouglas** [Radarr/Radarr#895]
**Description:**
Importer not overwriting exsiting file, for some reason it removes the file from the radarr db but then when it tries to import, Radarr refuses to overwrite the file that is already there, this is when it finds a better 1080p quality (ie larger remuxed file)

ImportApprovedMovie	Couldn't import movie /hd/03/media/downloads/complete/movie/I.Daniel.Blake.2016.FRA.BluRay.Remux.1080p.AVC.DTS-HD.MA.5.1-HiFi/1rTTvrdf4S2STFf7CpMVHwEtZ97y3WeSC.mkv: Destination already exists [/hd/00/media/sorted/media/movie/I, Daniel Blake (2016)/I, Daniel Blake (2016) Bluray-1080p (tt5168192).mkv]	5:17pm
ImportApprovedMovie	Couldn't import movie /hd/03/media/downloads/complete/movie/I.Daniel.Blake.2016.FRA.BluRay.Remux.1080p.AVC.DTS-HD.MA.5.1-HiFi/1rTTvrdf4S2STFf7CpMVHwEtZ97y3WeSC.mkv: Destination already exists [/hd/00/media/sorted/media/movie/I, Daniel Blake (2016)/I, Daniel Blake (2016) Bluray-1080p (tt5168192).mkv]

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:**
Latest Nightly
**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by onedr0p** [comment]
I just upgraded a release and it replaced the movie for me. Do you have Complete download handling enabled?

**Comment by jscottdouglas** [comment]
It's not an upgrade per-say, the 1080p file is being replaced by another 1080p file, both already blu-ray, and yes i have complete download handling enabled. 95% of my downloads are NZB

**Comment by onedr0p** [comment]
Can you please try this, I think I fixed it..

**Comment by onedr0p** [comment]
Closing.. let me know if you still have problems on the latest nightly.

**Comment by secjoe88** [comment]
i seem to still have this issue. i'm on the latest nightly

17-4-7 19:35:43.7|Warn|ImportApprovedMovie|Couldn't import movie /mnt/media_rw/5855-0B3B/media/downloaded/movies/The Wind Rises 2013 [1080p BluRay flac x264] - THORA/The_Wind_Rises_2013_[1080p,BluRay,flac,x264]_-_THORA.mkv

[v0.2.0.573] System.IO.IOException: Destination already exists [/media/final/movies/Wind Rises, The (2013)/Wind Rises, The (2013).mkv]
  at NzbDrone.Common.Disk.DiskTransferService.ClearTargetPath (System.String targetPath, System.Boolean overwrite) [0x0001e] in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskTransferService.cs:331 
  at NzbDrone.Common.Disk.DiskTransferService.TransferFile (System.String sourcePath, System.String targetPath, NzbDrone.Common.Disk.TransferMode mode, System.Boolean overwrite, NzbDrone.Common.Disk.DiskTransferVerificationMode verificationMode) [0x0021f] in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskTransferService.cs:244 
  at NzbDrone.Common.Disk.DiskTransferService.TransferFile (System.String sourcePath, System.String targetPath, NzbDrone.Common.Disk.TransferMode mode, System.Boolean overwrite, System.Boolean verified) [0x0000e] in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskTransferService.cs:183 
  at NzbDrone.Core.MediaFiles.MovieFileMovingService.TransferFile (NzbDrone.Core.MediaFiles.MovieFile movieFile, NzbDrone.Core.Tv.Movie movie, System.String destinationFilePath, NzbDrone.Common.Disk.TransferMode mode) [0x0012b] in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:117 
  at NzbDrone.Core.MediaFiles.MovieFileMovingService.MoveMovieFile (NzbDrone.Core.MediaFiles.MovieFile movieFile, NzbDrone.Core.Parser.Model.LocalMovie localMovie) [0x00052] in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:79 
  at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile (NzbDrone.Core.MediaFiles.MovieFile movieFile, NzbDrone.Core.Parser.Model.LocalMovie localMovie, System.Boolean copyOnly) [0x0009d] in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:66 
  at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedMovie.Import (System.Collections.Generic.List`1[T] decisions, System.Boolean newDownload, NzbDrone.Core.Download.DownloadClientItem downloadClientItem, NzbDrone.Core.MediaFiles.EpisodeImport.ImportMode importMode) [0x0026b] in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedMovie.cs:107

**Comment by galli-leo** [comment]
@secjoe88 Does Radarr know about the existing movie?

**Comment by secjoe88** [comment]
yes. it knows of the file, as it shows up under the 'Files' tab in the movie detail.

**Comment by lilbrimstone** [comment]
I have the same issue

**Comment by galli-leo** [comment]
@lilbrimstone Have you verified Radarr knows about the file?

**Comment by lilbrimstone** [comment]
The torrent was added automatically through Radarr, so I assume it does. Any downloads that aren't upgrades work fine.

**Comment by galli-leo** [comment]
@lilbrimstone Can you verify that by going into the files tab when you open the movie's detail page?

**Comment by lilbrimstone** [comment]
I've already manually imported it. I'll check next time an upgrade occurs.
