### ISSUE TITLE
list couchpotato connection issue

### ISSUE THREAD

**Issue by madmanali93** [Radarr/Radarr#934]
Connection to couchpotato fails. Image below shows the issue

 [image](http://imgur.com/TY8NRJb)

radarr version 0.2.0.375

log:

> 17-2-27 16:59:50.2|Warn|CouchPotatoImport|Unable to connect to list
>  
> [v0.2.0.375] System.ArgumentNullException: Value cannot be null.
> Parameter name: source
>   at System.Linq.Enumerable.Any[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00010] in <63992662b765477a898ef49cdcc99ee2>:0
>   at NzbDrone.Core.NetImport.CouchPotato.CouchPotatoParser.ParseResponse (NzbDrone.Core.NetImport.NetImportResponse importResponse) [0x00075] in <a65e619312484e57bf6a607be1e6496a>:0
>   at NzbDrone.Core.NetImport.HttpNetImportBase`1[TSettings].FetchPage (NzbDrone.Core.NetImport.NetImportRequest request, NzbDrone.Core.NetImport.IParseNetImportResponse parser) [0x00008] in <a65e619312484e57bf6a607be1e6496a>:0
>   at NzbDrone.Core.NetImport.HttpNetImportBase`1[TSettings].TestConnection () [0x00024] in <a65e619312484e57bf6a607be1e6496a>:0
>  
> 17-2-27 16:59:50.2|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: ^M
>  -- Unable to connect to list, check the log for more details

**Comment by onedr0p** [comment]
Can you confirm you do not have a baseURL and that you aren't using SSL?

**Comment by madmanali93** [comment]
No ssl and localhost:5050/ works without anything else.

**Comment by galli-leo** [comment]
@onedr0p Seems like source should be nullable?

**Comment by onedr0p** [comment]
Source where? I don't see it in the couchpotato api or in the parser, this error confuses me lol

**Comment by madmanali93** [comment]
I believe source refers to **System.Linq.Enumerable.Any** which has source as a parameter. Not sure where it is used yet.

```
 public static bool Any<TSource>(
	this IEnumerable<TSource> source,
	Func<TSource, bool> predicate
)
```

**Comment by onedr0p** [comment]
If you can provide me with access to your couch potato I can prolly fix this but I cannot replicate your issue. Hit me up on discord if you are willing to help me debug this error.

**Comment by stewsta** [comment]
This issue is also happening to me, just installed Radarr and trying to import from CouchPotato running under same user on same system (Ubuntu server).

Couchpotato is running over HTTP (insecure) with URL base (/couchpotato) on default port (5050), no authentication.
Radarr is running the same way.

These are both reverse proxied through HTTPS on apache2, but the import is running through localhost without reverse proxy in the way.

**Comment by onedr0p** [comment]
Fixed.

**Comment by evenwebb** [comment]
Ive been getting exactly the same issue for months, tested again today and still getting the same error as @madmanali93. Running the latest version.

@madmanali93 Did you get yours working?

**Comment by madmanali93** [comment]
@evenwebb just update radarr it should be fixed.
